import type { Level } from '../../types/content';

export const level11: Level = {
  id: 11,
  titleEn: 'Days & Time',
  titleCkb: 'ڕۆژ و دەم',
  icon: '📅',
  objectiveEn: 'Say the days of the week and tell the time.',
  objectiveCkb: 'ڕۆژێن حەفتیێ بزانە و دەمژمێرێ بڵێ.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l11-monday',
      en: 'Monday',
      ckb: 'دووشەم',
      pos: 'noun',
      emoji: '📅',
      phonetic: '/ˈmʌndeɪ/',
      exampleEn: 'Today is Monday.',
      exampleCkb: 'ئەڤڕۆ دووشەمە.',
      category: 'days',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-tuesday',
      en: 'Tuesday',
      ckb: 'سێشەم',
      pos: 'noun',
      emoji: '📅',
      phonetic: '/ˈtjuːzdeɪ/',
      exampleEn: 'Tomorrow is Tuesday.',
      exampleCkb: 'سەبەی سێشەمە.',
      category: 'days',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-wednesday',
      en: 'Wednesday',
      ckb: 'چارشەم',
      pos: 'noun',
      emoji: '📅',
      phonetic: '/ˈwɛnzdeɪ/',
      exampleEn: 'Today is Wednesday.',
      exampleCkb: 'ئەڤڕۆ چارشەمە.',
      category: 'days',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-thursday',
      en: 'Thursday',
      ckb: 'پێنجشەم',
      pos: 'noun',
      emoji: '📅',
      phonetic: '/ˈθɜːzdeɪ/',
      exampleEn: 'Today is Thursday.',
      exampleCkb: 'ئەڤڕۆ پێنجشەمە.',
      category: 'days',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-friday',
      en: 'Friday',
      ckb: 'ئینی',
      pos: 'noun',
      emoji: '📅',
      phonetic: '/ˈfraɪdeɪ/',
      exampleEn: 'Tomorrow is Friday.',
      exampleCkb: 'سەبەی ئینی یە.',
      category: 'days',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-saturday',
      en: 'Saturday',
      ckb: 'شەممی',
      pos: 'noun',
      emoji: '📅',
      phonetic: '/ˈsætədeɪ/',
      exampleEn: 'Yesterday was Saturday.',
      exampleCkb: 'دوهی شەممی بوو.',
      category: 'days',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-sunday',
      en: 'Sunday',
      ckb: 'یەکشەم',
      pos: 'noun',
      emoji: '📅',
      phonetic: '/ˈsʌndeɪ/',
      exampleEn: 'Today is Sunday.',
      exampleCkb: 'ئەڤڕۆ یەکشەمە.',
      category: 'days',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-morning',
      en: 'morning',
      ckb: 'سپێدە',
      pos: 'noun',
      emoji: '🌅',
      phonetic: '/ˈmɔːnɪŋ/',
      exampleEn: 'Good morning.',
      exampleCkb: 'سپێدە باش.',
      category: 'time',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-afternoon',
      en: 'afternoon',
      ckb: 'پاش نیڤڕۆ',
      pos: 'noun',
      emoji: '☀️',
      phonetic: '/ˌɑːftəˈnuːn/',
      exampleEn: 'I study in the afternoon.',
      exampleCkb: 'ئەز پاش نیڤڕۆ دخوینم.',
      category: 'time',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-evening',
      en: 'evening',
      ckb: 'ئێڤار',
      pos: 'noun',
      emoji: '🌆',
      phonetic: '/ˈiːvnɪŋ/',
      exampleEn: 'Good evening.',
      exampleCkb: 'ئێوارە باش.',
      category: 'time',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-night',
      en: 'night',
      ckb: 'شەڤ',
      pos: 'noun',
      emoji: '🌙',
      phonetic: '/naɪt/',
      exampleEn: 'Good night.',
      exampleCkb: 'شەڤ باش.',
      category: 'time',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-today',
      en: 'today',
      ckb: 'ئەڤڕۆ',
      pos: 'noun',
      emoji: '📆',
      phonetic: '/təˈdeɪ/',
      exampleEn: 'Today is Friday.',
      exampleCkb: 'ئەڤڕۆ ئینی یە.',
      category: 'time',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-tomorrow',
      en: 'tomorrow',
      ckb: 'سەبەی',
      pos: 'noun',
      emoji: '🔜',
      phonetic: '/təˈmɒrəʊ/',
      exampleEn: 'See you tomorrow.',
      exampleCkb: 'ئەز تە سەبەی دبینم.',
      category: 'time',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l11-yesterday',
      en: 'yesterday',
      ckb: 'دوهی',
      pos: 'noun',
      emoji: '🔙',
      phonetic: '/ˈjɛstədeɪ/',
      exampleEn: 'Yesterday was Sunday.',
      exampleCkb: 'دوهی یەکشەم بوو.',
      category: 'time',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'What day is it?', ckb: 'ئەڤڕۆ چ ڕۆژە؟' },
    { en: 'Today is Monday.', ckb: 'ئەڤڕۆ دووشەمە.' },
    { en: 'What time is it?', ckb: 'دەمژمێر چەندە؟' },
    { en: "It is three o'clock.", ckb: 'دەمژمێر سێ یە.' },
    { en: 'Tomorrow is Friday.', ckb: 'سەبەی ئینی یە.' },
    { en: 'Yesterday was Sunday.', ckb: 'دوهی یەکشەم بوو.' },
  ],
  conversation: [
    { characterId: 'dara', en: 'What day is it today?', ckb: 'ئەڤڕۆ چ ڕۆژە؟' },
    { characterId: 'rojin', en: 'Today is Monday.', ckb: 'ئەڤڕۆ دووشەمە.' },
    { characterId: 'dara', en: 'What time is it?', ckb: 'دەمژمێر چەندە؟' },
    { characterId: 'rojin', en: "It is three o'clock.", ckb: 'دەمژمێر سێ یە.' },
    { characterId: 'dara', en: 'Tomorrow is Tuesday.', ckb: 'سەبەی سێشەمە.' },
    { characterId: 'rojin', en: 'Yes. See you tomorrow!', ckb: 'بەلێ. ئەز تە سەبەی دبینم!' },
  ],
};
