import type { Level } from '../../types/content';

export const level23: Level = {
  id: 23,
  titleEn: 'There Is / There Are',
  titleCkb: 'هەیە / هەنە',
  icon: '🪑',
  objectiveEn: 'Describe what is in a place using "there is" and "there are".',
  objectiveCkb: 'فێر ببە چەوا ب «there is» و «there are» بڵێ ل جهەکی چ هەیە و چ نینە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l23-there',
      en: 'there',
      ckb: 'ل ویر',
      pos: 'other',
      emoji: '👉',
      phonetic: '/ðeə(r)/',
      exampleEn: 'There is a table.',
      exampleCkb: 'ل ویر مێزەک هەیە.',
      category: 'other',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-room',
      en: 'room',
      ckb: 'ژوور',
      pos: 'noun',
      emoji: '🛏️',
      phonetic: '/ruːm/',
      exampleEn: 'The room is big.',
      exampleCkb: 'ژوور مەزنە.',
      category: 'places',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-house',
      en: 'house',
      ckb: 'مال',
      pos: 'noun',
      emoji: '🏠',
      phonetic: '/haʊs/',
      exampleEn: 'The house has two doors.',
      exampleCkb: 'ل مالێ دوو دەرگەه هەنە.',
      category: 'places',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-shop',
      en: 'shop',
      ckb: 'دوکان',
      pos: 'noun',
      emoji: '🏪',
      phonetic: '/ʃɒp/',
      exampleEn: 'There is a shop on the street.',
      exampleCkb: 'دوکانەک ل سەر جاددێ هەیە.',
      category: 'places',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-street',
      en: 'street',
      ckb: 'جاددە',
      pos: 'noun',
      emoji: '🛣️',
      phonetic: '/striːt/',
      exampleEn: 'There are cars on the street.',
      exampleCkb: 'ل سەر جاددێ ترومبێل هەنە.',
      category: 'places',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-car',
      en: 'car',
      ckb: 'ترومبێل',
      pos: 'noun',
      emoji: '🚗',
      phonetic: '/kɑː(r)/',
      exampleEn: 'There is a car outside.',
      exampleCkb: 'ل دەرڤە ترومبێلەک هەیە.',
      category: 'things',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-people',
      en: 'people',
      ckb: 'خەلک',
      pos: 'noun',
      emoji: '🧑‍🤝‍🧑',
      phonetic: '/ˈpiːpl/',
      exampleEn: 'There are three people in the room.',
      exampleCkb: 'ل ژوورێ سێ کەس هەنە.',
      category: 'people',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-chair',
      en: 'chair',
      ckb: 'کورسی',
      pos: 'noun',
      emoji: '🪑',
      phonetic: '/tʃeə(r)/',
      exampleEn: 'There are two chairs.',
      exampleCkb: 'دوو کورسی هەنە.',
      category: 'things',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-table',
      en: 'table',
      ckb: 'مێز',
      pos: 'noun',
      emoji: '🍽️',
      phonetic: '/ˈteɪbl/',
      exampleEn: 'There is a table in the room.',
      exampleCkb: 'ل ژوورێ مێزەک هەیە.',
      category: 'things',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-window',
      en: 'window',
      ckb: 'پەنجەرە',
      pos: 'noun',
      emoji: '🪟',
      phonetic: '/ˈwɪndəʊ/',
      exampleEn: 'There are two windows.',
      exampleCkb: 'دوو پەنجەرە هەنە.',
      category: 'things',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-door',
      en: 'door',
      ckb: 'دەرگەه',
      pos: 'noun',
      emoji: '🚪',
      phonetic: '/dɔː(r)/',
      exampleEn: 'There is a door in the room.',
      exampleCkb: 'ل ژوورێ دەرگەهەک هەیە.',
      category: 'things',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l23-building',
      en: 'building',
      ckb: 'باڵەخانە',
      pos: 'noun',
      emoji: '🏢',
      phonetic: '/ˈbɪldɪŋ/',
      exampleEn: 'The building is big.',
      exampleCkb: 'باڵەخانە مەزنە.',
      category: 'places',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'There is a table.', ckb: 'مێزەک هەیە.' },
    { en: 'There are two chairs.', ckb: 'دوو کورسی هەنە.' },
    { en: 'There is a car outside.', ckb: 'ل دەرڤە ترومبێلەک هەیە.' },
    { en: 'There are three people in the room.', ckb: 'ل ژوورێ سێ کەس هەنە.' },
    { en: "There isn't a window.", ckb: 'پەنجەرەک نینە.' },
    { en: "There aren't any shops.", ckb: 'هیڤ دوکان نینە.' },
    { en: 'Is there a shop here?', ckb: 'ل ڤێرێ دوکانەک هەیە؟' },
    { en: "Yes, there is. / No, there isn't.", ckb: 'بەلێ، هەیە. / نەخێر، نینە.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Welcome to my house!', ckb: 'ب خێر هاتوی بۆ مالا من!' },
    { characterId: 'dara', en: 'Thank you! The room is big.', ckb: 'سوپاس! ژوور مەزنە.' },
    { characterId: 'shirin', en: 'Yes. There is a table and four chairs.', ckb: 'بەلێ. مێزەک و چار کورسی هەنە.' },
    { characterId: 'dara', en: 'Is there a window?', ckb: 'پەنجەرەک هەیە؟' },
    { characterId: 'shirin', en: 'Yes, there are two windows.', ckb: 'بەلێ، دوو پەنجەرە هەنە.' },
    { characterId: 'dara', en: 'Is there a TV in the room?', ckb: 'ل ژوورێ تەلەفزیۆنەک هەیە؟' },
    { characterId: 'shirin', en: "No, there isn't. But there are many books.", ckb: 'نەخێر، نینە. بەلکو گەلەک پەرتووک هەنە.' },
    { characterId: 'dara', en: 'I like your room!', ckb: 'ئەز حەز ژ ژوورا تە دکەم!' },
  ],
};
