import type { Level } from '../../types/content';

export const level06: Level = {
  id: 6,
  titleEn: 'People & Basic Descriptions',
  titleCkb: 'خەلک و وەسفکرن',
  icon: '😊',
  objectiveEn: 'Describe people and things with simple adjectives.',
  objectiveCkb: 'مرۆڤ و تشتان ب پەیڤێن سادە وەسف بکە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l6-big',
      en: 'Big',
      ckb: 'مەزن',
      pos: 'adjective',
      emoji: '🐘',
      phonetic: '/bɪɡ/',
      exampleEn: 'My family is big.',
      exampleCkb: 'خێزانا من مەزنە.',
      category: 'description',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-small',
      en: 'Small',
      ckb: 'بچووک',
      pos: 'adjective',
      emoji: '🐜',
      phonetic: '/smɔːl/',
      exampleEn: 'The baby is small.',
      exampleCkb: 'گیانوێ بچووکە.',
      category: 'description',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-tall',
      en: 'Tall',
      ckb: 'بلند',
      pos: 'adjective',
      emoji: '🦒',
      phonetic: '/tɔːl/',
      exampleEn: 'My father is tall.',
      exampleCkb: 'باڤێ من بلندە.',
      category: 'description',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-short',
      en: 'Short',
      ckb: 'کن',
      pos: 'adjective',
      emoji: '🐭',
      phonetic: '/ʃɔːrt/',
      exampleEn: 'My brother is short.',
      exampleCkb: 'برایێ من کنە.',
      category: 'description',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-young',
      en: 'Young',
      ckb: 'گەنج',
      pos: 'adjective',
      emoji: '🧒',
      phonetic: '/jʌŋ/',
      exampleEn: 'My brother is young.',
      exampleCkb: 'برایێ من گەنجە.',
      category: 'description',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-old',
      en: 'Old',
      ckb: 'پیر',
      pos: 'adjective',
      emoji: '👴',
      phonetic: '/oʊld/',
      exampleEn: 'My grandfather is old.',
      exampleCkb: 'بابیرێ من پیرە.',
      category: 'description',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-happy',
      en: 'Happy',
      ckb: 'دڵخۆش',
      pos: 'adjective',
      emoji: '😊',
      phonetic: '/ˈhæpi/',
      exampleEn: 'She is happy.',
      exampleCkb: 'ئەو دڵخۆشە.',
      category: 'feelings',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-sad',
      en: 'Sad',
      ckb: 'خەمگین',
      pos: 'adjective',
      emoji: '😢',
      phonetic: '/sæd/',
      exampleEn: 'The child is sad.',
      exampleCkb: 'زارۆک خەمگینە.',
      category: 'feelings',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-good',
      en: 'Good',
      ckb: 'باش',
      pos: 'adjective',
      emoji: '👍',
      phonetic: '/ɡʊd/',
      exampleEn: 'It is good.',
      exampleCkb: 'ئەو باشە.',
      category: 'description',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-bad',
      en: 'Bad',
      ckb: 'خراب',
      pos: 'adjective',
      emoji: '👎',
      phonetic: '/bæd/',
      exampleEn: 'It is bad.',
      exampleCkb: 'ئەو خرابە.',
      category: 'description',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-fast',
      en: 'Fast',
      ckb: 'خێرا',
      pos: 'adjective',
      emoji: '⚡',
      phonetic: '/fæst/',
      exampleEn: 'He is fast.',
      exampleCkb: 'ئەو خێرایە.',
      category: 'description',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l6-slow',
      en: 'Slow',
      ckb: 'ب حەوانێ',
      pos: 'adjective',
      emoji: '🐢',
      phonetic: '/sloʊ/',
      exampleEn: 'It is slow.',
      exampleCkb: 'ئەو ب حەوانێ یە.',
      category: 'description',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'He is tall.', ckb: 'ئەو بلندە.' },
    { en: 'She is happy.', ckb: 'ئەو دڵخۆشە.' },
    { en: 'My family is big.', ckb: 'خێزانا من مەزنە.' },
    { en: 'The baby is small.', ckb: 'گیانوێ بچووکە.' },
    { en: 'She is sad.', ckb: 'ئەو خەمگینە.' },
    { en: 'He is young.', ckb: 'ئەو گەنجە.' },
  ],
  conversation: [
    {
      characterId: 'dara',
      en: 'This is my grandfather.',
      ckb: 'ئەڤە بابیرێ منە.',
    },
    { characterId: 'rojin', en: 'He is old.', ckb: 'ئەو پیرە.' },
    {
      characterId: 'dara',
      en: 'He is old and happy.',
      ckb: 'ئەو پیرە و دڵخۆشە.',
    },
    {
      characterId: 'rojin',
      en: 'This is my brother.',
      ckb: 'ئەڤە برایێ منە.',
    },
    {
      characterId: 'rojin',
      en: 'He is tall and young.',
      ckb: 'ئەو بلندە و گەنجە.',
    },
    {
      characterId: 'dara',
      en: 'My brother is short.',
      ckb: 'برایێ من کنە.',
    },
    { characterId: 'rojin', en: 'But he is fast!', ckb: 'بەلکو ئەو خێرایە!' },
  ],
};
