import type { Level } from '../../types/content';

export const level04: Level = {
  id: 4,
  titleEn: 'Colors',
  titleCkb: 'ڕەنگ',
  icon: '🎨',
  objectiveEn: 'Name ten colors and describe things with them.',
  objectiveCkb: 'دەه ڕەنگ بناڤ ببە و تشتان ب ڕەنگان وەسف بکە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l4-red',
      en: 'Red',
      ckb: 'سور',
      pos: 'color',
      emoji: '🔴',
      phonetic: '/red/',
      exampleEn: 'The apple is red.',
      exampleCkb: 'سیڤ سورە.',
      category: 'Colors',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-blue',
      en: 'Blue',
      ckb: 'شین',
      pos: 'color',
      emoji: '🔵',
      phonetic: '/bluː/',
      exampleEn: 'The car is blue.',
      exampleCkb: 'ترومبێل شینە.',
      category: 'Colors',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-green',
      en: 'Green',
      ckb: 'کێسک',
      pos: 'color',
      emoji: '🟢',
      phonetic: '/ɡriːn/',
      exampleEn: 'The tree is green.',
      exampleCkb: 'دار کێسکە.',
      category: 'Colors',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-yellow',
      en: 'Yellow',
      ckb: 'زەرد',
      pos: 'color',
      emoji: '🟡',
      phonetic: '/ˈjeləʊ/',
      exampleEn: 'The sun is yellow.',
      exampleCkb: 'ڕۆژ زەردە.',
      category: 'Colors',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-black',
      en: 'Black',
      ckb: 'رەش',
      pos: 'color',
      emoji: '⚫',
      phonetic: '/blæk/',
      exampleEn: 'The cat is black.',
      exampleCkb: 'کتیک رەشە.',
      category: 'Colors',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-white',
      en: 'White',
      ckb: 'سپی',
      pos: 'color',
      emoji: '⚪',
      phonetic: '/waɪt/',
      exampleEn: 'The milk is white.',
      exampleCkb: 'شیر سپییە.',
      category: 'Colors',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-orange',
      en: 'Orange',
      ckb: 'پیرتەقالی',
      pos: 'color',
      emoji: '🟠',
      phonetic: '/ˈɒrɪndʒ/',
      exampleEn: 'The carrot is orange.',
      exampleCkb: 'گێزەر پیرتەقالییە.',
      category: 'Colors',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-pink',
      en: 'Pink',
      ckb: 'پەمەیی',
      pos: 'color',
      emoji: '🌸',
      phonetic: '/pɪŋk/',
      exampleEn: 'The flower is pink.',
      exampleCkb: 'گول پەمەیییە.',
      category: 'Colors',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-brown',
      en: 'Brown',
      ckb: 'قاوەیی',
      pos: 'color',
      emoji: '🟤',
      phonetic: '/braʊn/',
      exampleEn: 'The bread is brown.',
      exampleCkb: 'نان قاوەیییە.',
      category: 'Colors',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l4-purple',
      en: 'Purple',
      ckb: 'مۆر',
      pos: 'color',
      emoji: '🟣',
      phonetic: '/ˈpɜːpəl/',
      exampleEn: 'The flower is purple.',
      exampleCkb: 'گول مۆرە.',
      category: 'Colors',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'It is red.', ckb: 'ئەو سورە. — «It is» + ڕەنگ: ئەو ... ـە' },
    { en: 'The car is blue.', ckb: 'ترومبێل شینە. — ناڤ + is + ڕەنگ' },
    { en: 'What color is it?', ckb: 'ئەو ب چ ڕەنگییە؟ — بۆ پسیارکرنا ڕەنگی' },
    { en: 'Is it yellow?', ckb: 'ئەو زەردە؟ — پسیارا بەلێ/نەخێر' },
    { en: 'Yes, it is.', ckb: 'بەلێ، ئەو هەیە. — بەرسڤا بەلێ' },
    { en: 'No, it is green.', ckb: 'نەخێر، ئەو کێسکە. — بەرسڤا نەخێر دگەل راستیێ' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'What color is it?', ckb: 'ئەو ب چ ڕەنگییە؟' },
    { characterId: 'azad', en: 'It is red.', ckb: 'ئەو سورە.' },
    { characterId: 'shirin', en: 'Yes! And the car?', ckb: 'بەلێ! و ترومبێل؟' },
    { characterId: 'azad', en: 'The car is blue.', ckb: 'ترومبێل شینە.' },
    { characterId: 'shirin', en: 'Good! And the tree?', ckb: 'باشە! و دار؟' },
    { characterId: 'azad', en: 'It is green.', ckb: 'ئەو کێسکە.' },
    { characterId: 'shirin', en: 'And the sun?', ckb: 'و ڕۆژ؟' },
    { characterId: 'azad', en: 'It is yellow!', ckb: 'ئەو زەردە!' },
  ],
};
