import type { Level } from '../../types/content';

export const level18: Level = {
  id: 18,
  titleEn: 'Basic Questions',
  titleCkb: 'پرسیارێن بنچینەیی',
  icon: '❓',
  objectiveEn: 'Ask and answer basic questions with what, where, who, when, why and how.',
  objectiveCkb: 'ب چی، ل کو، کێ، کەی، بۆچی و چەوا پرسیاران بکە و بەرسڤان بدە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l18-what',
      en: 'what',
      ckb: 'چی',
      pos: 'question',
      emoji: '❓',
      phonetic: '/wʌt/',
      exampleEn: 'What is this?',
      exampleCkb: 'ئەڤ چیە؟',
      category: 'questions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-where',
      en: 'where',
      ckb: 'ل کو',
      pos: 'question',
      emoji: '📍',
      phonetic: '/weər/',
      exampleEn: 'Where are you?',
      exampleCkb: 'تو ل کو یی؟',
      category: 'questions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-who',
      en: 'who',
      ckb: 'کێ',
      pos: 'question',
      emoji: '👤',
      phonetic: '/huː/',
      exampleEn: 'Who is he?',
      exampleCkb: 'ئەو کێیە؟',
      category: 'questions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-when',
      en: 'when',
      ckb: 'کەی',
      pos: 'question',
      emoji: '🕐',
      phonetic: '/wen/',
      exampleEn: 'When do you sleep?',
      exampleCkb: 'تو کەی دنووی؟',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-why',
      en: 'why',
      ckb: 'بۆچی',
      pos: 'question',
      emoji: '🤔',
      phonetic: '/waɪ/',
      exampleEn: 'Why are you sad?',
      exampleCkb: 'تو بۆچی ب خەم یی؟',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-how',
      en: 'how',
      ckb: 'چەوا',
      pos: 'question',
      emoji: '💭',
      phonetic: '/haʊ/',
      exampleEn: 'How are you?',
      exampleCkb: 'تو چەوا یی؟',
      category: 'questions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-how-are-you',
      en: 'How are you?',
      ckb: 'تو چەوا یی؟',
      pos: 'phrase',
      emoji: '🙂',
      phonetic: '/haʊ ɑːr juː/',
      exampleEn: 'How are you? I am fine.',
      exampleCkb: 'تو چەوا یی؟ ئەز باش مە.',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-what-is-this',
      en: 'What is this?',
      ckb: 'ئەڤ چیە؟',
      pos: 'phrase',
      emoji: '👆',
      phonetic: '/wʌt ɪz ðɪs/',
      exampleEn: 'What is this? It is a book.',
      exampleCkb: 'ئەڤ چیە؟ ئەڤ پەرتووکەکە.',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-where-is',
      en: 'Where is...?',
      ckb: '... ل کویە؟',
      pos: 'phrase',
      emoji: '🗺️',
      phonetic: '/weər ɪz/',
      exampleEn: 'Where is the school?',
      exampleCkb: 'قوتابخانە ل کویە؟',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-how-much',
      en: 'How much?',
      ckb: 'ب چەند؟',
      pos: 'phrase',
      emoji: '💰',
      phonetic: '/haʊ mʌtʃ/',
      exampleEn: 'How much is it?',
      exampleCkb: 'ئەڤ ب چەندە؟',
      category: 'questions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-how-many',
      en: 'How many?',
      ckb: 'چەند؟',
      pos: 'phrase',
      emoji: '🔢',
      phonetic: '/haʊ ˈmeni/',
      exampleEn: 'How many apples do you have?',
      exampleCkb: 'چەند سیڤێن تە هەنە؟',
      category: 'questions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l18-what-is-your-name',
      en: 'What is your name?',
      ckb: 'ناڤێ تە چیە؟',
      pos: 'phrase',
      emoji: '📛',
      phonetic: '/wʌt ɪz jʊər neɪm/',
      exampleEn: 'What is your name? My name is Dara.',
      exampleCkb: 'ناڤێ تە چیە؟ ناڤێ من دارا یە.',
      category: 'questions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'What is this?', ckb: 'ئەڤ چیە؟' },
    { en: 'Where are you?', ckb: 'تو ل کو یی؟' },
    { en: 'Who is she?', ckb: 'ئەو کێیە؟' },
    { en: 'When do you sleep?', ckb: 'تو کەی دنووی؟' },
    { en: 'Why are you sad?', ckb: 'تو بۆچی ب خەم یی؟' },
    { en: 'How are you?', ckb: 'تو چەوا یی؟' },
    { en: 'How much is it?', ckb: 'ئەڤ ب چەندە؟' },
  ],
  conversation: [
    { characterId: 'dara', en: 'Hello! What is your name?', ckb: 'سلاو! ناڤێ تە چیە؟' },
    { characterId: 'shirin', en: 'My name is Shirin.', ckb: 'ناڤێ من شیرینە.' },
    { characterId: 'dara', en: 'How are you, Shirin?', ckb: 'تو چەوا یی، شیرین؟' },
    { characterId: 'shirin', en: 'I am good, thank you.', ckb: 'ئەز باش مە، سوپاس.' },
    { characterId: 'shirin', en: 'Where are you from?', ckb: 'تو ژ کو یی؟' },
    { characterId: 'dara', en: 'I am from Duhok.', ckb: 'ئەز ژ دهوکێ مە.' },
    { characterId: 'shirin', en: 'What is this?', ckb: 'ئەڤ چیە؟' },
    { characterId: 'dara', en: 'It is a book.', ckb: 'ئەڤ پەرتووکەکە.' },
    { characterId: 'shirin', en: 'Who is he?', ckb: 'ئەو کێیە؟' },
    { characterId: 'dara', en: 'He is Azad, my friend.', ckb: 'ئەو ئازادە، هەڤالێ منە.' },
  ],
};
