import type { Level } from '../../types/content';

export const level16: Level = {
  id: 16,
  titleEn: 'Weather',
  titleCkb: 'هەوا',
  icon: '🌦️',
  objectiveEn: 'Learn to talk about the weather: hot, cold, sunny and rainy.',
  objectiveCkb: 'فێر ببە ل سەر هەوایێ بپەیڤی: گەرم، سار، هەتاوی و بارانی.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l16-hot',
      en: 'Hot',
      ckb: 'گەرم',
      pos: 'adjective',
      emoji: '🔥',
      phonetic: '/hɒt/',
      exampleEn: 'It is hot today.',
      exampleCkb: 'ئەڤڕۆ هەوا یا گەرمە.',
      category: 'weather',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-cold',
      en: 'Cold',
      ckb: 'سار',
      pos: 'adjective',
      emoji: '🥶',
      phonetic: '/koʊld/',
      exampleEn: 'The water is cold.',
      exampleCkb: 'ئاڤ یا سارە.',
      category: 'weather',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-warm',
      en: 'Warm',
      ckb: 'گەرم',
      pos: 'adjective',
      emoji: '🌤️',
      phonetic: '/wɔːrm/',
      exampleEn: 'The tea is warm.',
      exampleCkb: 'چای یێ هینە.',
      category: 'weather',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-cool',
      en: 'Cool',
      ckb: 'خنک',
      pos: 'adjective',
      emoji: '🍃',
      phonetic: '/kuːl/',
      exampleEn: 'The evening is cool.',
      exampleCkb: 'ئێڤار یا هینینە.',
      category: 'weather',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-sunny',
      en: 'Sunny',
      ckb: 'هەتاوی',
      pos: 'adjective',
      emoji: '☀️',
      phonetic: '/ˈsʌni/',
      exampleEn: 'Today is sunny.',
      exampleCkb: 'ئەڤڕۆ هەوا یا هەتاوییە.',
      category: 'weather',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-rainy',
      en: 'Rainy',
      ckb: 'بارانی',
      pos: 'adjective',
      emoji: '🌦️',
      phonetic: '/ˈreɪni/',
      exampleEn: 'I like rainy days.',
      exampleCkb: 'من حەز ل ڕۆژێن بارانی دکەم.',
      category: 'weather',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-cloudy',
      en: 'Cloudy',
      ckb: 'هەوری',
      pos: 'adjective',
      emoji: '☁️',
      phonetic: '/ˈklaʊdi/',
      exampleEn: 'The sky is cloudy.',
      exampleCkb: 'ئەسمان یێ هەورییە.',
      category: 'weather',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-windy',
      en: 'Windy',
      ckb: 'بایی',
      pos: 'adjective',
      emoji: '💨',
      phonetic: '/ˈwɪndi/',
      exampleEn: 'It is windy in the park.',
      exampleCkb: 'ل پارکی هەوا یا بایییە.',
      category: 'weather',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-snow',
      en: 'Snow',
      ckb: 'بەفر',
      pos: 'noun',
      emoji: '❄️',
      phonetic: '/snoʊ/',
      exampleEn: 'Snow is white.',
      exampleCkb: 'بەفر یێ سپییە.',
      category: 'weather',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l16-rain',
      en: 'Rain',
      ckb: 'باران',
      pos: 'noun',
      emoji: '🌧️',
      phonetic: '/reɪn/',
      exampleEn: 'Rain is good for the trees.',
      exampleCkb: 'باران بۆ داران یێ باشە.',
      category: 'weather',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'It is hot.', ckb: 'هەوا یا گەرمە.' },
    { en: 'It is cold.', ckb: 'هەوا یا سارە.' },
    { en: "It's raining.", ckb: 'باران دبارێت.' },
    { en: "It's snowing.", ckb: 'بەفر دبارێت.' },
    { en: 'What is the weather like?', ckb: 'هەوا چاوایە؟' },
    { en: 'Today is sunny.', ckb: 'ئەڤڕۆ هەوا یا هەتاوییە.' },
  ],
  conversation: [
    {
      characterId: 'dara',
      en: 'What is the weather like today?',
      ckb: 'ئەڤڕۆ هەوا چاوایە؟',
    },
    {
      characterId: 'azad',
      en: 'It is hot and sunny.',
      ckb: 'هەوا یا گەرمە و هەتاوییە.',
    },
    {
      characterId: 'dara',
      en: 'Yesterday it was cold and rainy.',
      ckb: 'دوسل هەوا یا سار و بارانی بوو.',
    },
    {
      characterId: 'azad',
      en: 'Yes, it was raining all day.',
      ckb: 'بەلێ، هەمی ڕۆژێ د دبارای.',
    },
    {
      characterId: 'dara',
      en: 'Tomorrow it will be cloudy.',
      ckb: 'سێبەهی هەوا دێ هەوری بیت.',
    },
    {
      characterId: 'azad',
      en: 'I like cool weather.',
      ckb: 'من حەز ل هەوایا هینین دکەم.',
    },
  ],
};
