import type { Level } from '../../types/content';

export const level27: Level = {
  id: 27,
  titleEn: 'Everyday Routines: More Detail',
  titleCkb: 'کارێن ڕۆژانە: زێدەتر وردی',
  icon: '📆',
  objectiveEn: 'Describe your day with always, usually, sometimes and never.',
  objectiveCkb: 'بەحسا ڕۆژا خو بکە ب: هەردەم، ب گشتی، هندەک جاران و هیچ دەم.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l27-wake-up',
      en: 'wake up',
      ckb: 'هێش بوون',
      pos: 'verb',
      emoji: '⏰',
      phonetic: '/weɪk ʌp/',
      exampleEn: 'I usually wake up at seven.',
      exampleCkb: 'ئەز ب گشتی دەمژمێر حەفت هێش دبم.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-get-dressed',
      en: 'get dressed',
      ckb: 'جل ل خۆ کرن',
      pos: 'phrase',
      emoji: '👕',
      phonetic: '/ɡet drest/',
      exampleEn: 'I always get dressed before breakfast.',
      exampleCkb: 'ئەز هەردەم بەر ژارێ جلێن خو ل خۆ دکەم.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-brush-my-teeth',
      en: 'brush my teeth',
      ckb: 'ددەنێن خو پاککرن',
      pos: 'phrase',
      emoji: '🪥',
      phonetic: '/brʌʃ maɪ tiːθ/',
      exampleEn: 'I brush my teeth every morning.',
      exampleCkb: 'ئەز هەر سپێدەیێ ددەنێن خو دپاقیژکم.',
      category: 'routine',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-take-a-shower',
      en: 'take a shower',
      ckb: 'حەمامێ کرن / خۆشوون',
      pos: 'phrase',
      emoji: '🚿',
      phonetic: '/teɪk ə ˈʃaʊər/',
      exampleEn: 'I take a shower at night.',
      exampleCkb: 'ئەز شەڤی حەمامێ دکەم.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-have-breakfast',
      en: 'have breakfast',
      ckb: 'ژار خوارن',
      pos: 'phrase',
      emoji: '🍳',
      phonetic: '/hæv ˈbrekfəst/',
      exampleEn: 'I have breakfast with my family.',
      exampleCkb: 'ئەز دگەل خیزانا خو ژارێ دخوم.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-leave-home',
      en: 'leave home',
      ckb: 'ژ مال دەرکەڤن',
      pos: 'phrase',
      emoji: '🚪',
      phonetic: '/liːv həʊm/',
      exampleEn: 'I leave home at eight.',
      exampleCkb: 'ئەز دەمژمێر هەشتی ژ مال دەرکەڤم.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-arrive-at-work',
      en: 'arrive at work',
      ckb: 'گەهشتنە کار',
      pos: 'phrase',
      emoji: '🏢',
      phonetic: '/əˈraɪv æt wɜːk/',
      exampleEn: 'I arrive at work at nine.',
      exampleCkb: 'ئەز دەمژمێر نۆی دگەهشمە کار.',
      category: 'routine',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-have-lunch',
      en: 'have lunch',
      ckb: 'نانێ نیڤڕۆ خوارن',
      pos: 'phrase',
      emoji: '🥪',
      phonetic: '/hæv lʌntʃ/',
      exampleEn: 'I sometimes have lunch at work.',
      exampleCkb: 'ئەز هندەک جاران ل کار نانێ نیڤڕۆ دخوم.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-finish-work',
      en: 'finish work',
      ckb: 'کار تمامکرن',
      pos: 'phrase',
      emoji: '✅',
      phonetic: '/ˈfɪnɪʃ wɜːk/',
      exampleEn: 'I finish work at five.',
      exampleCkb: 'ئەز دەمژمێر پێنجی کارا خو تمام دکەم.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-go-home',
      en: 'go home',
      ckb: 'چوونە مال',
      pos: 'phrase',
      emoji: '🏠',
      phonetic: '/ɡəʊ həʊm/',
      exampleEn: 'I go home by taxi.',
      exampleCkb: 'ئەز ب تاکسیێ دچمە مال.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-have-dinner',
      en: 'have dinner',
      ckb: 'نانێ ئێوارێ خوارن',
      pos: 'phrase',
      emoji: '🍲',
      phonetic: '/hæv ˈdɪnər/',
      exampleEn: 'We have dinner at seven.',
      exampleCkb: 'ئەم دەمژمێر حەفتی نانێ ئێوارێ دخۆین.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l27-go-to-bed',
      en: 'go to bed',
      ckb: 'چوونە خەڤێ / ڕاکەڤن',
      pos: 'phrase',
      emoji: '🛏️',
      phonetic: '/ɡəʊ tə bed/',
      exampleEn: 'I never go to bed early.',
      exampleCkb: 'ئەز هیچ دەم ژ بەر دەمێ ڕاناکەڤم.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I usually wake up at seven.', ckb: 'ئەز ب گشتی دەمژمێر حەفت هێش دبم.' },
    { en: 'I always brush my teeth.', ckb: 'ئەز هەردەم ددەنێن خو دپاقیژکم.' },
    { en: 'I sometimes drink coffee.', ckb: 'ئەز هندەک جاران قەهوێ دڤەخوم.' },
    { en: 'I never go to bed early.', ckb: 'ئەز هیچ دەم ژ بەر دەمێ ڕاناکەڤم.' },
    { en: 'I take a shower in the morning.', ckb: 'ئەز سپێدە حەمامێ دکەم.' },
    { en: 'I finish work at five.', ckb: 'ئەز دەمژمێر پێنجی کارا خو تمام دکەم.' },
    { en: 'I go home at six.', ckb: 'ئەز دەمژمێر شەشی دچمە مال.' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'When do you usually wake up, Dara?', ckb: 'تو ب گشتی دەمژمێر چەندێ هێش دبی، دارا؟' },
    { characterId: 'dara', en: 'I usually wake up at seven. And you?', ckb: 'ئەز ب گشتی دەمژمێر حەفت هێش دبم. و تو؟' },
    { characterId: 'rojin', en: 'I always wake up at six. I take a shower and get dressed.', ckb: 'ئەز هەردەم دەمژمێر شەشی هێش دبم. خۆ دەشوم و جلێن خو ل خۆ دکەم.' },
    { characterId: 'dara', en: 'Do you have breakfast at home?', ckb: 'تو ل مال ژارێ دخوی؟' },
    { characterId: 'rojin', en: 'Yes, I always have breakfast with my family.', ckb: 'بەلێ، ئەز هەردەم دگەل خیزانا خو ژارێ دخوم.' },
    { characterId: 'dara', en: 'I sometimes drink coffee at work.', ckb: 'ئەز هندەک جاران ل کار قەهوێ دڤەخوم.' },
    { characterId: 'rojin', en: 'When do you go to bed?', ckb: 'تو دەمژمێر چەندێ ڕادکەڤی؟' },
    { characterId: 'dara', en: 'I sometimes go to bed late. I never go to bed early!', ckb: 'ئەز هندەک جاران درنگ ڕادکەڤم. ئەز هیچ دەم ژ بەر دەمێ ڕاناکەڤم!' },
  ],
};
