import type { Level } from '../../types/content';

export const level19: Level = {
  id: 19,
  titleEn: 'Basic Conversations',
  titleCkb: 'ئاخفتنێن بنچینەیی',
  icon: '💬',
  objectiveEn: 'Have simple conversations: meeting people and shopping.',
  objectiveCkb: 'ئاخفتنێن سادە بکە: ناسینا خەلکی و کڕین ل دووکانی.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l19-meet',
      en: 'meet',
      ckb: 'ھەڤدیتن',
      pos: 'verb',
      emoji: '🤝',
      phonetic: '/miːt/',
      exampleEn: 'I meet my friend.',
      exampleCkb: 'ئەز هەڤالێ خو دبینم.',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-welcome',
      en: 'welcome',
      ckb: 'ب خێر هاتن',
      pos: 'phrase',
      emoji: '👋',
      phonetic: '/ˈwelkəm/',
      exampleEn: 'Welcome to Duhok!',
      exampleCkb: 'ب خێر هاتوی بۆ دهوکێ!',
      category: 'conversation',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-help',
      en: 'help',
      ckb: 'هاریکاریکرن',
      pos: 'verb',
      emoji: '🆘',
      phonetic: '/help/',
      exampleEn: 'Can you help me?',
      exampleCkb: 'تو دشێی هاریکاریا من بکەی؟',
      category: 'conversation',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-order',
      en: 'order',
      ckb: 'داواکرن',
      pos: 'verb',
      emoji: '🧾',
      phonetic: '/ˈɔːrdər/',
      exampleEn: 'I order tea.',
      exampleCkb: 'ئەز چایەکێ داوا دکەم.',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-near',
      en: 'near',
      ckb: 'نێزیک',
      pos: 'adjective',
      emoji: '📍',
      phonetic: '/nɪər/',
      exampleEn: 'The shop is near.',
      exampleCkb: 'دووکان نێزیکە.',
      category: 'conversation',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-far',
      en: 'far',
      ckb: 'دور',
      pos: 'adjective',
      emoji: '🛣️',
      phonetic: '/fɑːr/',
      exampleEn: 'The airport is far.',
      exampleCkb: 'فرۆکەخانە دورە.',
      category: 'conversation',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-excuse-me',
      en: 'excuse me',
      ckb: 'ببورە',
      pos: 'phrase',
      emoji: '🙋',
      phonetic: '/ɪkˈskjuːz miː/',
      exampleEn: 'Excuse me, where is the bank?',
      exampleCkb: 'ببورە، بانک ل کویە؟',
      category: 'conversation',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-of-course',
      en: 'of course',
      ckb: 'بێگومان',
      pos: 'phrase',
      emoji: '✅',
      phonetic: '/əv kɔːrs/',
      exampleEn: 'Can you help me? Of course!',
      exampleCkb: 'تو دشێی هاریکاریا من بکەی؟ بێگومان!',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-nice-to-meet-you',
      en: 'Nice to meet you.',
      ckb: 'دلخۆش مە ب دیتنا تە',
      pos: 'phrase',
      emoji: '😊',
      phonetic: '/naɪs tə miːt juː/',
      exampleEn: 'Nice to meet you, Dara.',
      exampleCkb: 'دلخۆش مە ب دیتنا تە، دارا.',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-can-i-help-you',
      en: 'Can I help you?',
      ckb: 'ئەز دشێم ھاریکاریا تە بکەم؟',
      pos: 'phrase',
      emoji: '💁',
      phonetic: '/kæn aɪ help juː/',
      exampleEn: 'Can I help you? Yes, please.',
      exampleCkb: 'ئەز دشێم هاریکاریا تە بکەم؟ بەلێ، هیڤیدارین.',
      category: 'conversation',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-here-you-are',
      en: 'Here you are.',
      ckb: 'ئەڤە بۆ تە',
      pos: 'phrase',
      emoji: '🤲',
      phonetic: '/hɪər juː ɑːr/',
      exampleEn: 'Here you are. Thank you!',
      exampleCkb: 'ئەڤە بۆ تە. سوپاس!',
      category: 'conversation',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-you-are-welcome',
      en: "You're welcome.",
      ckb: 'ب دەم و چاڤێ',
      pos: 'phrase',
      emoji: '🌟',
      phonetic: '/jʊər ˈwelkəm/',
      exampleEn: 'Thank you! You are welcome.',
      exampleCkb: 'سوپاس! ب دەم و چاڤێ.',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l19-thank-you-very-much',
      en: 'Thank you very much.',
      ckb: 'زۆر سوپاس',
      pos: 'phrase',
      emoji: '🙏',
      phonetic: '/θæŋk juː ˈveri mʌtʃ/',
      exampleEn: 'Thank you very much, my friend.',
      exampleCkb: 'زۆر سوپاس، هەڤالێ من.',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Nice to meet you.', ckb: 'دلخۆش مە ب دیتنا تە.' },
    { en: 'Nice to meet you too.', ckb: 'ئەز ژی دلخۆش مە ب دیتنا تە.' },
    { en: 'Can I help you?', ckb: 'ئەز دشێم هاریکاریا تە بکەم؟' },
    { en: 'Yes, please.', ckb: 'بەلێ، هیڤیدارین.' },
    { en: 'Excuse me, where is the shop?', ckb: 'ببورە، دووکان ل کویە؟' },
    { en: 'Thank you very much.', ckb: 'زۆر سوپاس.' },
    { en: "You're welcome.", ckb: 'ب دەم و چاڤێ.' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'Hello! My name is Rojin. What is your name?', ckb: 'سلاو! ناڤێ من ڕۆژینە. ناڤێ تە چیە؟' },
    { characterId: 'azad', en: 'My name is Azad. Nice to meet you.', ckb: 'ناڤێ من ئازادە. دلخۆش مە ب دیتنا تە.' },
    { characterId: 'rojin', en: 'Nice to meet you too.', ckb: 'ئەز ژی دلخۆش مە ب دیتنا تە.' },
    { characterId: 'azad', en: 'Welcome to my shop. Can I help you?', ckb: 'ب خێر هاتوی بۆ دووکانا من. ئەز دشێم هاریکاریا تە بکەم؟' },
    { characterId: 'rojin', en: 'Yes, please. Where is the bread?', ckb: 'بەلێ، هیڤیدارین. نان ل کویە؟' },
    { characterId: 'azad', en: 'It is near the door.', ckb: 'ل نێزیکی دەرگەهێ یە.' },
    { characterId: 'rojin', en: 'How much is it?', ckb: 'ئەڤ ب چەندە؟' },
    { characterId: 'azad', en: 'It is two dollars.', ckb: 'دوو دۆلارە.' },
    { characterId: 'rojin', en: 'Here you are. Thank you!', ckb: 'ئەڤە بۆ تە. سوپاس!' },
    { characterId: 'azad', en: "You're welcome. Goodbye!", ckb: 'ب دەم و چاڤێ. ب خاتی تە!' },
  ],
};
