import type { Level } from '../../types/content';

export const level37: Level = {
  id: 37,
  titleEn: 'Health & Basic Problems',
  titleCkb: 'ساخلەمی و کێشەیێن بنچینەیی',
  icon: '🩺',
  objectiveEn: 'Explain simple health problems and ask for a doctor.',
  objectiveCkb: 'کێشەیێن ساخلەمیێ یێن سادە رابگەهینە و دکتورەکی بخوازە.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l37-head',
      en: 'head',
      ckb: 'سەر',
      pos: 'noun',
      emoji: '🗣️',
      phonetic: '/hed/',
      exampleEn: 'My head hurts.',
      exampleCkb: 'سەرێ من دئێشێت.',
      category: 'health',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-stomach',
      en: 'stomach',
      ckb: 'زک',
      pos: 'noun',
      emoji: '🍽️',
      phonetic: '/ˈstʌmək/',
      exampleEn: 'My stomach hurts.',
      exampleCkb: 'زکا من دئێشێت.',
      category: 'health',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-back',
      en: 'back',
      ckb: 'پشتی',
      pos: 'noun',
      emoji: '🧍',
      phonetic: '/bæk/',
      exampleEn: 'My back hurts.',
      exampleCkb: 'پشتیێ من دئێشێت.',
      category: 'health',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-hand',
      en: 'hand',
      ckb: 'دەست',
      pos: 'noun',
      emoji: '✋',
      phonetic: '/hænd/',
      exampleEn: 'My hand hurts.',
      exampleCkb: 'دەستێ من دئێشێت.',
      category: 'health',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-foot',
      en: 'foot',
      ckb: 'لنگ',
      pos: 'noun',
      emoji: '🦶',
      phonetic: '/fʊt/',
      exampleEn: 'My foot hurts.',
      exampleCkb: 'لنگا من دئێشێت.',
      category: 'health',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-pain',
      en: 'pain',
      ckb: 'ئێش',
      pos: 'noun',
      emoji: '🤕',
      phonetic: '/peɪn/',
      exampleEn: 'I have a pain in my back.',
      exampleCkb: 'ئێشەک ل پشتیێ من هەیە.',
      category: 'health',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-sick',
      en: 'sick',
      ckb: 'نەخۆش',
      pos: 'adjective',
      emoji: '🤒',
      phonetic: '/sɪk/',
      exampleEn: 'I am sick today.',
      exampleCkb: 'ئەڤڕۆ ئەز نەخۆش مە.',
      category: 'health',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-tired',
      en: 'tired',
      ckb: 'ماندوو',
      pos: 'adjective',
      emoji: '😴',
      phonetic: '/ˈtaɪərd/',
      exampleEn: 'I am very tired.',
      exampleCkb: 'ئەز زۆر ماندوو مە.',
      category: 'health',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-cold',
      en: 'cold',
      ckb: 'سەرما',
      pos: 'noun',
      emoji: '🤧',
      phonetic: '/koʊld/',
      exampleEn: 'I have a cold.',
      exampleCkb: 'ئەز ب سەرما مە.',
      category: 'health',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-fever',
      en: 'fever',
      ckb: 'تاب',
      pos: 'noun',
      emoji: '🌡️',
      phonetic: '/ˈfiːvər/',
      exampleEn: 'I have a fever.',
      exampleCkb: 'تابا من هەیە.',
      category: 'health',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-doctor',
      en: 'doctor',
      ckb: 'دکتور',
      pos: 'noun',
      emoji: '👨‍⚕️',
      phonetic: '/ˈdɑːktər/',
      exampleEn: 'I need a doctor.',
      exampleCkb: 'پێدڤیا من ب دکتورەکی هەیە.',
      category: 'health',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-hospital',
      en: 'hospital',
      ckb: 'نەخۆشخانە',
      pos: 'noun',
      emoji: '🏥',
      phonetic: '/ˈhɑːspɪtl/',
      exampleEn: 'Where is the hospital?',
      exampleCkb: 'نەخۆشخانە ل کویە؟',
      category: 'health',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l37-medicine',
      en: 'medicine',
      ckb: 'دەرمان',
      pos: 'noun',
      emoji: '💊',
      phonetic: '/ˈmedɪsn/',
      exampleEn: 'Take this medicine.',
      exampleCkb: 'ڤی دەرمانی وەربگرە.',
      category: 'health',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: "I don't feel well.", ckb: 'ئەز خوود باش حەس ناکەم.' },
    { en: 'My head hurts.', ckb: 'سەرێ من دئێشێت.' },
    { en: 'My stomach hurts.', ckb: 'زکا من دئێشێت.' },
    { en: 'I am tired.', ckb: 'ئەز ماندوو مە.' },
    { en: 'I have a fever.', ckb: 'تابا من هەیە.' },
    { en: 'I need a doctor.', ckb: 'پێدڤیا من ب دکتورەکی هەیە.' },
    { en: 'Where is the hospital?', ckb: 'نەخۆشخانە ل کویە؟' },
  ],
  conversation: [
    { characterId: 'azad', en: 'Good morning. What is the problem?', ckb: 'بەیانی تە باش. کێشە چیە؟' },
    { characterId: 'rojin', en: "I don't feel well. My head hurts.", ckb: 'ئەز خوود باش حەس ناکەم. سەرێ من دئێشێت.' },
    { characterId: 'azad', en: 'Do you have a fever?', ckb: 'تابا تە هەیە؟' },
    { characterId: 'rojin', en: 'Yes, and my stomach hurts too.', ckb: 'بەلێ، و زکا من ژی دئێشێت.' },
    { characterId: 'azad', en: 'Are you tired?', ckb: 'تو یی ماندوو؟' },
    { characterId: 'rojin', en: 'Yes, very tired. I need medicine.', ckb: 'بەلێ، زۆر ماندوو مە. پێدڤیا من ب دەرمانی هەیە.' },
    { characterId: 'azad', en: 'Take this medicine in the morning and at night.', ckb: 'ڤی دەرمانی ل بەیانی و ل ئێڤارێ وەربگرە.' },
    { characterId: 'rojin', en: 'Thank you very much, doctor.', ckb: 'زۆر سوپاس، دکتور.' },
    { characterId: 'azad', en: "You're welcome. Drink water and rest.", ckb: 'ب دەم و چاڤێ. ئاڤێ ڤەبخوە و بێهنڤەدانێ بکە.' },
    { characterId: 'rojin', en: 'Goodbye!', ckb: 'ب خاتی تە!' },
  ],
};
