import type { Level } from '../../types/content';

export const level07: Level = {
  id: 7,
  titleEn: 'Home',
  titleCkb: 'مال',
  icon: '🏠',
  objectiveEn: 'Name the rooms and furniture in your home.',
  objectiveCkb: 'ناڤێن ژوور و تشتێن مالێ فێر ببە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l7-house',
      en: 'House',
      ckb: 'مال',
      pos: 'noun',
      emoji: '🏠',
      phonetic: '/haʊs/',
      exampleEn: 'This is my house.',
      exampleCkb: 'ئەڤە مالا منە.',
      category: 'home',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-room',
      en: 'Room',
      ckb: 'ژوور',
      pos: 'noun',
      emoji: '🛋️',
      phonetic: '/ruːm/',
      exampleEn: 'This is my room.',
      exampleCkb: 'ئەڤە ژوورا منە.',
      category: 'home',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-kitchen',
      en: 'Kitchen',
      ckb: 'مەتبەخ',
      pos: 'noun',
      emoji: '🍳',
      phonetic: '/ˈkɪtʃɪn/',
      exampleEn: 'The kitchen is big.',
      exampleCkb: 'مەتبەخ مەزنە.',
      category: 'home',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-bedroom',
      en: 'Bedroom',
      ckb: 'ژوورا نڤستنێ',
      pos: 'noun',
      emoji: '🛌',
      phonetic: '/ˈbedruːm/',
      exampleEn: 'This is my bedroom.',
      exampleCkb: 'ئەڤە ژوورا نڤستنێ یا منە.',
      category: 'home',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-bathroom',
      en: 'Bathroom',
      ckb: 'حەمام',
      pos: 'noun',
      emoji: '🛁',
      phonetic: '/ˈbæθruːm/',
      exampleEn: 'The bathroom is small.',
      exampleCkb: 'حەمام بچووکە.',
      category: 'home',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-door',
      en: 'Door',
      ckb: 'دەرگا',
      pos: 'noun',
      emoji: '🚪',
      phonetic: '/dɔːr/',
      exampleEn: 'The door is open.',
      exampleCkb: 'دەرگا ڤەکرییە.',
      category: 'home',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-window',
      en: 'Window',
      ckb: 'پەنجەرە',
      pos: 'noun',
      emoji: '🪟',
      phonetic: '/ˈwɪndoʊ/',
      exampleEn: 'The window is big.',
      exampleCkb: 'پەنجەرە مەزنە.',
      category: 'home',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-table',
      en: 'Table',
      ckb: 'مێز',
      pos: 'noun',
      emoji: '🍽️',
      phonetic: '/ˈteɪbəl/',
      exampleEn: 'This is a table.',
      exampleCkb: 'ئەڤە مێزەکە.',
      category: 'furniture',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-chair',
      en: 'Chair',
      ckb: 'کورسی',
      pos: 'noun',
      emoji: '🪑',
      phonetic: '/tʃer/',
      exampleEn: 'This is a chair.',
      exampleCkb: 'ئەڤە کورسییەکە.',
      category: 'furniture',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-bed',
      en: 'Bed',
      ckb: 'جێگا',
      pos: 'noun',
      emoji: '🛏️',
      phonetic: '/bed/',
      exampleEn: 'The bed is big.',
      exampleCkb: 'جێگا مەزنە.',
      category: 'furniture',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l7-tv',
      en: 'TV',
      ckb: 'تەلەفزیۆن',
      pos: 'noun',
      emoji: '📺',
      phonetic: '/ˌtiːˈviː/',
      exampleEn: 'This is a TV.',
      exampleCkb: 'ئەڤە تەلەفزیۆنەکە.',
      category: 'furniture',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'This is my house.', ckb: 'ئەڤە مالا منە.' },
    { en: 'That is my room.', ckb: 'ئەوە ژوورا منە.' },
    { en: 'This is a chair.', ckb: 'ئەڤە کورسییەکە.' },
    { en: 'This is a table.', ckb: 'ئەڤە مێزەکە.' },
    { en: 'The door is open.', ckb: 'دەرگا ڤەکرییە.' },
  ],
  conversation: [
    {
      characterId: 'azad',
      en: 'Welcome! This is my house.',
      ckb: 'ب خێر هاتوی! ئەڤە مالا منە.',
    },
    { characterId: 'shirin', en: 'It is big!', ckb: 'ئەو مەزنە!' },
    { characterId: 'azad', en: 'This is the kitchen.', ckb: 'ئەڤە مەتبەخە.' },
    {
      characterId: 'azad',
      en: 'And this is my bedroom.',
      ckb: 'و ئەڤە ژوورا نڤستنێ یا منە.',
    },
    { characterId: 'shirin', en: 'The window is big.', ckb: 'پەنجەرە مەزنە.' },
    {
      characterId: 'azad',
      en: 'This is a table and this is a chair.',
      ckb: 'ئەڤە مێزەکە و ئەڤە کورسییەکە.',
    },
    { characterId: 'shirin', en: 'The door is open.', ckb: 'دەرگا ڤەکرییە.' },
  ],
};
