import type { Level } from '../../types/content';

export const level25: Level = {
  id: 25,
  titleEn: 'Describing People',
  titleCkb: 'وەسفکرنا کەسان',
  icon: '🧑',
  objectiveEn: "Describe people's appearance: height, age, hair, eyes and clothes.",
  objectiveCkb: 'فێر ببە چەوا کەسان وەسف بکەی: درێژ یان کورت، گەنج یان پیر، پڕچ، چاڤ و جلوبەرگ.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l25-tall',
      en: 'tall',
      ckb: 'درێژ',
      pos: 'adjective',
      emoji: '🦒',
      phonetic: '/tɔːl/',
      exampleEn: 'My brother is tall.',
      exampleCkb: 'برایێ من درێژە.',
      category: 'appearance',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-short',
      en: 'short',
      ckb: 'کورت',
      pos: 'adjective',
      emoji: '📏',
      phonetic: '/ʃɔːt/',
      exampleEn: 'He is short.',
      exampleCkb: 'ئەو کورتە.',
      category: 'appearance',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-young',
      en: 'young',
      ckb: 'گەنج',
      pos: 'adjective',
      emoji: '🧒',
      phonetic: '/jʌŋ/',
      exampleEn: 'My sister is young.',
      exampleCkb: 'خوشکا من گەنجە.',
      category: 'appearance',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-old',
      en: 'old',
      ckb: 'پیر',
      pos: 'adjective',
      emoji: '👴',
      phonetic: '/əʊld/',
      exampleEn: 'My grandfather is old.',
      exampleCkb: 'باپیرێ من پیرە.',
      category: 'appearance',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-beautiful',
      en: 'beautiful',
      ckb: 'جوان',
      pos: 'adjective',
      emoji: '🌸',
      phonetic: '/ˈbjuːtɪfl/',
      exampleEn: 'She is beautiful.',
      exampleCkb: 'کچەکە گەلەک جوانە.',
      category: 'appearance',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-handsome',
      en: 'handsome',
      ckb: 'جوان',
      pos: 'adjective',
      emoji: '😎',
      phonetic: '/ˈhænsəm/',
      exampleEn: 'He is handsome.',
      exampleCkb: 'کوڕەکە گەلەک جوانە.',
      category: 'appearance',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-long',
      en: 'long',
      ckb: 'درێژ',
      pos: 'adjective',
      emoji: '📐',
      phonetic: '/lɒŋ/',
      exampleEn: 'She has long hair.',
      exampleCkb: 'پڕچا وێ درێژە.',
      category: 'appearance',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-hair',
      en: 'hair',
      ckb: 'پڕچ',
      pos: 'noun',
      emoji: '💇',
      phonetic: '/heə(r)/',
      exampleEn: 'Her hair is black.',
      exampleCkb: 'پڕچا وێ ڕەشە.',
      category: 'body',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-eyes',
      en: 'eyes',
      ckb: 'چاڤ',
      pos: 'noun',
      emoji: '👀',
      phonetic: '/aɪz/',
      exampleEn: 'She has blue eyes.',
      exampleCkb: 'چاڤێن وێ شین نە.',
      category: 'body',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-face',
      en: 'face',
      ckb: 'دەموچاڤ',
      pos: 'noun',
      emoji: '🙂',
      phonetic: '/feɪs/',
      exampleEn: 'Her face is beautiful.',
      exampleCkb: 'دەموچاڤێ وێ جوانە.',
      category: 'body',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-beard',
      en: 'beard',
      ckb: 'ڕێش',
      pos: 'noun',
      emoji: '🧔',
      phonetic: '/bɪəd/',
      exampleEn: 'He has a beard.',
      exampleCkb: 'ڕێشێ وی هەیە.',
      category: 'body',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-glasses',
      en: 'glasses',
      ckb: 'بەرگێرن',
      pos: 'noun',
      emoji: '👓',
      phonetic: '/ˈɡlɑːsɪz/',
      exampleEn: 'He is wearing glasses.',
      exampleCkb: 'بەرگێرن ل چاڤێن وی نە.',
      category: 'accessories',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-shirt',
      en: 'shirt',
      ckb: 'کراس',
      pos: 'noun',
      emoji: '👕',
      phonetic: '/ʃɜːt/',
      exampleEn: 'He is wearing a black shirt.',
      exampleCkb: 'کراسەکا ڕەش ل بەری یە.',
      category: 'clothes',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l25-shoes',
      en: 'shoes',
      ckb: 'پێلاڤ',
      pos: 'noun',
      emoji: '👟',
      phonetic: '/ʃuːz/',
      exampleEn: 'Her shoes are red.',
      exampleCkb: 'پێلاڤێن وێ سۆر نە.',
      category: 'clothes',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'He is tall.', ckb: 'ئەو درێژە.' },
    { en: 'She is beautiful.', ckb: 'ئەو جوانە. — «ئەو» بۆ مێ و نێر ژی هاتینە بکارئینان.' },
    { en: 'He has a beard.', ckb: 'ڕێشێ وی هەیە.' },
    { en: 'She has long hair.', ckb: 'پڕچا وێ درێژە. — وێ = بۆ ئافرەتان، وی = بۆ مێران.' },
    { en: 'She has blue eyes.', ckb: 'چاڤێن وێ شین نە.' },
    { en: 'He is wearing a black shirt.', ckb: 'کراسەکا ڕەش ل بەری یە.' },
    { en: 'Is he young or old?', ckb: 'ئەو گەنجە یان پیرە؟' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Azad, do you know my brother?', ckb: 'ئازاد، تو برایێ من دزانی؟' },
    { characterId: 'azad', en: 'No. What does he look like?', ckb: 'نەخێر. چ شێوەیێ وی یە؟' },
    { characterId: 'shirin', en: 'He is tall and young.', ckb: 'ئەو درێژە و گەنجە.' },
    { characterId: 'azad', en: 'Does he have long hair?', ckb: 'پڕچا وی درێژە؟' },
    { characterId: 'shirin', en: 'No, his hair is short and black.', ckb: 'نەخێر، پڕچا وی کورتە و ڕەشە.' },
    { characterId: 'azad', en: 'Does he have a beard?', ckb: 'ڕێشێ وی هەیە؟' },
    { characterId: 'shirin', en: 'Yes, and he has blue eyes.', ckb: 'بەلێ، و چاڤێن وی شین نە.' },
    { characterId: 'azad', en: 'Oh, I know him! He is wearing a white shirt today.', ckb: 'ئاه، ئەز وی دزانم! ئەڤڕۆ کراسەکا سپی ل بەری یە.' },
  ],
};
