import type { Level } from '../../types/content';

export const level05: Level = {
  id: 5,
  titleEn: 'Family',
  titleCkb: 'خێزان',
  icon: '👨‍👩‍👧',
  objectiveEn: 'Talk about your family and introduce family members.',
  objectiveCkb: 'بەسەر خێزانا خو دا بئاخڤە و ئەندامێن خێزانێ ناس بکە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l5-mother',
      en: 'Mother',
      ckb: 'دايك',
      pos: 'noun',
      emoji: '👩',
      phonetic: '/ˈmʌðər/',
      exampleEn: 'This is my mother.',
      exampleCkb: 'ئەڤە دايكا منە.',
      category: 'family',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-father',
      en: 'Father',
      ckb: 'باڤ',
      pos: 'noun',
      emoji: '👨',
      phonetic: '/ˈfɑːðər/',
      exampleEn: 'This is my father.',
      exampleCkb: 'ئەڤە باڤێ منە.',
      category: 'family',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-brother',
      en: 'Brother',
      ckb: 'برا',
      pos: 'noun',
      emoji: '🧍‍♂️',
      phonetic: '/ˈbrʌðər/',
      exampleEn: 'He is my brother.',
      exampleCkb: 'ئەو برایێ منە.',
      category: 'family',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-sister',
      en: 'Sister',
      ckb: 'خوشک',
      pos: 'noun',
      emoji: '🧍‍♀️',
      phonetic: '/ˈsɪstər/',
      exampleEn: 'She is my sister.',
      exampleCkb: 'ئەو خوشکا منە.',
      category: 'family',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-son',
      en: 'Son',
      ckb: 'کور',
      pos: 'noun',
      emoji: '👦',
      phonetic: '/sʌn/',
      exampleEn: 'He is my son.',
      exampleCkb: 'ئەو کورێ منە.',
      category: 'family',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-daughter',
      en: 'Daughter',
      ckb: 'کێچ',
      pos: 'noun',
      emoji: '👧',
      phonetic: '/ˈdɔːtər/',
      exampleEn: 'She is my daughter.',
      exampleCkb: 'ئەو کێچا منە.',
      category: 'family',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-family',
      en: 'Family',
      ckb: 'خێزان',
      pos: 'noun',
      emoji: '👨‍👩‍👧',
      phonetic: '/ˈfæməli/',
      exampleEn: 'This is my family.',
      exampleCkb: 'ئەڤە خێزانا منە.',
      category: 'family',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-child',
      en: 'Child',
      ckb: 'زارۆ',
      pos: 'noun',
      emoji: '🧒',
      phonetic: '/tʃaɪld/',
      exampleEn: 'This is my child.',
      exampleCkb: 'ئەڤە زارۆکێ منە.',
      category: 'family',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-baby',
      en: 'Baby',
      ckb: 'گیانوێ',
      pos: 'noun',
      emoji: '👶',
      phonetic: '/ˈbeɪbi/',
      exampleEn: 'This is my baby.',
      exampleCkb: 'ئەڤە گیانوێ منە.',
      category: 'family',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-grandmother',
      en: 'Grandmother',
      ckb: 'دابیرە',
      pos: 'noun',
      emoji: '👵',
      phonetic: '/ˈɡrænˌmʌðər/',
      exampleEn: 'She is my grandmother.',
      exampleCkb: 'ئەو دابیرا منە.',
      category: 'family',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l5-grandfather',
      en: 'Grandfather',
      ckb: 'باپیر',
      pos: 'noun',
      emoji: '👴',
      phonetic: '/ˈɡrænˌfɑːðər/',
      exampleEn: 'He is my grandfather.',
      exampleCkb: 'ئەو بابیرێ منە.',
      category: 'family',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'This is my mother.', ckb: 'ئەڤە دايكا منە.' },
    { en: 'He is my father.', ckb: 'ئەو باڤێ منە.' },
    { en: 'She is my sister.', ckb: 'ئەو خوشکا منە.' },
    { en: 'He is my brother.', ckb: 'ئەو برایێ منە.' },
    { en: 'This is my family.', ckb: 'ئەڤە خێزانا منە.' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'Hello, Dara!', ckb: 'سلاو دارا!' },
    {
      characterId: 'dara',
      en: 'Hello, Rojin! This is my family.',
      ckb: 'سلاو ڕۆژین! ئەڤە خێزانا منە.',
    },
    { characterId: 'dara', en: 'This is my father.', ckb: 'ئەڤە باڤێ منە.' },
    { characterId: 'dara', en: 'This is my mother.', ckb: 'ئەڤە دايكا منە.' },
    {
      characterId: 'rojin',
      en: 'This is my brother Azad.',
      ckb: 'ئەڤە برایێ من ئازادە.',
    },
    {
      characterId: 'rojin',
      en: 'And this is my sister Shirin.',
      ckb: 'و ئەڤە خوشکا من شیرینە.',
    },
    { characterId: 'shirin', en: 'Hello!', ckb: 'سلاو!' },
  ],
};
