import type { Level } from '../../types/content';

export const level22: Level = {
  id: 22,
  titleEn: 'Can You?',
  titleCkb: 'تو دشێی؟',
  icon: '💪',
  objectiveEn: 'Talk about abilities and make simple requests with "can".',
  objectiveCkb: 'فێر ببە چەوا ب «can» بڵێ چ دشێی و چ ناشێی بکەی، و ژ کەسان داخوازیێ بکەی.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l22-can',
      en: 'can',
      ckb: 'شێتن',
      pos: 'verb',
      emoji: '💪',
      phonetic: '/kæn/',
      exampleEn: 'I can swim.',
      exampleCkb: 'ئەز دشێم مەلەڤانیێ بکەم.',
      category: 'ability',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-swim',
      en: 'swim',
      ckb: 'مەلەڤانی کرن',
      pos: 'verb',
      emoji: '🏊',
      phonetic: '/swɪm/',
      exampleEn: 'I can swim.',
      exampleCkb: 'ئەز دشێم مەلەڤانیێ بکەم.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-run',
      en: 'run',
      ckb: 'بەزین',
      pos: 'verb',
      emoji: '🏃',
      phonetic: '/rʌn/',
      exampleEn: 'I can run fast.',
      exampleCkb: 'ئەز دشێم ب خێرایی بڕەڤوم.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-drive',
      en: 'drive',
      ckb: 'ترومبێل خەراندن',
      pos: 'verb',
      emoji: '🚗',
      phonetic: '/draɪv/',
      exampleEn: "I can't drive.",
      exampleCkb: 'ئەز ناشێم ترومبێلێ بخوم.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-speak',
      en: 'speak',
      ckb: 'ئاخفتن',
      pos: 'verb',
      emoji: '🗣️',
      phonetic: '/spiːk/',
      exampleEn: 'I can speak English.',
      exampleCkb: 'ئەز دشێم ب ئینگلیزی ئاخڤم.',
      category: 'communication',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-read',
      en: 'read',
      ckb: 'خویندن',
      pos: 'verb',
      emoji: '📖',
      phonetic: '/riːd/',
      exampleEn: 'I can read a book.',
      exampleCkb: 'ئەز دشێم پەرتووکێ بخوینم.',
      category: 'communication',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-write',
      en: 'write',
      ckb: 'نڤیسین',
      pos: 'verb',
      emoji: '✍️',
      phonetic: '/raɪt/',
      exampleEn: 'I can write my name.',
      exampleCkb: 'ئەز دشێم ناڤێ خو بینیڤیسم.',
      category: 'communication',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-cook',
      en: 'cook',
      ckb: 'خواردن چێکرن',
      pos: 'verb',
      emoji: '🍳',
      phonetic: '/kʊk/',
      exampleEn: 'My mother can cook.',
      exampleCkb: 'دایکا من دشێت خواردنێ چێبکەت.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-help',
      en: 'help',
      ckb: 'ھاریکاریکرن',
      pos: 'verb',
      emoji: '🤝',
      phonetic: '/help/',
      exampleEn: 'Can you help me?',
      exampleCkb: 'تو دشێی ئارامیا من بکەی؟',
      category: 'requests',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-open',
      en: 'open',
      ckb: 'ڤەکرن',
      pos: 'verb',
      emoji: '🚪',
      phonetic: '/ˈəʊpən/',
      exampleEn: 'Can you open the door?',
      exampleCkb: 'تو دشێی دەرگەهێ ڤەبکەی؟',
      category: 'requests',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-close',
      en: 'close',
      ckb: 'گرتن',
      pos: 'verb',
      emoji: '🔒',
      phonetic: '/kləʊz/',
      exampleEn: 'Please close the window.',
      exampleCkb: 'هیڤیدارم، پەنجەرێ بگرە.',
      category: 'requests',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-use',
      en: 'use',
      ckb: 'بکارئینان',
      pos: 'verb',
      emoji: '🛠️',
      phonetic: '/juːz/',
      exampleEn: 'Can you use a computer?',
      exampleCkb: 'تو دشێی کۆمپیوتەری بکاربینیی؟',
      category: 'ability',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l22-understand',
      en: 'understand',
      ckb: 'تێگەیشتن',
      pos: 'verb',
      emoji: '💡',
      phonetic: '/ˌʌndəˈstænd/',
      exampleEn: "I don't understand.",
      exampleCkb: 'ئەز تێنەگەیشتم.',
      category: 'communication',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I can swim.', ckb: 'ئەز دشێم مەلەڤانیێ بکەم.' },
    { en: "I can't drive.", ckb: 'ئەز ناشێم ترومبێلێ بخوم.' },
    { en: 'I can speak English.', ckb: 'ئەز دشێم ب ئینگلیزی ئاخڤم.' },
    { en: 'Can you help me?', ckb: 'تو دشێی ئارامیا من بکەی؟' },
    { en: 'Can you open the door?', ckb: 'تو دشێی دەرگەهێ ڤەبکەی؟' },
    { en: 'Yes, I can.', ckb: 'بەلێ، ئەز دشێم.' },
    { en: "No, I can't.", ckb: 'نەخێر، ئەز ناشێم.' },
  ],
  conversation: [
    { characterId: 'azad', en: 'Rojin, can you help me?', ckb: 'ڕۆژین، تو دشێی ئارامیا من بکەی؟' },
    { characterId: 'rojin', en: 'Yes, I can. What is it?', ckb: 'بەلێ، دشێم. چیە؟' },
    { characterId: 'azad', en: 'Can you open the door, please?', ckb: 'تو دشێی دەرگەهێ ڤەبکەی، هیڤیدارم؟' },
    { characterId: 'rojin', en: 'Sure. Can you close the window?', ckb: 'ب سەر چاڤان. تو دشێی پەنجەرێ بگری؟' },
    { characterId: 'azad', en: 'Yes, I can.', ckb: 'بەلێ، ئەز دشێم.' },
    { characterId: 'rojin', en: 'Thank you! Can you cook?', ckb: 'سوپاس! تو چێکرنا خواردنی دزانی؟' },
    { characterId: 'azad', en: "No, I can't cook. But I can drive!", ckb: 'نەخێر، ئەز چێکرنا خواردنی نازانم. بەلکو ئەز دشێم ترومبێلێ بخوم!' },
    { characterId: 'rojin', en: 'Haha, great!', ckb: 'هەهە، زۆر باش!' },
  ],
};
