import type { Level } from '../../types/content';

export const level38: Level = {
  id: 38,
  titleEn: 'Comparing Things',
  titleCkb: 'بەراوردکرنا تشتان',
  icon: '⚖️',
  objectiveEn: 'Compare things: bigger, smaller, cheaper, more expensive.',
  objectiveCkb: 'تشتان بەراورد بکە: مەزنتر، بچویکتر، هەرزانتر، گرانتر.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l38-cheap',
      en: 'cheap',
      ckb: 'هەرزان',
      pos: 'adjective',
      emoji: '🏷️',
      phonetic: '/tʃiːp/',
      exampleEn: 'This shirt is cheap.',
      exampleCkb: 'ئەڤ کراسە هەرزانە.',
      category: 'comparing',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-expensive',
      en: 'expensive',
      ckb: 'گران',
      pos: 'adjective',
      emoji: '💎',
      phonetic: '/ɪkˈspensɪv/',
      exampleEn: 'The hotel is expensive.',
      exampleCkb: 'ئۆتێل گرانە.',
      category: 'comparing',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-fast',
      en: 'fast',
      ckb: 'خێرا',
      pos: 'adjective',
      emoji: '🏎️',
      phonetic: '/fæst/',
      exampleEn: 'The blue car is fast.',
      exampleCkb: 'ترۆمبێلا شین خێرا یە.',
      category: 'comparing',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-slow',
      en: 'slow',
      ckb: 'ھێدی',
      pos: 'adjective',
      emoji: '🐢',
      phonetic: '/sloʊ/',
      exampleEn: 'The taxi is slow today.',
      exampleCkb: 'تاکسی ئەڤڕۆ حەوا یە.',
      category: 'comparing',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-easy',
      en: 'easy',
      ckb: 'ئاسان',
      pos: 'adjective',
      emoji: '👌',
      phonetic: '/ˈiːzi/',
      exampleEn: 'English is easy.',
      exampleCkb: 'ئینگلیزی ئاسانە.',
      category: 'comparing',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-difficult',
      en: 'difficult',
      ckb: 'ئەستەم',
      pos: 'adjective',
      emoji: '🧩',
      phonetic: '/ˈdɪfɪkəlt/',
      exampleEn: 'This book is difficult.',
      exampleCkb: 'ئەڤ پەرتووکە ئەستەمە.',
      category: 'comparing',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-better',
      en: 'better',
      ckb: 'باشتر',
      pos: 'adjective',
      emoji: '👍',
      phonetic: '/ˈbetər/',
      exampleEn: 'This coffee is better.',
      exampleCkb: 'ئەڤ قەهوە باشترە.',
      category: 'comparing',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-bigger',
      en: 'bigger',
      ckb: 'مەزنتر',
      pos: 'adjective',
      emoji: '🐘',
      phonetic: '/ˈbɪɡər/',
      exampleEn: 'My house is bigger.',
      exampleCkb: 'مالا من مەزنترە.',
      category: 'comparing',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-smaller',
      en: 'smaller',
      ckb: 'بچویکتر',
      pos: 'adjective',
      emoji: '🐜',
      phonetic: '/ˈsmɔːlər/',
      exampleEn: 'This phone is smaller.',
      exampleCkb: 'ئەڤ تەلەفۆنە بچویکترە.',
      category: 'comparing',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-cheaper',
      en: 'cheaper',
      ckb: 'هەرزانتر',
      pos: 'adjective',
      emoji: '💰',
      phonetic: '/ˈtʃiːpər/',
      exampleEn: 'That one is cheaper.',
      exampleCkb: 'ئەو هەرزانترە.',
      category: 'comparing',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-more-expensive',
      en: 'more expensive',
      ckb: 'گرانتر',
      pos: 'phrase',
      emoji: '💸',
      phonetic: '/mɔːr ɪkˈspensɪv/',
      exampleEn: 'This hotel is more expensive.',
      exampleCkb: 'ئەڤ ئۆتێلە گرانترە.',
      category: 'comparing',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l38-faster',
      en: 'faster',
      ckb: 'خێراتر',
      pos: 'adjective',
      emoji: '⚡',
      phonetic: '/ˈfæstər/',
      exampleEn: 'The blue car is faster.',
      exampleCkb: 'ترۆمبێلا شین خێراترە.',
      category: 'comparing',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'This is bigger.', ckb: 'ئەڤە مەزنترە.' },
    { en: 'That is cheaper.', ckb: 'ئەو هەرزانترە.' },
    { en: 'The blue car is faster.', ckb: 'ترۆمبێلا شین خێراترە.' },
    { en: 'This hotel is more expensive.', ckb: 'ئەڤ ئۆتێلە گرانترە.' },
    { en: 'This phone is better.', ckb: 'ئەڤ تەلەفۆنە باشترە.' },
    { en: 'English is easier than Arabic.', ckb: 'ئینگلیزی ژ عەرەبی ئاسانترە.' },
  ],
  conversation: [
    { characterId: 'dara', en: 'Hello, I want to buy a new phone.', ckb: 'سلاو، ئەز دڤێم تەلەفۆنەکا نوو بکڕم.' },
    { characterId: 'azad', en: 'We have two good phones. This one is small and cheap.', ckb: 'دوو تەلەفۆنێن باشێن مە هەنە. ئەڤە بچویک و هەرزانە.' },
    { characterId: 'dara', en: 'How much is it?', ckb: 'ئەڤ ب چەندە؟' },
    { characterId: 'azad', en: 'It is two hundred dollars.', ckb: 'دووسەد دۆلارە.' },
    { characterId: 'dara', en: 'And that one?', ckb: 'و ئەو چەندە؟' },
    { characterId: 'azad', en: 'That one is three hundred dollars. It is more expensive, but it is faster.', ckb: 'ئەو سێسەد دۆلارە. گرانترە، بەلێ خێراترە ژی.' },
    { characterId: 'dara', en: 'Which one is better?', ckb: 'کام باشترە؟' },
    { characterId: 'azad', en: 'The big one is better for work. The small one is better for you.', ckb: 'ئەلا مەزن بۆ کارێ باشترە. ئەلا بچویک بۆ تە باشترە.' },
    { characterId: 'dara', en: 'I think the cheaper one is fine for me.', ckb: 'ئەز دبیرم ئەلا هەرزانتر بۆ من باشە.' },
    { characterId: 'azad', en: 'Good choice! Here you are.', ckb: 'هەڵبژاردنەکا باش! ئەڤە بۆ تە.' },
  ],
};
