import type { Level } from '../../types/content';

export const level15: Level = {
  id: 15,
  titleEn: 'Clothes',
  titleCkb: 'جلوبەرگ',
  icon: '👕',
  objectiveEn: 'Learn clothes words and describe them with colors and possessives.',
  objectiveCkb: 'ناڤێن جلوبەرگان فێر ببە و ب رەنگان و پەیڤێن خویانیێ وەسفا وان بکە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l15-shirt',
      en: 'Shirt',
      ckb: 'کراس',
      pos: 'noun',
      emoji: '👕',
      phonetic: '/ʃɜːrt/',
      exampleEn: 'My shirt is white.',
      exampleCkb: 'کراسا من یا سپییە.',
      category: 'clothes',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-pants',
      en: 'Pants',
      ckb: 'پانتۆل',
      pos: 'noun',
      emoji: '👖',
      phonetic: '/pænts/',
      exampleEn: 'My pants are new.',
      exampleCkb: 'پانتۆلا من یا نوییە.',
      category: 'clothes',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-shoes',
      en: 'Shoes',
      ckb: 'سۆلمە',
      pos: 'noun',
      emoji: '👟',
      phonetic: '/ʃuːz/',
      exampleEn: 'My shoes are black.',
      exampleCkb: 'سۆلمەیێن من یێن ڕەشن.',
      category: 'clothes',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-socks',
      en: 'Socks',
      ckb: 'جوراب',
      pos: 'noun',
      emoji: '🧦',
      phonetic: '/sɒks/',
      exampleEn: 'I wash my socks.',
      exampleCkb: 'ئەز جورابێن خو دشوم.',
      category: 'clothes',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-jacket',
      en: 'Jacket',
      ckb: 'چاکەت',
      pos: 'noun',
      emoji: '🧥',
      phonetic: '/ˈdʒækɪt/',
      exampleEn: 'His jacket is warm.',
      exampleCkb: 'چاکەتێ وی یێ گەرمە.',
      category: 'clothes',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-hat',
      en: 'Hat',
      ckb: 'کەلو',
      pos: 'noun',
      emoji: '🎩',
      phonetic: '/hæt/',
      exampleEn: 'She has a red hat.',
      exampleCkb: 'وێ کەلوەکا سور هەیە.',
      category: 'clothes',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-dress',
      en: 'Dress',
      ckb: 'فستان',
      pos: 'noun',
      emoji: '👗',
      phonetic: '/drɛs/',
      exampleEn: 'Her dress is beautiful.',
      exampleCkb: 'فستانا ڤێ یا جوانە.',
      category: 'clothes',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-bag',
      en: 'Bag',
      ckb: 'چەنتە',
      pos: 'noun',
      emoji: '👜',
      phonetic: '/bæɡ/',
      exampleEn: 'My bag is heavy.',
      exampleCkb: 'چەنتەیا من یا گرانە.',
      category: 'clothes',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-gloves',
      en: 'Gloves',
      ckb: 'دەستکێش',
      pos: 'noun',
      emoji: '🧤',
      phonetic: '/ɡlʌvz/',
      exampleEn: 'My gloves are warm.',
      exampleCkb: 'دەستکێشێن من یێن گەرم نە.',
      category: 'clothes',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l15-watch',
      en: 'Watch',
      ckb: 'دەمساعەت',
      pos: 'noun',
      emoji: '⌚',
      phonetic: '/wɒtʃ/',
      exampleEn: 'This watch is new.',
      exampleCkb: 'ڤێ دەمساعەت یا نوییە.',
      category: 'clothes',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'My shirt is blue.', ckb: 'کراسا من یا شینە.' },
    { en: 'Your shoes are black.', ckb: 'سۆلمەیێن تە یێن ڕەشن.' },
    { en: 'His jacket is new.', ckb: 'چاکەتێ وی یێ نوییە.' },
    { en: 'Her dress is beautiful.', ckb: 'فستانا ڤێ یا جوانە.' },
    { en: 'A red shirt.', ckb: 'کراسەکا سور.' },
    { en: 'Black shoes.', ckb: 'سۆلمەیێن ڕەش.' },
  ],
  conversation: [
    {
      characterId: 'rojin',
      en: 'Your dress is beautiful, Shirin!',
      ckb: 'فستانا تە یا جوانە، شیرین!',
    },
    {
      characterId: 'shirin',
      en: 'Thank you! My shirt is blue.',
      ckb: 'سپاس! کراسا من یا شینە.',
    },
    {
      characterId: 'rojin',
      en: 'I have a red shirt.',
      ckb: 'من کراسەکا سور هەیە.',
    },
    {
      characterId: 'shirin',
      en: 'And black shoes?',
      ckb: 'و سۆلمەیێن ڕەش؟',
    },
    {
      characterId: 'rojin',
      en: 'Yes, and a new bag.',
      ckb: 'بەلێ، و چەنتەیەکا نوی.',
    },
    {
      characterId: 'shirin',
      en: 'Very nice!',
      ckb: 'زۆر جوانە!',
    },
  ],
};
