import type { Level } from '../../types/content';

export const level34: Level = {
  id: 34,
  titleEn: 'Travel & Airport English',
  titleCkb: 'گەشت و ئینگلیزیا فڕۆکەخانێ',
  icon: '✈️',
  objectiveEn: 'Use English at the airport: check-in, security, and finding your gate.',
  objectiveCkb: 'ل فڕۆکەخانێ ئینگلیزی بکاربینە: چێک ئین، ئاسایش و دیتنا گەیتا خو.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l34-airport',
      en: 'airport',
      ckb: 'فڕۆکەخانە',
      pos: 'noun',
      emoji: '🛫',
      phonetic: '/ˈɛrpɔːrt/',
      exampleEn: 'Where is the airport?',
      exampleCkb: 'فڕۆکەخانە ل کوویە؟',
      category: 'travel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-flight',
      en: 'flight',
      ckb: 'گەشت',
      pos: 'noun',
      emoji: '🛩️',
      phonetic: '/flaɪt/',
      exampleEn: 'What time is the flight?',
      exampleCkb: 'گەشت ل دەمژمێر چەندێیە؟',
      category: 'travel',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-ticket',
      en: 'ticket',
      ckb: 'بلیت',
      pos: 'noun',
      emoji: '🎫',
      phonetic: '/ˈtɪkɪt/',
      exampleEn: 'Here is my ticket.',
      exampleCkb: 'بگرە، بلیتا من.',
      category: 'travel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-passport',
      en: 'passport',
      ckb: 'پاسپۆرت',
      pos: 'noun',
      emoji: '🛂',
      phonetic: '/ˈpæspɔːrt/',
      exampleEn: 'Here is my passport.',
      exampleCkb: 'بگرە، پاسپۆرتا من.',
      category: 'travel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-boarding-pass',
      en: 'boarding pass',
      ckb: 'کارتا سواربوونێ',
      pos: 'noun',
      emoji: '🎟️',
      phonetic: '/ˈbɔːrdɪŋ pæs/',
      exampleEn: 'Here is your boarding pass.',
      exampleCkb: 'بگرە، کارتا سواربوونا تە.',
      category: 'travel',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-gate',
      en: 'gate',
      ckb: 'گەیت',
      pos: 'noun',
      emoji: '🚪',
      phonetic: '/ɡeɪt/',
      exampleEn: 'Where is Gate 5?',
      exampleCkb: 'گەیتا پێنجێ ل کوویە؟',
      category: 'travel',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-security',
      en: 'security',
      ckb: 'ئاسایش',
      pos: 'noun',
      emoji: '🔍',
      phonetic: '/sɪˈkjʊrɪti/',
      exampleEn: 'Where is security?',
      exampleCkb: 'ئاسایش ل کوویە؟',
      category: 'travel',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-baggage',
      en: 'baggage',
      ckb: 'جانتاو بار',
      pos: 'noun',
      emoji: '🧳',
      phonetic: '/ˈbæɡɪdʒ/',
      exampleEn: 'Where is baggage claim?',
      exampleCkb: 'جهێ وەرگرتنا جانتاو باری ل کوویە؟',
      category: 'travel',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-suitcase',
      en: 'suitcase',
      ckb: 'جانتا',
      pos: 'noun',
      emoji: '💼',
      phonetic: '/ˈsuːtkeɪs/',
      exampleEn: 'My suitcase is heavy.',
      exampleCkb: 'جانتایا من یا گرانە.',
      category: 'travel',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-departure',
      en: 'departure',
      ckb: 'ڕۆیشتن',
      pos: 'noun',
      emoji: '🛫',
      phonetic: '/dɪˈpɑːrtʃər/',
      exampleEn: 'The departure is at nine o’clock.',
      exampleCkb: 'ڕۆیشتن ل دەمژمێر نۆیێیە.',
      category: 'travel',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-arrival',
      en: 'arrival',
      ckb: 'گەهیشتن',
      pos: 'noun',
      emoji: '🛬',
      phonetic: '/əˈraɪvəl/',
      exampleEn: 'The arrival is at five o’clock.',
      exampleCkb: 'گەهیشتن ل دەمژمێر پێنجێیە.',
      category: 'travel',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l34-plane',
      en: 'plane',
      ckb: 'فڕۆکە',
      pos: 'noun',
      emoji: '✈️',
      phonetic: '/pleɪn/',
      exampleEn: 'The plane is big.',
      exampleCkb: 'فڕۆکە یا مەزنە.',
      category: 'travel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Where is passport control?', ckb: 'کۆنترۆلا پاسپۆرتێ ل کوویە؟' },
    { en: 'Here is my passport.', ckb: 'بگرە، پاسپۆرتا من.' },
    { en: 'Where is Gate 5?', ckb: 'گەیتا پێنجێ ل کوویە؟' },
    { en: 'Where is baggage claim?', ckb: 'جهێ وەرگرتنا جانتاو باری ل کوویە؟' },
    { en: 'What time is the flight?', ckb: 'گەشت ل دەمژمێر چەندێیە؟' },
    { en: 'Where is check-in?', ckb: 'چێک ئین ل کوویە؟' },
    { en: 'My suitcase is heavy.', ckb: 'جانتایا من یا گرانە.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Hello. Your passport and ticket, please.', ckb: 'سلاو. هیڤیدارم، پاسپۆرت و بلیتا تە.' },
    { characterId: 'dara', en: 'Here is my passport and my ticket.', ckb: 'بگرە، پاسپۆرتا من و بلیتا من.' },
    { characterId: 'shirin', en: 'Thank you. Do you have a suitcase?', ckb: 'سپاس. جانتایا تە هەیە؟' },
    { characterId: 'dara', en: 'Yes, one suitcase.', ckb: 'بەلێ، جانتایەک.' },
    { characterId: 'shirin', en: 'OK. Here is your boarding pass. Your flight is at nine o’clock.', ckb: 'باشە. بگرە کارتا سواربوونا تە. گەشتا تە ل دەمژمێر نۆیێیە.' },
    { characterId: 'dara', en: 'Where is security?', ckb: 'ئاسایش ل کوویە؟' },
    { characterId: 'shirin', en: 'Go straight, then turn left.', ckb: 'ڕاستی بچە، پاشی بزڤرە چەپێ.' },
    { characterId: 'dara', en: 'And where is Gate 5?', ckb: 'و گەیتا پێنجێ ل کوویە؟' },
    { characterId: 'shirin', en: 'It is after security, next to the café.', ckb: 'ل پاش ئاسایشێیە، ل تەنیشت کافێیێ.' },
    { characterId: 'dara', en: 'Thank you very much!', ckb: 'زۆر سپاس!' },
  ],
};
