import type { Level } from '../../types/content';

export const level35: Level = {
  id: 35,
  titleEn: 'Hotel English',
  titleCkb: 'ئینگلیزیا ئۆتێلێ',
  icon: '🏨',
  objectiveEn: 'Check into a hotel and ask about your room, breakfast and check-out.',
  objectiveCkb: 'ل ئۆتێلێ تومارێ بکە و بپرسە ژوورا تە، تاشتی و چێک ئاوت.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l35-hotel',
      en: 'hotel',
      ckb: 'ئۆتێل',
      pos: 'noun',
      emoji: '🏨',
      phonetic: '/hoʊˈtɛl/',
      exampleEn: 'The hotel is next to the bank.',
      exampleCkb: 'ئۆتێل ل تەنیشت بانکێیە.',
      category: 'hotel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-room',
      en: 'room',
      ckb: 'ژوور',
      pos: 'noun',
      emoji: '🛏️',
      phonetic: '/ruːm/',
      exampleEn: 'I need a room.',
      exampleCkb: 'پێدڤییا من ب ژوورەکێ هەیە.',
      category: 'hotel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-reservation',
      en: 'reservation',
      ckb: 'حەجز',
      pos: 'noun',
      emoji: '📅',
      phonetic: '/ˌrɛzərˈveɪʃən/',
      exampleEn: 'I have a reservation.',
      exampleCkb: 'من حیجزەک هەیە.',
      category: 'hotel',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-reception',
      en: 'reception',
      ckb: 'پێشوازی',
      pos: 'noun',
      emoji: '🛎️',
      phonetic: '/rɪˈsɛpʃən/',
      exampleEn: 'The reception is over there.',
      exampleCkb: 'پێشوازی ل هەرێیە.',
      category: 'hotel',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-key',
      en: 'key',
      ckb: 'کلیل',
      pos: 'noun',
      emoji: '🔑',
      phonetic: '/kiː/',
      exampleEn: 'Can I have another key?',
      exampleCkb: 'دشێم کلیلەکا دی وەربگرم؟',
      category: 'hotel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-passport',
      en: 'passport',
      ckb: 'پاسپۆرت',
      pos: 'noun',
      emoji: '🛂',
      phonetic: '/ˈpæspɔːrt/',
      exampleEn: 'Your passport, please?',
      exampleCkb: 'هیڤیدارم، پاسپۆرتا تە؟',
      category: 'hotel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-single-room',
      en: 'single room',
      ckb: 'ژوورا ئێک کەسی',
      pos: 'noun',
      emoji: '🛌',
      phonetic: '/ˈsɪŋɡəl ruːm/',
      exampleEn: 'I want a single room, please.',
      exampleCkb: 'هیڤیدارم، ئەز ژوورا ئێک کەسی دڤێم.',
      category: 'hotel',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-double-room',
      en: 'double room',
      ckb: 'ژوورا دوو کەسان',
      pos: 'noun',
      emoji: '🛏️',
      phonetic: '/ˈdʌbəl ruːm/',
      exampleEn: 'A double room for two nights.',
      exampleCkb: 'ژوورا دوو کەسان بۆ دوو شەڤان.',
      category: 'hotel',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-breakfast',
      en: 'breakfast',
      ckb: 'تاشتی',
      pos: 'noun',
      emoji: '🍳',
      phonetic: '/ˈbrɛkfəst/',
      exampleEn: 'What time is breakfast?',
      exampleCkb: 'تاشتی ل دەمژمێر چەندێیە؟',
      category: 'hotel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-check-in',
      en: 'check-in',
      ckb: 'چێک ئین',
      pos: 'noun',
      emoji: '📥',
      phonetic: '/ˈtʃɛk ɪn/',
      exampleEn: 'Check-in is at two o’clock.',
      exampleCkb: 'چێک ئین ل دەمژمێر دووێیە.',
      category: 'hotel',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-check-out',
      en: 'check-out',
      ckb: 'چێک ئاوت',
      pos: 'noun',
      emoji: '📤',
      phonetic: '/ˈtʃɛk aʊt/',
      exampleEn: 'What time is check-out?',
      exampleCkb: 'چێک ئاوت ل دەمژمێر چەندێیە؟',
      category: 'hotel',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l35-night',
      en: 'night',
      ckb: 'شەڤ',
      pos: 'noun',
      emoji: '🌙',
      phonetic: '/naɪt/',
      exampleEn: 'I stay for two nights.',
      exampleCkb: 'ئەز بۆ دوو شەڤان دمینم.',
      category: 'hotel',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I have a reservation.', ckb: 'من حیجزەک هەیە.' },
    { en: 'I need a room.', ckb: 'پێدڤییا من ب ژوورەکێ هەیە.' },
    { en: 'What time is breakfast?', ckb: 'تاشتی ل دەمژمێر چەندێیە؟' },
    { en: 'Where is my room?', ckb: 'ژوورا من ل کوویە؟' },
    { en: 'Can I have another key?', ckb: 'دشێم کلیلەکا دی وەربگرم؟' },
    { en: 'What time is check-out?', ckb: 'چێک ئاوت ل دەمژمێر چەندێیە؟' },
    { en: 'A double room for two nights.', ckb: 'ژوورا دوو کەسان بۆ دوو شەڤان.' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'Hello! Welcome to our hotel.', ckb: 'سلاو! ب خێر هاتوی بۆ ئۆتێلا مە.' },
    { characterId: 'azad', en: 'Hello. I have a reservation for two nights.', ckb: 'سلاو. من حیجزەک هەیە بۆ دوو شەڤان.' },
    { characterId: 'rojin', en: 'What is your name, please?', ckb: 'هیڤیدارم، ناڤێ تە چیە؟' },
    { characterId: 'azad', en: 'Azad. I need a double room.', ckb: 'ئازاد. پێدڤییا من ب ژوورا دوو کەسان هەیە.' },
    { characterId: 'rojin', en: 'Yes, I see it. Your passport, please?', ckb: 'بەلێ، من دیت. هیڤیدارم، پاسپۆرتا تە؟' },
    { characterId: 'azad', en: 'Here you are.', ckb: 'بگرە.' },
    { characterId: 'rojin', en: 'Here is your key. Your room is number twelve.', ckb: 'بگرە کلیلا تە. ژوورا تە یا ژمارە دوانزدەیە.' },
    { characterId: 'azad', en: 'What time is breakfast?', ckb: 'تاشتی ل دەمژمێر چەندێیە؟' },
    { characterId: 'rojin', en: 'From seven to ten o’clock. Check-out is at twelve.', ckb: 'ژ دەمژمێر حەفتێ هەتا دەهیێ. چێک ئاوت ل دەمژمێر دوانزدەیێیە.' },
    { characterId: 'azad', en: 'Thank you very much!', ckb: 'زۆر سپاس!' },
  ],
};
