import type { Level } from '../../types/content';

export const level24: Level = {
  id: 24,
  titleEn: 'Where Is It?',
  titleCkb: 'ل کرێ یە؟',
  icon: '📍',
  objectiveEn: 'Ask and answer where things are using prepositions of place.',
  objectiveCkb: 'فێر ببە چەوا بپرسی تشت ل کرێ نە و بەرسڤێ بدەی: ل سەر، ژێر، ل نێزک، ل پشت...',
  cefr: 'A1',
  vocab: [
    {
      id: 'l24-in',
      en: 'in',
      ckb: 'د ... دا',
      pos: 'other',
      emoji: '📥',
      phonetic: '/ɪn/',
      exampleEn: 'The book is in the bag.',
      exampleCkb: 'پەرتووک د چانتایێ دا یە.',
      category: 'prepositions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-on',
      en: 'on',
      ckb: 'ل سەر',
      pos: 'other',
      emoji: '🔝',
      phonetic: '/ɒn/',
      exampleEn: 'The phone is on the table.',
      exampleCkb: 'تەلەفۆن ل سەر مێزێ یە.',
      category: 'prepositions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-under',
      en: 'under',
      ckb: 'ژێر',
      pos: 'other',
      emoji: '⬇️',
      phonetic: '/ˈʌndə(r)/',
      exampleEn: 'The shoes are under the bed.',
      exampleCkb: 'پێلاڤ ژێر تەختی نە.',
      category: 'prepositions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-next-to',
      en: 'next to',
      ckb: 'ل رەخ',
      pos: 'other',
      emoji: '↔️',
      phonetic: '/ˈnekst tə/',
      exampleEn: 'The shop is next to the bank.',
      exampleCkb: 'دوکان ل نێزک بانکی یە.',
      category: 'prepositions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-behind',
      en: 'behind',
      ckb: 'ل پشت',
      pos: 'other',
      emoji: '🔙',
      phonetic: '/bɪˈhaɪnd/',
      exampleEn: 'The car is behind the house.',
      exampleCkb: 'ترومبێل ل پشت مالێ یە.',
      category: 'prepositions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-in-front-of',
      en: 'in front of',
      ckb: 'ل بەردەم',
      pos: 'other',
      emoji: '➡️',
      phonetic: '/ɪn frʌnt əv/',
      exampleEn: 'The car is in front of the house.',
      exampleCkb: 'ترومبێل ل بەردەم مالێ یە.',
      category: 'prepositions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-between',
      en: 'between',
      ckb: 'د ناڤبەرا ... دا',
      pos: 'other',
      emoji: '🔀',
      phonetic: '/bɪˈtwiːn/',
      exampleEn: 'The bank is between the shop and the hospital.',
      exampleCkb: 'بانک د ناڤبرا دوکانێ و نەخۆشخانەیێ دا یە.',
      category: 'prepositions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-near',
      en: 'near',
      ckb: 'نێزک',
      pos: 'other',
      emoji: '📍',
      phonetic: '/nɪə(r)/',
      exampleEn: 'The shop is near my house.',
      exampleCkb: 'دوکان نێزک مالا من یە.',
      category: 'prepositions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-far',
      en: 'far',
      ckb: 'دور',
      pos: 'other',
      emoji: '🛣️',
      phonetic: '/fɑː(r)/',
      exampleEn: 'The airport is far.',
      exampleCkb: 'فڕۆکەخانە دۆرە.',
      category: 'prepositions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-inside',
      en: 'inside',
      ckb: 'ژ ناڤە',
      pos: 'other',
      emoji: '📦',
      phonetic: '/ˌɪnˈsaɪd/',
      exampleEn: 'The dog is inside the house.',
      exampleCkb: 'سەگ د مالێ دا یە.',
      category: 'prepositions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l24-outside',
      en: 'outside',
      ckb: 'ل دەرڤە',
      pos: 'other',
      emoji: '🌳',
      phonetic: '/ˌaʊtˈsaɪd/',
      exampleEn: 'The car is outside the house.',
      exampleCkb: 'ترومبێل ل دەرڤەیا مالێ یە.',
      category: 'prepositions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Where is the phone?', ckb: 'تەلەفۆن ل کرێ یە؟' },
    { en: 'The phone is on the table.', ckb: 'تەلەفۆن ل سەر مێزێ یە.' },
    { en: 'The shoes are under the bed.', ckb: 'پێلاڤ ژێر تەختی نە.' },
    { en: 'The car is in front of the house.', ckb: 'ترومبێل ل بەردەم مالێ یە.' },
    { en: 'The shop is next to the bank.', ckb: 'دوکان ل نێزک بانکی یە.' },
    { en: 'Where are my keys?', ckb: 'کلییلێن من ل کرێ نە؟' },
    { en: 'Is it near here?', ckb: 'ئەڤە نێزک ڤێرێ یە؟' },
    { en: "No, it's far.", ckb: 'نەخێر، دۆرە.' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'Dara, where is my phone?', ckb: 'دارا، تەلەفۆنا من ل کرێ یە؟' },
    { characterId: 'dara', en: 'Is it on the table?', ckb: 'ل سەر مێزێ یە؟' },
    { characterId: 'rojin', en: "No, it isn't there.", ckb: 'نەخێر، ل ویر نینە.' },
    { characterId: 'dara', en: 'Look! It is under the chair.', ckb: 'ببینە! ژێر کورسیێ یە.' },
    { characterId: 'rojin', en: 'Thank you! And where are my keys?', ckb: 'سوپاس! کلییلێن من ل کرێ نە؟' },
    { characterId: 'dara', en: 'They are in your bag.', ckb: 'د چانتایێ تە دا نە.' },
    { characterId: 'rojin', en: 'No! They are next to the door.', ckb: 'نەخێر! ل نێزک دەرگەهێ نە.' },
    { characterId: 'dara', en: 'Great, now you have everything!', ckb: 'زۆر باش، نوکە هەمی تشت ل دەست تە نە!' },
  ],
};
