import type { Level } from '../../types/content';

export const level33: Level = {
  id: 33,
  titleEn: 'Asking for Directions',
  titleCkb: 'پرسکرنا ڕێیێ',
  icon: '🧭',
  objectiveEn: 'Ask for and give directions in a city.',
  objectiveCkb: 'ل باجێری ڕێیێ بپرسە و ڕێیێ نیشان بدە.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l33-left',
      en: 'left',
      ckb: 'چەپ',
      pos: 'other',
      emoji: '⬅️',
      phonetic: '/lɛft/',
      exampleEn: 'Turn left.',
      exampleCkb: 'بزڤرە چەپێ.',
      category: 'directions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-right',
      en: 'right',
      ckb: 'ڕاست',
      pos: 'other',
      emoji: '➡️',
      phonetic: '/raɪt/',
      exampleEn: 'Turn right.',
      exampleCkb: 'بزڤرە ڕاستێ.',
      category: 'directions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-straight',
      en: 'straight',
      ckb: 'ڕاستی',
      pos: 'other',
      emoji: '⬆️',
      phonetic: '/streɪt/',
      exampleEn: 'Go straight.',
      exampleCkb: 'ڕاستی بچە.',
      category: 'directions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-turn',
      en: 'turn',
      ckb: 'زڤرین (ئەز دزڤرم)',
      pos: 'verb',
      emoji: '🔄',
      phonetic: '/tɜːrn/',
      exampleEn: 'Turn left at the corner.',
      exampleCkb: 'ل گۆشەیێ بزڤرە چەپێ.',
      category: 'directions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-street',
      en: 'street',
      ckb: 'جادە',
      pos: 'noun',
      emoji: '🛣️',
      phonetic: '/striːt/',
      exampleEn: 'Go straight on this street.',
      exampleCkb: 'ژ ڤێ جادەیێ ڕاستی بچە.',
      category: 'directions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-corner',
      en: 'corner',
      ckb: 'گۆشە',
      pos: 'noun',
      emoji: '📐',
      phonetic: '/ˈkɔːrnər/',
      exampleEn: 'The shop is at the corner.',
      exampleCkb: 'دکان ل گۆشەیێیە.',
      category: 'directions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-traffic-light',
      en: 'traffic light',
      ckb: 'چرایا ترفیکێ',
      pos: 'noun',
      emoji: '🚦',
      phonetic: '/ˈtræfɪk laɪt/',
      exampleEn: 'Turn right at the traffic light.',
      exampleCkb: 'ل چرایا ترفیکێ بزڤرە ڕاستێ.',
      category: 'directions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-near',
      en: 'near',
      ckb: 'نێزک',
      pos: 'adjective',
      emoji: '📍',
      phonetic: '/nɪr/',
      exampleEn: 'Is the bank near here?',
      exampleCkb: 'بانک نێزکێ ڤێرێیە؟',
      category: 'directions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-far',
      en: 'far',
      ckb: 'دوور',
      pos: 'adjective',
      emoji: '🔭',
      phonetic: '/fɑːr/',
      exampleEn: 'The airport is far.',
      exampleCkb: 'فڕۆکەخانە یا دوورە.',
      category: 'directions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-next-to',
      en: 'next to',
      ckb: 'ل تەنیشت',
      pos: 'phrase',
      emoji: '👫',
      phonetic: '/ˈnɛkst tuː/',
      exampleEn: "It's next to the hotel.",
      exampleCkb: 'ل تەنیشت ئۆتێلێیە.',
      category: 'directions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-opposite',
      en: 'opposite',
      ckb: 'بەرامبەر',
      pos: 'adjective',
      emoji: '↔️',
      phonetic: '/ˈɒpəzɪt/',
      exampleEn: "It's opposite the bank.",
      exampleCkb: 'بەرامبەر بانکێیە.',
      category: 'directions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l33-behind',
      en: 'behind',
      ckb: 'ل پاش',
      pos: 'other',
      emoji: '🔙',
      phonetic: '/bɪˈhaɪnd/',
      exampleEn: 'The restaurant is behind the hotel.',
      exampleCkb: 'ڕێستۆرانت ل پاش ئۆتێلێیە.',
      category: 'directions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Where is the bank?', ckb: 'بانک ل کوویە؟' },
    { en: 'How do I get to the airport?', ckb: 'ئەز چەوا دچم فڕۆکەخانێ؟' },
    { en: 'How do I get to the hospital?', ckb: 'ئەز چەوا دچم نەخۆشخانێ؟' },
    { en: 'Turn left.', ckb: 'بزڤرە چەپێ.' },
    { en: 'Turn right.', ckb: 'بزڤرە ڕاستێ.' },
    { en: 'Go straight.', ckb: 'ڕاستی بچە.' },
    { en: "It's next to the hotel.", ckb: 'ل تەنیشت ئۆتێلێیە.' },
    { en: "It's opposite the bank.", ckb: 'بەرامبەر بانکێیە.' },
  ],
  conversation: [
    { characterId: 'azad', en: 'Excuse me! Where is the hospital?', ckb: 'ببورە! نەخۆشخانە ل کوویە؟' },
    { characterId: 'shirin', en: 'It is a little far. Go straight on this street.', ckb: 'هندەک یا دوورە. ژ ڤێ جادەیێ ڕاستی بچە.' },
    { characterId: 'azad', en: 'OK. And then?', ckb: 'باشە. و پاشی چ؟' },
    { characterId: 'shirin', en: 'Turn left at the traffic light.', ckb: 'ل چرایا ترفیکێ بزڤرە چەپێ.' },
    { characterId: 'azad', en: 'Left at the traffic light. OK.', ckb: 'ل چرایا ترفیکێ چەپێ. باشە.' },
    { characterId: 'shirin', en: 'Then turn right at the corner.', ckb: 'پاشی ل گۆشەیێ بزڤرە ڕاستێ.' },
    { characterId: 'azad', en: 'Is the hospital near the corner?', ckb: 'نەخۆشخانە نێزکێ گۆشەیێیە؟' },
    { characterId: 'shirin', en: 'Yes. It is next to the bank, opposite the hotel.', ckb: 'بەلێ. ل تەنیشت بانکێیە، بەرامبەر ئۆتێلێ.' },
    { characterId: 'azad', en: 'Thank you very much!', ckb: 'زۆر سپاس!' },
    { characterId: 'shirin', en: 'You are welcome. Good luck!', ckb: 'شایانی نینە. خویێ لگەڵ!' },
  ],
};
