import type { Level } from '../../types/content';

export const level13: Level = {
  id: 13,
  titleEn: 'Places',
  titleCkb: 'جهێن باژێری',
  icon: '🏙️',
  objectiveEn: 'Learn the names of places in town and ask where they are.',
  objectiveCkb: 'ناڤێن جهێن باژێری فێر ببە و بپرسە جه ل کوو نە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l13-home',
      en: 'Home',
      ckb: 'ماڵ',
      pos: 'noun',
      emoji: '🏠',
      phonetic: '/hoʊm/',
      exampleEn: 'I go home at five o’clock.',
      exampleCkb: 'ئەز ل دەمژمێر پێنجی دچم ماڵ.',
      category: 'places',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-school',
      en: 'School',
      ckb: 'قوتابخانە',
      pos: 'noun',
      emoji: '🏫',
      phonetic: '/skuːl/',
      exampleEn: 'My brother goes to school.',
      exampleCkb: 'برایێ من دچیت قوتابخانێ.',
      category: 'places',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-work',
      en: 'Work',
      ckb: 'کار',
      pos: 'noun',
      emoji: '💼',
      phonetic: '/wɜːrk/',
      exampleEn: 'My father goes to work.',
      exampleCkb: 'بابێ من دچیت کار.',
      category: 'places',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-airport',
      en: 'Airport',
      ckb: 'فڕۆکەخانە',
      pos: 'noun',
      emoji: '🛫',
      phonetic: '/ˈɛrpɔːrt/',
      exampleEn: 'The airport is big.',
      exampleCkb: 'فڕۆکەخانە یا مەزنە.',
      category: 'places',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-shop',
      en: 'Shop',
      ckb: 'دکان',
      pos: 'noun',
      emoji: '🏪',
      phonetic: '/ʃɒp/',
      exampleEn: 'I buy bread at the shop.',
      exampleCkb: 'ئەز ژ دکانی نان دکڕم.',
      category: 'places',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-restaurant',
      en: 'Restaurant',
      ckb: 'خواردنگەه',
      pos: 'noun',
      emoji: '🍽️',
      phonetic: '/ˈrɛstrɒnt/',
      exampleEn: 'We eat dinner at the restaurant.',
      exampleCkb: 'ئەم خوارنا ئێڤی ل خواردنگەهێ دخوین.',
      category: 'places',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-hospital',
      en: 'Hospital',
      ckb: 'نەخۆشخانە',
      pos: 'noun',
      emoji: '🏥',
      phonetic: '/ˈhɒspɪtl/',
      exampleEn: 'My mother works at the hospital.',
      exampleCkb: 'دایکا من ل نەخۆشخانێ کار دکەت.',
      category: 'places',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-bank',
      en: 'Bank',
      ckb: 'بانک',
      pos: 'noun',
      emoji: '🏦',
      phonetic: '/bæŋk/',
      exampleEn: 'The bank is next to the hotel.',
      exampleCkb: 'بانک ل تەنیشت هۆتێلییە.',
      category: 'places',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-hotel',
      en: 'Hotel',
      ckb: 'هۆتێل',
      pos: 'noun',
      emoji: '🏨',
      phonetic: '/hoʊˈtɛl/',
      exampleEn: 'The hotel is in the city.',
      exampleCkb: 'هۆتێل ل باژێرییە.',
      category: 'places',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-mosque',
      en: 'Mosque',
      ckb: 'مزگەفت',
      pos: 'noun',
      emoji: '🕌',
      phonetic: '/mɒsk/',
      exampleEn: 'I go to the mosque on Friday.',
      exampleCkb: 'ئەز ئینیێ دچم مزگەفتی.',
      category: 'places',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-park',
      en: 'Park',
      ckb: 'پارک',
      pos: 'noun',
      emoji: '🌳',
      phonetic: '/pɑːrk/',
      exampleEn: 'The children play in the park.',
      exampleCkb: 'زارۆک ل پارکی یاریێ دکەن.',
      category: 'places',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l13-street',
      en: 'Street',
      ckb: 'جادە',
      pos: 'noun',
      emoji: '🛣️',
      phonetic: '/striːt/',
      exampleEn: 'Our house is on this street.',
      exampleCkb: 'ماڵا مە ل ڤێ جادەیێیە.',
      category: 'places',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I am at home.', ckb: 'ئەز ل ماڵ مە.' },
    { en: 'I am at work.', ckb: 'ئەز ل کار مە.' },
    { en: 'I go to school.', ckb: 'ئەز دچم قوتابخانێ.' },
    { en: 'I go to the airport.', ckb: 'ئەز دچم فڕۆکەخانێ.' },
    { en: 'Where is the bank?', ckb: 'بانک ل کوویە؟' },
    { en: 'Where is the mosque?', ckb: 'مزگەفت ل کوویە؟' },
  ],
  conversation: [
    {
      characterId: 'dara',
      en: 'Excuse me, where is the hospital?',
      ckb: 'ببورە، نەخۆشخانە ل کوویە؟',
    },
    {
      characterId: 'rojin',
      en: 'The hospital is on this street.',
      ckb: 'نەخۆشخانە ل ڤێ جادەیێیە.',
    },
    {
      characterId: 'dara',
      en: 'And where is the park?',
      ckb: 'و پارک ل کوویە؟',
    },
    {
      characterId: 'rojin',
      en: 'The park is next to the mosque.',
      ckb: 'پارک ل تەنیشت مزگەفتییە.',
    },
    {
      characterId: 'dara',
      en: 'Thank you very much!',
      ckb: 'زۆر سپاس!',
    },
    {
      characterId: 'rojin',
      en: 'You are welcome!',
      ckb: 'شایانی نینە!',
    },
  ],
};
