import type { Level } from '../../types/content';

export const level39: Level = {
  id: 39,
  titleEn: 'Real Conversations',
  titleCkb: 'ئاخفتنێن راستی',
  icon: '💬',
  objectiveEn: 'Have real conversations: meeting someone and going to a restaurant.',
  objectiveCkb: 'ئاخفتنێن راستی بکە: ناسینا کەسەکی و چوون بۆ چێشتخانەیێ.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l39-hungry',
      en: 'hungry',
      ckb: 'بەرسی',
      pos: 'adjective',
      emoji: '🍽️',
      phonetic: '/ˈhʌŋɡri/',
      exampleEn: "I am hungry. Let's go to a restaurant.",
      exampleCkb: 'ئەز بەرسی مە. وەرە بچین چێشتخانەیێ.',
      category: 'conversation',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-thirsty',
      en: 'thirsty',
      ckb: 'تهنی',
      pos: 'adjective',
      emoji: '🥤',
      phonetic: '/ˈθɜːrsti/',
      exampleEn: 'I am thirsty. I want water.',
      exampleCkb: 'ئەز تهنی مە. ئەز ئاڤێ دڤێم.',
      category: 'conversation',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-delicious',
      en: 'delicious',
      ckb: 'تامەز',
      pos: 'adjective',
      emoji: '😋',
      phonetic: '/dɪˈlɪʃəs/',
      exampleEn: 'The food is delicious.',
      exampleCkb: 'خوارن تامەزە.',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-recommend',
      en: 'recommend',
      ckb: 'پێشنیارکرن',
      pos: 'verb',
      emoji: '🌟',
      phonetic: '/ˌrekəˈmend/',
      exampleEn: 'What do you recommend?',
      exampleCkb: 'تو چی پێشنیار دکەی؟',
      category: 'conversation',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-together',
      en: 'together',
      ckb: 'پێکڤە',
      pos: 'other',
      emoji: '🧑‍🤝‍🧑',
      phonetic: '/təˈɡeðər/',
      exampleEn: 'We eat together.',
      exampleCkb: 'ئەم پێکڤە دخوین.',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-tonight',
      en: 'tonight',
      ckb: 'ئەڤشەڤ',
      pos: 'other',
      emoji: '🌙',
      phonetic: '/təˈnaɪt/',
      exampleEn: 'Are you free tonight?',
      exampleCkb: 'تو ئەڤشەڤ بەربەست یی؟',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-free',
      en: 'free',
      ckb: 'بەربەست',
      pos: 'adjective',
      emoji: '🆓',
      phonetic: '/friː/',
      exampleEn: 'Are you free tomorrow?',
      exampleCkb: 'تو سبەی بەربەست یی؟',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-plan',
      en: 'plan',
      ckb: 'پیلان',
      pos: 'noun',
      emoji: '🗓️',
      phonetic: '/plæn/',
      exampleEn: 'What is your plan for tonight?',
      exampleCkb: 'پیلانا تە بۆ ئەڤشەڤێ چیە؟',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-invite',
      en: 'invite',
      ckb: 'داوەتکرن',
      pos: 'verb',
      emoji: '💌',
      phonetic: '/ɪnˈvaɪt/',
      exampleEn: 'I invite my friend to dinner.',
      exampleCkb: 'ئەز هەڤالێ خو بۆ خوارنا ئێڤارێ داوەت دکەم.',
      category: 'conversation',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-usually',
      en: 'usually',
      ckb: 'ب گشتی',
      pos: 'other',
      emoji: '🔁',
      phonetic: '/ˈjuːʒuəli/',
      exampleEn: 'I usually drink coffee in the morning.',
      exampleCkb: 'ئەز ب گشتی ل بەیانیان قەهوەیێ دڤێم.',
      category: 'conversation',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-would-like',
      en: "I'd like...",
      ckb: 'دڤێم...',
      pos: 'phrase',
      emoji: '🙋',
      phonetic: '/aɪd laɪk/',
      exampleEn: "I'd like chicken and rice, please.",
      exampleCkb: 'ئەز مرشک و برنج دڤێم، هیڤیدارین.',
      category: 'conversation',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l39-sounds-good',
      en: 'Sounds good!',
      ckb: 'باشە، زۆر باشە!',
      pos: 'phrase',
      emoji: '🎶',
      phonetic: '/saʊndz ɡʊd/',
      exampleEn: "Let's go at seven. Sounds good!",
      exampleCkb: 'بچین ل دەمژمێر حەفتێ. باشە، زۆر باشە!',
      category: 'conversation',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Hi! Where are you going?', ckb: 'سلاو! تو دچی کو؟' },
    { en: "I'm going to the airport.", ckb: 'ئەز دچمە فرۆکەخانێ.' },
    { en: 'Are you free tonight?', ckb: 'تو ئەڤشەڤ بەربەست یی؟' },
    { en: 'What do you recommend?', ckb: 'تو چی پێشنیار دکەی؟' },
    { en: 'Do you want to come with me?', ckb: 'تو دڤێی ب من را بێی؟' },
    { en: 'What did you do yesterday?', ckb: 'دوهی تو چیکری؟' },
    { en: 'What are you going to do tomorrow?', ckb: 'سبەی تو دێ چیکەی؟' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'Hi, Azad! Where are you going?', ckb: 'سلاو ئازاد! تو دچی کو؟' },
    { characterId: 'azad', en: 'Hi, Rojin! I am going to the restaurant. I am hungry.', ckb: 'سلاو ڕۆژین! ئەز دچمە چێشتخانەیێ. ئەز بەرسی مە.' },
    { characterId: 'rojin', en: 'I am hungry too. Can I come with you?', ckb: 'ئەز ژی بەرسی مە. ئەز دشێم ب تە را بێم؟' },
    { characterId: 'azad', en: 'Of course! The restaurant is near the bank.', ckb: 'بێگومان! چێشتخانە ل نێزیکی بانکێ یە.' },
    { characterId: 'rojin', en: 'Great. What do you recommend there?', ckb: 'باش. ل ویرێ تو چی پێشنیار دکەی؟' },
    { characterId: 'azad', en: 'The chicken and rice is delicious.', ckb: 'مرشک و برنج زۆر تامەزە.' },
    { characterId: 'shirin', en: 'Hello! What would you like?', ckb: 'سلاو! تو چی دڤێی؟' },
    { characterId: 'azad', en: "I'd like chicken and rice, please.", ckb: 'ئەز مرشک و برنج دڤێم، هیڤیدارین.' },
    { characterId: 'rojin', en: 'Me too. And two teas, please.', ckb: 'ئەز ژی. و دوو چای ژی، هیڤیدارین.' },
    { characterId: 'shirin', en: 'Of course. Your food is coming soon.', ckb: 'بێگومان. خوارنا هێن دەمەکا نێزیک دێ.' },
  ],
};
