import type { Level } from '../../types/content';

export const level01: Level = {
  id: 1,
  titleEn: 'Hello!',
  titleCkb: 'سلاڤ!',
  icon: '👋',
  objectiveEn: 'Learn to greet people and use polite words like "please" and "thank you".',
  objectiveCkb: 'فێر ببە چەوا سلاڤ ل کەسان بکەی و پەیڤێن وەک «هیڤیدارم» و «سوپاس» بکاربینیی.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l1-hello',
      en: 'Hello',
      ckb: 'سلاڤ',
      pos: 'phrase',
      emoji: '👋',
      phonetic: '/həˈləʊ/',
      exampleEn: 'Hello, Dara!',
      exampleCkb: 'سلاڤ، دارا!',
      category: 'Greetings',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-hi',
      en: 'Hi',
      ckb: 'هێلو',
      pos: 'phrase',
      emoji: '🙋',
      phonetic: '/haɪ/',
      exampleEn: 'Hi, Rojin!',
      exampleCkb: 'هێلو، ڕۆژین!',
      category: 'Greetings',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-good-morning',
      en: 'Good morning',
      ckb: 'بەیانیا خێر',
      pos: 'phrase',
      emoji: '🌅',
      phonetic: '/ɡʊd ˈmɔːnɪŋ/',
      exampleEn: 'Good morning, Azad!',
      exampleCkb: 'بەیانیا خێر، ئازاد!',
      category: 'Greetings',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-good-afternoon',
      en: 'Good afternoon',
      ckb: 'ڕۆژباش',
      pos: 'phrase',
      emoji: '☀️',
      phonetic: '/ɡʊd ˌɑːftəˈnuːn/',
      exampleEn: 'Good afternoon, Shirin!',
      exampleCkb: 'ڕۆژباش، شیرین!',
      category: 'Greetings',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-good-evening',
      en: 'Good evening',
      ckb: 'ئێڤارباش',
      pos: 'phrase',
      emoji: '🌆',
      phonetic: '/ɡʊd ˈiːvnɪŋ/',
      exampleEn: 'Good evening, my friend!',
      exampleCkb: 'ئێڤارباش، هەڤاڵێ من!',
      category: 'Greetings',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-goodbye',
      en: 'Goodbye',
      ckb: 'ب خاترێ تە',
      pos: 'phrase',
      emoji: '🚶',
      phonetic: '/ɡʊdˈbaɪ/',
      exampleEn: 'Goodbye, Dara!',
      exampleCkb: 'ب خاترێ تە، دارا!',
      category: 'Greetings',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-bye',
      en: 'Bye',
      ckb: 'بایی',
      pos: 'phrase',
      emoji: '✌️',
      phonetic: '/baɪ/',
      exampleEn: 'Bye, Rojin!',
      exampleCkb: 'بایی، ڕۆژین!',
      category: 'Greetings',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-yes',
      en: 'Yes',
      ckb: 'بەلێ',
      pos: 'other',
      emoji: '✅',
      phonetic: '/jes/',
      exampleEn: 'Yes, please.',
      exampleCkb: 'بەلێ، هیڤیدارم.',
      category: 'Basics',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-no',
      en: 'No',
      ckb: 'نەخێر',
      pos: 'other',
      emoji: '❌',
      phonetic: '/nəʊ/',
      exampleEn: 'No, thank you.',
      exampleCkb: 'نەخێر، سوپاس.',
      category: 'Basics',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-please',
      en: 'Please',
      ckb: 'هیڤیدارم',
      pos: 'phrase',
      emoji: '🤲',
      phonetic: '/pliːz/',
      exampleEn: 'One tea, please.',
      exampleCkb: 'چایەک، هیڤیدارم.',
      category: 'Politeness',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-thank-you',
      en: 'Thank you',
      ckb: 'سوپاس',
      pos: 'phrase',
      emoji: '🙏',
      phonetic: '/ˈθæŋk juː/',
      exampleEn: 'Thank you very much!',
      exampleCkb: 'گەلەک سوپاس!',
      category: 'Politeness',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l1-sorry',
      en: 'Sorry',
      ckb: 'ببورە',
      pos: 'phrase',
      emoji: '😔',
      phonetic: '/ˈsɒri/',
      exampleEn: 'I am sorry.',
      exampleCkb: 'ببورە، ژ خەتا من بوو.',
      category: 'Politeness',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Hello.', ckb: 'سلاڤ. — دەمێ تو کەسەکی دبینی، بڵێ «Hello».' },
    { en: 'Hi.', ckb: 'هێلو. — سلاڤەکا کورت و سادەتر.' },
    { en: 'Good morning.', ckb: 'بەیانیا خێر. — ژ بەیانی هەتا نیڤڕۆ هاتییە بکارئینان.' },
    { en: 'Thank you.', ckb: 'سوپاس. — دەمێ کەسەک کاریەک بۆ تە دکەت.' },
    { en: "You're welcome.", ckb: 'هیڤیا خوشە. — بەرسڤا «Thank you».' },
    { en: 'Goodbye.', ckb: 'ب خاترێ تە. — دەمێ تو ژ کەسەکی دئێی.' },
  ],
  conversation: [
    { characterId: 'dara', en: 'Hello!', ckb: 'سلاڤ!' },
    { characterId: 'rojin', en: 'Hi, Dara!', ckb: 'هێلو، دارا!' },
    { characterId: 'dara', en: 'Good morning!', ckb: 'بەیانیا خێر!' },
    { characterId: 'rojin', en: 'Good morning!', ckb: 'بەیانیا خێر!' },
    { characterId: 'dara', en: 'Goodbye!', ckb: 'ب خاترێ تە!' },
    { characterId: 'rojin', en: 'Bye!', ckb: 'بایی!' },
  ],
};
