import type { Level } from '../../types/content';

export const level30: Level = {
  id: 30,
  titleEn: 'Talking about the Future',
  titleCkb: 'ئاخفتن ل سەر پاشەرۆژێ',
  icon: '🔮',
  objectiveEn: 'Talk about your plans with "going to".',
  objectiveCkb: 'بەحس ژ پیلانێن خو بکە ب "going to".',
  cefr: 'A2',
  vocab: [
    {
      id: 'l30-tomorrow',
      en: 'tomorrow',
      ckb: 'سبەی',
      pos: 'other',
      emoji: '🌅',
      phonetic: '/təˈmɒrəʊ/',
      exampleEn: "I'm going to work tomorrow.",
      exampleCkb: 'ئەز دێ سبەی بچمە کار.',
      category: 'time',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-tonight',
      en: 'tonight',
      ckb: 'ئەڤشەڤ',
      pos: 'other',
      emoji: '🌙',
      phonetic: '/təˈnaɪt/',
      exampleEn: "I'm going to watch a movie tonight.",
      exampleCkb: 'ئەز دێ ئەڤشەڤ فلمەک تەماشە بکەم.',
      category: 'time',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-next-week',
      en: 'next week',
      ckb: 'هەفتیا بهێت',
      pos: 'other',
      emoji: '🗓️',
      phonetic: '/nekst wiːk/',
      exampleEn: "I'm going to travel next week.",
      exampleCkb: 'ئەز دێ هەفتیا بهێت گەشتی بکەم.',
      category: 'time',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-plan',
      en: 'plan',
      ckb: 'پیلان',
      pos: 'noun',
      emoji: '📝',
      phonetic: '/plæn/',
      exampleEn: 'What is your plan for tomorrow?',
      exampleCkb: 'پیلانا تە بۆ سبەی چیە؟',
      category: 'plans',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-visit',
      en: 'visit',
      ckb: 'سەرەدانکرن',
      pos: 'verb',
      emoji: '🏡',
      phonetic: '/ˈvɪzɪt/',
      exampleEn: "I'm going to visit my family.",
      exampleCkb: 'ئەز دێ سەرەدانا خیزانا خو بکەم.',
      category: 'plans',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-travel',
      en: 'travel',
      ckb: 'گەشتکرن',
      pos: 'verb',
      emoji: '✈️',
      phonetic: '/ˈtrævəl/',
      exampleEn: "I'm going to travel to Duhok.",
      exampleCkb: 'ئەز دێ گەشتی بۆ دهۆکێ بکەم.',
      category: 'plans',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-buy',
      en: 'buy',
      ckb: 'کڕین',
      pos: 'verb',
      emoji: '🛍️',
      phonetic: '/baɪ/',
      exampleEn: "I'm going to buy a phone.",
      exampleCkb: 'ئەز دێ مۆبایلەک بکڕم.',
      category: 'plans',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-meet',
      en: 'meet',
      ckb: 'هەڤدیتن',
      pos: 'verb',
      emoji: '🤝',
      phonetic: '/miːt/',
      exampleEn: "I'm going to meet my friend.",
      exampleCkb: 'ئەز دێ هەڤالێ خو ببینم.',
      category: 'plans',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-work',
      en: 'work',
      ckb: 'کارکرن',
      pos: 'verb',
      emoji: '💼',
      phonetic: '/wɜːk/',
      exampleEn: 'Are you going to work tomorrow?',
      exampleCkb: 'تو دێ سبەی بچیە کار؟',
      category: 'plans',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-study',
      en: 'study',
      ckb: 'خواندن',
      pos: 'verb',
      emoji: '📚',
      phonetic: '/ˈstʌdi/',
      exampleEn: "I'm going to study English tonight.",
      exampleCkb: 'ئەز دێ ئەڤشەڤ ئینگلیزی بخوینم.',
      category: 'plans',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l30-go',
      en: 'go',
      ckb: 'چوون',
      pos: 'verb',
      emoji: '🚶',
      phonetic: '/ɡəʊ/',
      exampleEn: 'Where are you going to go?',
      exampleCkb: 'تو دێ بچیە کو؟',
      category: 'plans',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: "I'm going to work tomorrow.", ckb: 'ئەز دێ سبەی بچمە کار.' },
    { en: "I'm going to visit my family.", ckb: 'ئەز دێ سەرەدانا خیزانا خو بکەم.' },
    { en: "I'm going to buy a phone.", ckb: 'ئەز دێ مۆبایلەک بکڕم.' },
    { en: "I'm going to study English.", ckb: 'ئەز دێ ئینگلیزی بخوینم.' },
    { en: 'Are you going to travel?', ckb: 'تو دێ گەشتی بکەی؟' },
    { en: 'Yes, I am.', ckb: 'بەلێ.' },
    { en: "No, I'm not.", ckb: 'نەخێر.' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'What are you going to do tomorrow, Azad?', ckb: 'تو دێ سبەی چ بکەی، ئازاد؟' },
    { characterId: 'azad', en: "I'm going to work in the morning. And you?", ckb: 'ئەز دێ سپێدە بچمە کار. و تو؟' },
    { characterId: 'rojin', en: "I'm going to visit my family.", ckb: 'ئەز دێ سەرەدانا خیزانا خو بکەم.' },
    { characterId: 'azad', en: 'Are you going to travel by taxi?', ckb: 'تو دێ ب تاکسیێ گەشتی بکەی؟' },
    { characterId: 'rojin', en: 'Yes, I am. Are you going to meet Dara tonight?', ckb: 'بەلێ. تو دێ ئەڤشەڤ دارا ببینی؟' },
    { characterId: 'azad', en: 'Yes, we are going to drink coffee together.', ckb: 'بەلێ، ئەم دێ پێکڤە قەهوێ ڤەخۆین.' },
    { characterId: 'rojin', en: "Great! I'm going to watch a movie tonight.", ckb: 'باشە! ئەز دێ ئەڤشەڤ فلمەک تەماشە بکەم.' },
  ],
};
