import type { Level } from '../../types/content';

export const level26: Level = {
  id: 26,
  titleEn: 'Present Continuous',
  titleCkb: 'ئێستا یا بەردەوام',
  icon: '🎬',
  objectiveEn: 'Say what is happening right now.',
  objectiveCkb: 'بڵێ نوکە چ دچێت.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l26-eating',
      en: 'eating',
      ckb: 'خوارن (نوکە ئەز دخوم)',
      pos: 'verb',
      emoji: '🍽️',
      phonetic: '/ˈiːtɪŋ/',
      exampleEn: 'I am eating breakfast now.',
      exampleCkb: 'نوکە ئەز ژارێ دخوم.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-drinking',
      en: 'drinking',
      ckb: 'ڤەخوارن (نوکە ئەز دڤەخوم)',
      pos: 'verb',
      emoji: '🥤',
      phonetic: '/ˈdrɪŋkɪŋ/',
      exampleEn: 'She is drinking coffee.',
      exampleCkb: 'نوکە ئەو قەهوێ دڤەخۆ.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-walking',
      en: 'walking',
      ckb: 'پیاسەکرن (نوکە ئەز پیاسە دکەم)',
      pos: 'verb',
      emoji: '🚶',
      phonetic: '/ˈwɔːkɪŋ/',
      exampleEn: 'He is walking to the shop.',
      exampleCkb: 'نوکە ئەو پیاسە دکە بۆ دۆکانێ.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-running',
      en: 'running',
      ckb: 'ڕیکن (نوکە ئەز دڕیکم)',
      pos: 'verb',
      emoji: '🏃',
      phonetic: '/ˈrʌnɪŋ/',
      exampleEn: 'They are running now.',
      exampleCkb: 'نوکە ئەوان دڕیکن.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-working',
      en: 'working',
      ckb: 'کارکرن (نوکە ئەز کار دکەم)',
      pos: 'verb',
      emoji: '💼',
      phonetic: '/ˈwɜːkɪŋ/',
      exampleEn: 'We are working today.',
      exampleCkb: 'نوکە ئەم کار دکەین.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-sleeping',
      en: 'sleeping',
      ckb: 'نووستن (نوکە ئەز دنووم)',
      pos: 'verb',
      emoji: '😴',
      phonetic: '/ˈsliːpɪŋ/',
      exampleEn: 'My father is sleeping.',
      exampleCkb: 'نوکە بابێ من دنووە.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-reading',
      en: 'reading',
      ckb: 'خویندن (نوکە ئەز دخوینم)',
      pos: 'verb',
      emoji: '📖',
      phonetic: '/ˈriːdɪŋ/',
      exampleEn: 'I am reading a book.',
      exampleCkb: 'نوکە ئەز پەرتووکەکی دخوینم.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-writing',
      en: 'writing',
      ckb: 'نڤیسین (نوکە ئەز دنڤیسم)',
      pos: 'verb',
      emoji: '✍️',
      phonetic: '/ˈraɪtɪŋ/',
      exampleEn: 'She is writing her name.',
      exampleCkb: 'نوکە ئەو ناڤێ خو دنڤیسە.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-talking',
      en: 'talking',
      ckb: 'ئاخفتن (نوکە ئەز دئاخڤم)',
      pos: 'verb',
      emoji: '🗣️',
      phonetic: '/ˈtɔːkɪŋ/',
      exampleEn: 'They are talking together.',
      exampleCkb: 'نوکە ئەوان پێکڤە دئاخڤن.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-watching',
      en: 'watching',
      ckb: 'تەماشەکرن (نوکە ئەز تەماشە دکەم)',
      pos: 'verb',
      emoji: '📺',
      phonetic: '/ˈwɒtʃɪŋ/',
      exampleEn: 'We are watching a movie.',
      exampleCkb: 'نوکە ئەم فلمەکی تەماشە دکەین.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-driving',
      en: 'driving',
      ckb: 'دان (نوکە ئەز ترۆمبێلێ ددەم)',
      pos: 'verb',
      emoji: '🚗',
      phonetic: '/ˈdraɪvɪŋ/',
      exampleEn: 'He is driving a taxi.',
      exampleCkb: 'نوکە ئەو تاکسی ددە.',
      category: 'actions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l26-cooking',
      en: 'cooking',
      ckb: 'پژان (نوکە ئەز دپژم)',
      pos: 'verb',
      emoji: '🍳',
      phonetic: '/ˈkʊkɪŋ/',
      exampleEn: 'My mother is cooking chicken.',
      exampleCkb: 'نوکە دایکا من مریشکێ دپژە.',
      category: 'actions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I am eating.', ckb: 'نوکە ئەز دخوم.' },
    { en: 'He is walking.', ckb: 'نوکە ئەو پیاسە دکە.' },
    { en: 'She is drinking.', ckb: 'نوکە ئەو دڤەخۆ.' },
    { en: 'They are working.', ckb: 'نوکە ئەوان کار دکەن.' },
    { en: 'What are you doing?', ckb: 'تو چ دکەی؟' },
    { en: 'What is he doing?', ckb: 'ئەو چ دکە؟' },
    { en: 'We are watching a movie.', ckb: 'نوکە ئەم فلمەکی تەماشە دکەین.' },
  ],
  conversation: [
    { characterId: 'dara', en: 'Look, Rojin! What is Azad doing?', ckb: 'بسەحە، ڕۆژین! ئازاد چ دکە؟' },
    { characterId: 'rojin', en: 'He is running outside.', ckb: 'نوکە ئەو ل دەرڤە دڕیکی.' },
    { characterId: 'dara', en: 'And what is Shirin doing?', ckb: 'و شیرین چ دکە؟' },
    { characterId: 'rojin', en: 'She is cooking chicken for dinner.', ckb: 'نوکە ئەو بۆ نانێ ئێوارێ مریشکێ دپژە.' },
    { characterId: 'dara', en: 'My mother is drinking coffee.', ckb: 'نوکە دایکا من قەهوێ دڤەخۆ.' },
    { characterId: 'rojin', en: 'And my father is sleeping!', ckb: 'و نوکە بابێ من دنووە!' },
    { characterId: 'dara', en: 'We are all busy now!', ckb: 'نوکە ئەم هەمی مژوولین!' },
  ],
};
