import type { Level } from '../../types/content';

export const level21: Level = {
  id: 21,
  titleEn: "I Like / I Don't Like",
  titleCkb: 'حەز دکەم / حەز ناکەم',
  icon: '❤️',
  objectiveEn: "Talk about things you like and don't like, and say what you want and need.",
  objectiveCkb: 'فێر ببە چەوا بڵێ ژ چ حەز دکەی و ژ چ حەز ناکەی، و بڵێ چ دڤێی و پێدڤییا تە ب چ هەیە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l21-like',
      en: 'like',
      ckb: 'حەزکرن',
      pos: 'verb',
      emoji: '👍',
      phonetic: '/laɪk/',
      exampleEn: 'I like coffee.',
      exampleCkb: 'ئەز حەز ژ قەهوەیێ دکەم.',
      category: 'feelings',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-love',
      en: 'love',
      ckb: 'گەلەک حەزکرن',
      pos: 'verb',
      emoji: '❤️',
      phonetic: '/lʌv/',
      exampleEn: 'I love my mother.',
      exampleCkb: 'ئەز گەلەک حەز ژ دایکا خو دکەم.',
      category: 'feelings',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-want',
      en: 'want',
      ckb: 'ڤێان',
      pos: 'verb',
      emoji: '🙋',
      phonetic: '/wɒnt/',
      exampleEn: 'I want water.',
      exampleCkb: 'ئەز ئاڤێ دڤێم.',
      category: 'needs',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-need',
      en: 'need',
      ckb: 'پێدڤی بوون',
      pos: 'verb',
      emoji: '🆘',
      phonetic: '/niːd/',
      exampleEn: 'I need a taxi.',
      exampleCkb: 'پێدڤییا من ب تاکسییەکێ هەیە.',
      category: 'needs',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-prefer',
      en: 'prefer',
      ckb: 'باشتر دیتن',
      pos: 'verb',
      emoji: '⭐',
      phonetic: '/prɪˈfɜː(r)/',
      exampleEn: 'I prefer tea.',
      exampleCkb: 'ئەز چایێ باشتر دبینم.',
      category: 'feelings',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-hate',
      en: 'hate',
      ckb: 'هیڤ حەزنەکرن',
      pos: 'verb',
      emoji: '😖',
      phonetic: '/heɪt/',
      exampleEn: "I hate cold weather.",
      exampleCkb: 'ئەز هیڤ حەز ژ هەڤایا سار ناکەم.',
      category: 'feelings',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-music',
      en: 'music',
      ckb: 'مۆزیک',
      pos: 'noun',
      emoji: '🎵',
      phonetic: '/ˈmjuːzɪk/',
      exampleEn: 'I like music.',
      exampleCkb: 'ئەز حەز ژ مۆزیکێ دکەم.',
      category: 'hobbies',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-movie',
      en: 'movie',
      ckb: 'فیلم',
      pos: 'noun',
      emoji: '🎬',
      phonetic: '/ˈmuːvi/',
      exampleEn: 'I like movies.',
      exampleCkb: 'ئەز حەز ژ فیلمان دکەم.',
      category: 'hobbies',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-sport',
      en: 'sport',
      ckb: 'وەرزش',
      pos: 'noun',
      emoji: '⚽',
      phonetic: '/spɔːt/',
      exampleEn: 'I like football.',
      exampleCkb: 'ئەز حەز ژ تەپا پێ دکەم.',
      category: 'hobbies',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-game',
      en: 'game',
      ckb: 'یاری',
      pos: 'noun',
      emoji: '🎮',
      phonetic: '/ɡeɪm/',
      exampleEn: 'I like this game.',
      exampleCkb: 'ئەز حەز ژ ڤێ یاریێ دکەم.',
      category: 'hobbies',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-book',
      en: 'book',
      ckb: 'پەرتووک',
      pos: 'noun',
      emoji: '📖',
      phonetic: '/bʊk/',
      exampleEn: 'I like this book.',
      exampleCkb: 'ئەز حەز ژ ڤێ پەرتووکێ دکەم.',
      category: 'hobbies',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l21-place',
      en: 'place',
      ckb: 'جه',
      pos: 'noun',
      emoji: '📍',
      phonetic: '/pleɪs/',
      exampleEn: 'I like this place.',
      exampleCkb: 'ئەز حەز ژ ڤی جهی دکەم.',
      category: 'other',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I like coffee.', ckb: 'ئەز حەز ژ قەهوەیێ دکەم.' },
    { en: "I don't like tea.", ckb: 'ئەز حەز ژ چایێ ناکەم.' },
    { en: 'I love music.', ckb: 'ئەز گەلەک حەز ژ مۆزیکێ دکەم.' },
    { en: "I don't like cold weather.", ckb: 'ئەز حەز ژ هەڤایا سار ناکەم.' },
    { en: 'I want water.', ckb: 'ئەز ئاڤێ دڤێم.' },
    { en: 'I need a taxi.', ckb: 'پێدڤییا من ب تاکسییەکێ هەیە.' },
    { en: 'Do you like football?', ckb: 'تو ژ تەپا پێ حەز دکەی؟' },
    { en: "Yes, I do. / No, I don't.", ckb: 'بەلێ، حەز دکەم. / نەخێر، حەز ناکەم.' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'Do you like coffee, Dara?', ckb: 'تو ژ قەهوەیێ حەز دکەی، دارا؟' },
    { characterId: 'dara', en: 'Yes, I love coffee!', ckb: 'بەلێ، ئەز گەلەک حەز ژ قەهوەیێ دکەم!' },
    { characterId: 'rojin', en: 'Do you like tea?', ckb: 'تو ژ چایێ حەز دکەی؟' },
    { characterId: 'dara', en: "No, I don't like tea.", ckb: 'نەخێر، ئەز حەز ژ چایێ ناکەم.' },
    { characterId: 'rojin', en: 'I like tea. And I love music.', ckb: 'ئەز ژ چایێ حەز دکەم. و گەلەک حەز ژ مۆزیکێ ژی دکەم.' },
    { characterId: 'dara', en: 'I like music too. Do you like football?', ckb: 'ئەز ژی حەز ژ مۆزیکێ دکەم. تو ژ تەپا پێ حەز دکەی؟' },
    { characterId: 'rojin', en: "No, I don't like football. I like books.", ckb: 'نەخێر، ئەز حەز ژ تەپا پێ ناکەم. ئەز حەز ژ پەرتووکان دکەم.' },
    { characterId: 'dara', en: 'Me too!', ckb: 'ئەز ژی!' },
  ],
};
