import type { Level } from '../../types/content';

export const level14: Level = {
  id: 14,
  titleEn: 'Transport',
  titleCkb: 'ترانسپۆرت',
  icon: '🚌',
  objectiveEn: 'Learn words for transport and travel phrases like needing a taxi or a ticket.',
  objectiveCkb: 'پەیڤێن ترانسپۆرتێ فێر ببە و فێر ببە چەوان بڵێی پێدڤییا تە ب تەکسی و بلیتی هەیە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l14-car',
      en: 'Car',
      ckb: 'ترۆمبێل',
      pos: 'noun',
      emoji: '🚗',
      phonetic: '/kɑːr/',
      exampleEn: 'My father has a car.',
      exampleCkb: 'بابێ من ترۆمبێلەک هەیە.',
      category: 'transport',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-bus',
      en: 'Bus',
      ckb: 'پاس',
      pos: 'noun',
      emoji: '🚌',
      phonetic: '/bʌs/',
      exampleEn: 'I go to school by bus.',
      exampleCkb: 'ئەز ب پاسێ دچم قوتابخانێ.',
      category: 'transport',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-taxi',
      en: 'Taxi',
      ckb: 'تەکسی',
      pos: 'noun',
      emoji: '🚕',
      phonetic: '/ˈtæksi/',
      exampleEn: 'The taxi is yellow.',
      exampleCkb: 'تەکسی یا زەردە.',
      category: 'transport',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-train',
      en: 'Train',
      ckb: 'شەمەندەفەر',
      pos: 'noun',
      emoji: '🚆',
      phonetic: '/treɪn/',
      exampleEn: 'The train is fast.',
      exampleCkb: 'شەمەندەفەر یا بلەزە.',
      category: 'transport',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-plane',
      en: 'Plane',
      ckb: 'فڕۆکە',
      pos: 'noun',
      emoji: '✈️',
      phonetic: '/pleɪn/',
      exampleEn: 'The plane is in the sky.',
      exampleCkb: 'فڕۆکە ل ئەسمانییە.',
      category: 'transport',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-airport',
      en: 'Airport',
      ckb: 'فڕۆکەخانە',
      pos: 'noun',
      emoji: '🛫',
      phonetic: '/ˈɛrpɔːrt/',
      exampleEn: 'Where is the airport?',
      exampleCkb: 'فڕۆکەخانە ل کوویە؟',
      category: 'transport',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-road',
      en: 'Road',
      ckb: 'ڕێ',
      pos: 'noun',
      emoji: '🛤️',
      phonetic: '/roʊd/',
      exampleEn: 'This road is long.',
      exampleCkb: 'ڤێ ڕێ یا درێژە.',
      category: 'transport',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-street',
      en: 'Street',
      ckb: 'جادە',
      pos: 'noun',
      emoji: '🛣️',
      phonetic: '/striːt/',
      exampleEn: 'The bus is on the street.',
      exampleCkb: 'پاس ل جادەیێیە.',
      category: 'transport',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-ticket',
      en: 'Ticket',
      ckb: 'بلیت',
      pos: 'noun',
      emoji: '🎫',
      phonetic: '/ˈtɪkɪt/',
      exampleEn: 'I have a ticket.',
      exampleCkb: 'من بلیتەک هەیە.',
      category: 'transport',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l14-driver',
      en: 'Driver',
      ckb: 'شۆفێر',
      pos: 'noun',
      emoji: '🧑‍✈️',
      phonetic: '/ˈdraɪvər/',
      exampleEn: 'The driver is my uncle.',
      exampleCkb: 'شۆفێر مامێ منە.',
      category: 'transport',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I need a taxi.', ckb: 'پێدڤییا من ب تەکسییەکی هەیە.' },
    { en: 'I need a ticket.', ckb: 'پێدڤییا من ب بلیتەکێ هەیە.' },
    { en: 'I have a ticket.', ckb: 'من بلیتەک هەیە.' },
    { en: 'Where is the airport?', ckb: 'فڕۆکەخانە ل کوویە؟' },
    { en: 'I go by bus.', ckb: 'ئەز ب پاسێ دچم.' },
    { en: 'The driver is in the car.', ckb: 'شۆفێر ل ترۆمبێلێیە.' },
  ],
  conversation: [
    {
      characterId: 'azad',
      en: 'I need a taxi, please.',
      ckb: 'هیڤیدارم، پێدڤییا من ب تەکسییەکی هەیە.',
    },
    {
      characterId: 'shirin',
      en: 'Where do you want to go?',
      ckb: 'تو دڤێی بچی کوو؟',
    },
    {
      characterId: 'azad',
      en: 'To the airport, please.',
      ckb: 'هیڤیدارم، بۆ فڕۆکەخانێ.',
    },
    {
      characterId: 'shirin',
      en: 'Do you have a ticket?',
      ckb: 'بلیتا تە هەیە؟',
    },
    {
      characterId: 'azad',
      en: 'Yes, I have a ticket.',
      ckb: 'بەلێ، من بلیتەک هەیە.',
    },
    {
      characterId: 'shirin',
      en: 'Good! The plane is at eight o’clock.',
      ckb: 'باشە! فڕۆکە ل دەمژمێر هەشتێیە.',
    },
  ],
};
