import type { Level } from '../../types/content';

export const level12: Level = {
  id: 12,
  titleEn: 'Daily Routine',
  titleCkb: 'کارێن ڕۆژانە',
  icon: '🌅',
  objectiveEn: 'Talk about your daily routine.',
  objectiveCkb: 'بەحس ژ کارێن خو یێن ڕۆژانە بکە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l12-wake-up',
      en: 'wake up',
      ckb: 'هێش بوون',
      pos: 'verb',
      emoji: '⏰',
      phonetic: '/weɪk ʌp/',
      exampleEn: 'I wake up at seven.',
      exampleCkb: 'ئەز دەمژمێر حەفت هێش دبم.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-get-up',
      en: 'get up',
      ckb: 'سەرەکە هەستان',
      pos: 'verb',
      emoji: '🛏️',
      phonetic: '/ɡɛt ʌp/',
      exampleEn: 'I get up at seven.',
      exampleCkb: 'ئەز دەمژمێر حەفت سەرەکە هەژم.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-eat',
      en: 'eat',
      ckb: 'خوارن (ئەز دخوم)',
      pos: 'verb',
      emoji: '🍽️',
      phonetic: '/iːt/',
      exampleEn: 'I eat rice.',
      exampleCkb: 'ئەز برنجێ دخوم.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-drink',
      en: 'drink',
      ckb: 'ڤەخوارن (ئەز دڤێخوم)',
      pos: 'verb',
      emoji: '🥤',
      phonetic: '/drɪŋk/',
      exampleEn: 'I drink tea.',
      exampleCkb: 'ئەز چایێ دڤێخوم.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-go',
      en: 'go',
      ckb: 'چوون (ئەز دچم)',
      pos: 'verb',
      emoji: '🚶',
      phonetic: '/ɡəʊ/',
      exampleEn: 'I go to school.',
      exampleCkb: 'ئەز دچمە قوتابخانێ.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-come',
      en: 'come',
      ckb: 'هاتن (ئەز دێم)',
      pos: 'verb',
      emoji: '🏃',
      phonetic: '/kʌm/',
      exampleEn: 'Come here!',
      exampleCkb: 'وەرە ڤێرێ!',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-work',
      en: 'work',
      ckb: 'کارکرن (ئەز کار دکەم)',
      pos: 'verb',
      emoji: '💼',
      phonetic: '/wɜːk/',
      exampleEn: 'I work in the morning.',
      exampleCkb: 'ئەز سپێدە کار دکەم.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-study',
      en: 'study',
      ckb: 'خواندن (ئەز دخوینم)',
      pos: 'verb',
      emoji: '📚',
      phonetic: '/ˈstʌdi/',
      exampleEn: 'I study English.',
      exampleCkb: 'ئەز ئینگلیزی دخوینم.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-sleep',
      en: 'sleep',
      ckb: 'خەڤتن (ئەز ڕادکەڤم)',
      pos: 'verb',
      emoji: '😴',
      phonetic: '/sliːp/',
      exampleEn: 'I sleep at night.',
      exampleCkb: 'ئەز شەڤی ڕادکەڤم.',
      category: 'routine',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-go-home',
      en: 'go home',
      ckb: 'چوونە مال (ئەز دچمە مال)',
      pos: 'phrase',
      emoji: '🏠',
      phonetic: '/ɡəʊ həʊm/',
      exampleEn: 'I go home at five.',
      exampleCkb: 'ئەز دەمژمێر پێنجی دچمە مال.',
      category: 'routine',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-have-breakfast',
      en: 'have breakfast',
      ckb: 'ژار خوارن (ئەز ژارێ دخوم)',
      pos: 'phrase',
      emoji: '🍳',
      phonetic: '/hæv ˈbrɛkfəst/',
      exampleEn: 'I have breakfast at eight.',
      exampleCkb: 'ئەز دەمژمێر هەشتی ژارێ دخوم.',
      category: 'meals',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-have-lunch',
      en: 'have lunch',
      ckb: 'نانێ نیڤڕۆ خوارن',
      pos: 'phrase',
      emoji: '🥪',
      phonetic: '/hæv lʌntʃ/',
      exampleEn: 'I have lunch at one.',
      exampleCkb: 'ئەز دەمژمێر ئێکێ نانێ نیڤڕۆ دخوم.',
      category: 'meals',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l12-have-dinner',
      en: 'have dinner',
      ckb: 'نانێ ئێوارێ خوارن',
      pos: 'phrase',
      emoji: '🍲',
      phonetic: '/hæv ˈdɪnə/',
      exampleEn: 'I have dinner at seven.',
      exampleCkb: 'ئەز دەمژمێر حەفتی نانێ ئێوارێ دخوم.',
      category: 'meals',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I wake up at six.', ckb: 'ئەز دەمژمێر شەشی هێش دبم.' },
    { en: 'I have breakfast.', ckb: 'ئەز ژارێ دخوم.' },
    { en: 'I go to work.', ckb: 'ئەز دچمە کار.' },
    { en: 'I go home.', ckb: 'ئەز دچمە مال.' },
    { en: 'I have dinner.', ckb: 'ئەز نانێ ئێوارێ دخوم.' },
    { en: 'I sleep at night.', ckb: 'ئەز شەڤی ڕادکەڤم.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'When do you wake up?', ckb: 'تو دەمژمێر چەندێ هێش دبی؟' },
    { characterId: 'azad', en: 'I wake up at six.', ckb: 'ئەز دەمژمێر شەشی هێش دبم.' },
    { characterId: 'shirin', en: 'Do you have breakfast?', ckb: 'تو ژارێ دخوی؟' },
    { characterId: 'azad', en: 'Yes, I have breakfast at seven.', ckb: 'بەلێ، ئەز دەمژمێر حەفتی ژارێ دخوم.' },
    { characterId: 'shirin', en: 'When do you go to work?', ckb: 'تو دەمژمێر چەندێ دچیە کار؟' },
    { characterId: 'azad', en: 'I go to work at eight. I go home at five.', ckb: 'ئەز دەمژمێر هەشتی دچمە کار. ئەز دەمژمێر پێنجی دچمە مال.' },
  ],
};
