import type { Level } from '../../types/content';

export const level32: Level = {
  id: 32,
  titleEn: 'Restaurant English',
  titleCkb: 'ئینگلیزیا ڕێستۆرانتێ',
  icon: '🍽️',
  objectiveEn: 'Order food and drink in a restaurant and ask for the bill.',
  objectiveCkb: 'ل ڕێستۆرانتێ نان و وەخوارنێ داخاز بکە و حیسابێ بخوازە.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l32-menu',
      en: 'menu',
      ckb: 'مینیو',
      pos: 'noun',
      emoji: '📋',
      phonetic: '/ˈmɛnjuː/',
      exampleEn: 'Can I have the menu?',
      exampleCkb: 'دشێم مینیو وەربگرم؟',
      category: 'restaurant',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-order',
      en: 'order',
      ckb: 'داخازی کرن',
      pos: 'noun',
      emoji: '📝',
      phonetic: '/ˈɔːrdər/',
      exampleEn: 'Can I take your order?',
      exampleCkb: 'دشێم داخازیا تە وەربگرم؟',
      category: 'restaurant',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-waiter',
      en: 'waiter',
      ckb: 'گارسۆن',
      pos: 'noun',
      emoji: '🤵',
      phonetic: '/ˈweɪtər/',
      exampleEn: 'The waiter is very nice.',
      exampleCkb: 'گارسۆن زۆر یا باشە.',
      category: 'restaurant',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-table',
      en: 'table',
      ckb: 'مێز',
      pos: 'noun',
      emoji: '🪑',
      phonetic: '/ˈteɪbəl/',
      exampleEn: 'A table for two, please.',
      exampleCkb: 'هیڤیدارم، مێزەک بۆ دوو کەسان.',
      category: 'restaurant',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-water',
      en: 'water',
      ckb: 'ئاڤ',
      pos: 'noun',
      emoji: '💧',
      phonetic: '/ˈwɔːtər/',
      exampleEn: 'Can I have some water, please?',
      exampleCkb: 'هیڤیدارم، دشێم هندەک ئاڤی وەربگرم؟',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-coffee',
      en: 'coffee',
      ckb: 'قەھوە',
      pos: 'noun',
      emoji: '☕',
      phonetic: '/ˈkɔːfi/',
      exampleEn: "I'd like a coffee, please.",
      exampleCkb: 'هیڤیدارم، ئەز قەھوەیەکێ دڤێم.',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-tea',
      en: 'tea',
      ckb: 'چای',
      pos: 'noun',
      emoji: '🍵',
      phonetic: '/tiː/',
      exampleEn: 'Can I have a tea?',
      exampleCkb: 'دشێم چایەکێ وەربگرم؟',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-chicken',
      en: 'chicken',
      ckb: 'مریشک',
      pos: 'noun',
      emoji: '🍗',
      phonetic: '/ˈtʃɪkɪn/',
      exampleEn: "I'd like chicken and rice, please.",
      exampleCkb: 'هیڤیدارم، ئەز مریشک و برنج دڤێم.',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-rice',
      en: 'rice',
      ckb: 'برنج',
      pos: 'noun',
      emoji: '🍚',
      phonetic: '/raɪs/',
      exampleEn: 'The chicken and rice is very good.',
      exampleCkb: 'مریشک و برنج زۆر یا خۆشە.',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-fish',
      en: 'fish',
      ckb: 'ماسی',
      pos: 'noun',
      emoji: '🐟',
      phonetic: '/fɪʃ/',
      exampleEn: 'Do you have fish today?',
      exampleCkb: 'ئەڤڕۆ ماسی تە هەیە؟',
      category: 'food',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-bread',
      en: 'bread',
      ckb: 'نان',
      pos: 'noun',
      emoji: '🍞',
      phonetic: '/brɛd/',
      exampleEn: 'Can I have some bread, please?',
      exampleCkb: 'هیڤیدارم، دشێم هندەک نانی وەربگرم؟',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-bill',
      en: 'bill',
      ckb: 'حیساب',
      pos: 'noun',
      emoji: '🧾',
      phonetic: '/bɪl/',
      exampleEn: 'The bill, please.',
      exampleCkb: 'هیڤیدارم، حیسابە.',
      category: 'restaurant',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-breakfast',
      en: 'breakfast',
      ckb: 'تاشتی',
      pos: 'noun',
      emoji: '🍳',
      phonetic: '/ˈbrɛkfəst/',
      exampleEn: 'I have breakfast at eight o’clock.',
      exampleCkb: 'ئەز ل دەمژمێر هەشتێ تاشتیێ دخوم.',
      category: 'food',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l32-lunch',
      en: 'lunch',
      ckb: 'نانی نیڤرۆ',
      pos: 'noun',
      emoji: '🥗',
      phonetic: '/lʌntʃ/',
      exampleEn: 'What do you want for lunch?',
      exampleCkb: 'تو بۆ نانا نیڤرۆ چ دڤێی؟',
      category: 'food',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Can I have the menu?', ckb: 'دشێم مینیو وەربگرم؟' },
    { en: "I'd like chicken and rice, please.", ckb: 'هیڤیدارم، ئەز مریشک و برنج دڤێم.' },
    { en: 'Can I have some water?', ckb: 'دشێم هندەک ئاڤی وەربگرم؟' },
    { en: 'What do you recommend?', ckb: 'تو چ پێشنیار دکەی؟' },
    { en: 'A table for two, please.', ckb: 'هیڤیدارم، مێزەک بۆ دوو کەسان.' },
    { en: 'The bill, please.', ckb: 'هیڤیدارم، حیسابە.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Hello! A table for two?', ckb: 'سلاو! مێزەک بۆ دوو کەسان؟' },
    { characterId: 'dara', en: 'Yes, please. Can I have the menu?', ckb: 'بەلێ، هیڤیدارم. دشێم مینیو وەربگرم؟' },
    { characterId: 'shirin', en: 'Here you are. What would you like?', ckb: 'بگرە. تو چ دڤێی؟' },
    { characterId: 'dara', en: 'What do you recommend?', ckb: 'تو چ پێشنیار دکەی؟' },
    { characterId: 'shirin', en: 'The chicken and rice is very good.', ckb: 'مریشک و برنج زۆر یا خۆشە.' },
    { characterId: 'dara', en: "OK. I'd like chicken and rice, please.", ckb: 'باشە. هیڤیدارم، ئەز مریشک و برنج دڤێم.' },
    { characterId: 'shirin', en: 'And to drink?', ckb: 'و بۆ وەخوارنێ چی؟' },
    { characterId: 'dara', en: 'A tea and a coffee, please.', ckb: 'چایەک و قەھوەیەک، هیڤیدارم.' },
    { characterId: 'dara', en: 'It was delicious! The bill, please.', ckb: 'زۆر خۆش بوو! هیڤیدارم، حیسابە.' },
    { characterId: 'shirin', en: 'It is thirty dollars. Thank you, goodbye!', ckb: 'سی دۆلار دبیت. زۆر سپاس، خواهاتێ لگەڵ!' },
  ],
};
