import type { Level } from '../../types/content';

export const level31: Level = {
  id: 31,
  titleEn: 'Shopping Conversation',
  titleCkb: 'ئاخفتنا کڕینێ',
  icon: '🛍️',
  objectiveEn: 'Have a full shopping conversation: ask for items, prices and sizes, and pay.',
  objectiveCkb: 'ئاخفتنەکا تماما کڕینێ هەبێ: بپرسە بها چەندە، پێڤا چی دڤێی و پارە بدە.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l31-size',
      en: 'size',
      ckb: 'پێڤ',
      pos: 'noun',
      emoji: '📏',
      phonetic: '/saɪz/',
      exampleEn: 'What size do you want?',
      exampleCkb: 'تو پێڤا چی دڤێی؟',
      category: 'shopping',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-small',
      en: 'small',
      ckb: 'بچوک',
      pos: 'adjective',
      emoji: '🤏',
      phonetic: '/smɔːl/',
      exampleEn: 'Do you have a small size?',
      exampleCkb: 'پێڤا بچوک تە هەیە؟',
      category: 'shopping',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-medium',
      en: 'medium',
      ckb: 'مامناڤەندی',
      pos: 'adjective',
      emoji: '👕',
      phonetic: '/ˈmiːdiəm/',
      exampleEn: 'I want a medium, please.',
      exampleCkb: 'هیڤیدارم، ئەز مامناڤەندی دڤێم.',
      category: 'shopping',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-large',
      en: 'large',
      ckb: 'مەزن',
      pos: 'adjective',
      emoji: '🧥',
      phonetic: '/lɑːrdʒ/',
      exampleEn: 'Do you have a larger size?',
      exampleCkb: 'پێڤەکا مەزنتر تە هەیە؟',
      category: 'shopping',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-price',
      en: 'price',
      ckb: 'بها',
      pos: 'noun',
      emoji: '🏷️',
      phonetic: '/praɪs/',
      exampleEn: 'How much is it? The price is good.',
      exampleCkb: 'بها وی چەندە؟ بها باشە.',
      category: 'shopping',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-cash',
      en: 'cash',
      ckb: 'نەخت',
      pos: 'noun',
      emoji: '💵',
      phonetic: '/kæʃ/',
      exampleEn: 'I pay cash.',
      exampleCkb: 'ئەز نەخت ددەم.',
      category: 'money',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-card',
      en: 'card',
      ckb: 'کارت',
      pos: 'noun',
      emoji: '💳',
      phonetic: '/kɑːrd/',
      exampleEn: 'Can I pay by card?',
      exampleCkb: 'ئەز دشێم ب کارتێ بدەم؟',
      category: 'money',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-change',
      en: 'change',
      ckb: 'پاشماوە',
      pos: 'noun',
      emoji: '🪙',
      phonetic: '/tʃeɪndʒ/',
      exampleEn: 'Here is your change.',
      exampleCkb: 'بگرە پاشماوەیا تە.',
      category: 'money',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-buy',
      en: 'buy',
      ckb: 'کڕین (ئەز دکڕم)',
      pos: 'verb',
      emoji: '🛒',
      phonetic: '/baɪ/',
      exampleEn: 'I want to buy this shirt.',
      exampleCkb: 'ئەز دڤێم ڤێ کراسێ بکڕم.',
      category: 'shopping',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-sell',
      en: 'sell',
      ckb: 'فرۆتن (ئەز دفرۆشم)',
      pos: 'verb',
      emoji: '🏪',
      phonetic: '/sɛl/',
      exampleEn: 'They sell clothes here.',
      exampleCkb: 'ئەو ل ڤێرێ جلوبەرگێ دفرۆشن.',
      category: 'shopping',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-try',
      en: 'try',
      ckb: 'پێڤاندن (ئەز پێڤ دبەم)',
      pos: 'verb',
      emoji: '🪞',
      phonetic: '/traɪ/',
      exampleEn: 'Can I try it?',
      exampleCkb: 'ئەز دشێم پێڤی ببەم؟',
      category: 'shopping',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l31-fit',
      en: 'fit',
      ckb: 'ب قەپۆڵ هاتن',
      pos: 'verb',
      emoji: '👌',
      phonetic: '/fɪt/',
      exampleEn: 'It fits me well.',
      exampleCkb: 'باش ب قەپۆڵێ من دیت.',
      category: 'shopping',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'How much is it?', ckb: 'بها وی چەندە؟' },
    { en: 'How much are they?', ckb: 'بها وان چەندە؟' },
    { en: 'Can I try it?', ckb: 'ئەز دشێم پێڤی ببەم؟' },
    { en: 'Do you have a larger size?', ckb: 'پێڤەکا مەزنتر تە هەیە؟' },
    { en: 'I want this one.', ckb: 'ئەز ڤێ یا دڤێم.' },
    { en: "It's too expensive.", ckb: 'زۆر یا گرانە.' },
    { en: 'Can I pay by card?', ckb: 'ئەز دشێم ب کارتێ بدەم؟' },
  ],
  conversation: [
    { characterId: 'azad', en: 'Hello! Welcome to my shop.', ckb: 'سلاو! ب خێر هاتوی بۆ دکانا من.' },
    { characterId: 'rojin', en: 'Hello. I want this red shirt.', ckb: 'سلاو. ئەز ڤێ کراسا سۆر دڤێم.' },
    { characterId: 'azad', en: 'It is a nice shirt. What size do you want?', ckb: 'یا کراسا جوانە. تو پێڤا چی دڤێی؟' },
    { characterId: 'rojin', en: 'Medium, please. Can I try it?', ckb: 'هیڤیدارم، مامناڤەندی. ئەز دشێم پێڤی ببەم؟' },
    { characterId: 'azad', en: 'Yes, of course. It fits you well!', ckb: 'بەلێ، بێگومان. باش ب قەپۆڵێ تە دیت!' },
    { characterId: 'rojin', en: 'Good. How much is it?', ckb: 'باشە. بها وی چەندە؟' },
    { characterId: 'azad', en: 'It is twenty-five dollars.', ckb: 'بها وی بیست و پێنج دۆلارە.' },
    { characterId: 'rojin', en: 'It is a little expensive, but OK. I will take it.', ckb: 'هندەک یا گرانە، بەس باشە. ئەز وەردگرم.' },
    { characterId: 'azad', en: 'Cash or card?', ckb: 'نەخت یان کارت؟' },
    { characterId: 'rojin', en: 'By card, please. Thank you!', ckb: 'هیڤیدارم، ب کارتێ. زۆر سپاس!' },
  ],
};
