import type { Level } from '../../types/content';

export const level20: Level = {
  id: 20,
  titleEn: 'Basic English Challenge',
  titleCkb: 'تاقیکرنا ئینگلیزیا بنچینەیی',
  icon: '🏆',
  objectiveEn: 'Review everything: greetings, numbers, food, family, places and more in real situations.',
  objectiveCkb: 'هەمی تشتێن فێربووی دووبارە بکە: سلاو، ژمارە، خوارن، خیزان و جهێن جێجداهی.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l20-hello',
      en: 'hello',
      ckb: 'سلاو',
      pos: 'phrase',
      emoji: '👋',
      phonetic: '/heˈloʊ/',
      exampleEn: 'Hello, my friend!',
      exampleCkb: 'سلاو، هەڤالێ من!',
      category: 'review',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-friend',
      en: 'friend',
      ckb: 'هەڤال',
      pos: 'noun',
      emoji: '🧑‍🤝‍🧑',
      phonetic: '/frend/',
      exampleEn: 'He is my friend.',
      exampleCkb: 'ئەو هەڤالێ منە.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-five',
      en: 'five',
      ckb: 'پێنج',
      pos: 'number',
      emoji: '5️⃣',
      phonetic: '/faɪv/',
      exampleEn: 'I have five apples.',
      exampleCkb: 'پێنج سیڤێن من هەنە.',
      category: 'review',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-red',
      en: 'red',
      ckb: 'سۆر',
      pos: 'color',
      emoji: '🔴',
      phonetic: '/red/',
      exampleEn: 'The car is red.',
      exampleCkb: 'ترۆمبێل سۆرە.',
      category: 'review',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-mother',
      en: 'mother',
      ckb: 'دایک',
      pos: 'noun',
      emoji: '👩',
      phonetic: '/ˈmʌðər/',
      exampleEn: 'This is my mother.',
      exampleCkb: 'ئەڤ دایکا منە.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-house',
      en: 'house',
      ckb: 'مال',
      pos: 'noun',
      emoji: '🏠',
      phonetic: '/haʊs/',
      exampleEn: 'This is my house.',
      exampleCkb: 'ئەڤ مالا منە.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-book',
      en: 'book',
      ckb: 'پەرتووک',
      pos: 'noun',
      emoji: '📖',
      phonetic: '/bʊk/',
      exampleEn: 'I am reading a book.',
      exampleCkb: 'ئەز پەرتووکەکی دخوینم.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-water',
      en: 'water',
      ckb: 'ئاڤ',
      pos: 'noun',
      emoji: '💧',
      phonetic: '/ˈwɔːtər/',
      exampleEn: 'I want water, please.',
      exampleCkb: 'ئەز ئاڤێ دڤێم، هیڤیدارین.',
      category: 'review',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-want',
      en: 'want',
      ckb: 'ڤیان',
      pos: 'verb',
      emoji: '🛍️',
      phonetic: '/wɑːnt/',
      exampleEn: 'I want two teas.',
      exampleCkb: 'ئەز دوو چای دڤێم.',
      category: 'review',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-today',
      en: 'today',
      ckb: 'ئەڤڕۆ',
      pos: 'other',
      emoji: '📅',
      phonetic: '/təˈdeɪ/',
      exampleEn: 'Today is Monday.',
      exampleCkb: 'ئەڤڕۆ دووشەمبی یە.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-school',
      en: 'school',
      ckb: 'قوتابخانە',
      pos: 'noun',
      emoji: '🏫',
      phonetic: '/skuːl/',
      exampleEn: 'I go to school.',
      exampleCkb: 'ئەز دچمە قوتابخانێ.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-taxi',
      en: 'taxi',
      ckb: 'تەکسی',
      pos: 'noun',
      emoji: '🚕',
      phonetic: '/ˈtæksi/',
      exampleEn: 'I need a taxi.',
      exampleCkb: 'پێدڤیا من ب تاکسیەکێ هەیە.',
      category: 'review',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-shirt',
      en: 'shirt',
      ckb: 'کراس',
      pos: 'noun',
      emoji: '👕',
      phonetic: '/ʃɜːrt/',
      exampleEn: 'My shirt is blue.',
      exampleCkb: 'کراسا من شینە.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l20-sunny',
      en: 'sunny',
      ckb: 'ھەتاوی',
      pos: 'adjective',
      emoji: '☀️',
      phonetic: '/ˈsʌni/',
      exampleEn: 'It is sunny today.',
      exampleCkb: 'ئەڤڕۆ ب هەتاوە.',
      category: 'review',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Hello! What is your name?', ckb: 'سلاو! ناڤێ تە چیە؟' },
    { en: 'My name is Dara.', ckb: 'ناڤێ من دارا یە.' },
    { en: 'How much is it?', ckb: 'ئەڤ ب چەندە؟' },
    { en: 'I want a bottle of water.', ckb: 'ئەز شووشەکا ئاڤێ دڤێم.' },
    { en: 'Where is the airport?', ckb: 'فرۆکەخانە ل کویە؟' },
    { en: 'It is sunny today.', ckb: 'ئەڤڕۆ ب هەتاوە.' },
    { en: 'How are you? I am fine.', ckb: 'تو چەوا یی؟ ئەز باش مە.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Hello! What is your name?', ckb: 'سلاو! ناڤێ تە چیە؟' },
    { characterId: 'dara', en: 'My name is Dara.', ckb: 'ناڤێ من دارا یە.' },
    { characterId: 'shirin', en: 'Nice to meet you, Dara. Can I help you?', ckb: 'دلخۆش مە ب دیتنا تە، دارا. ئەز دشێم هاریکاریا تە بکەم؟' },
    { characterId: 'dara', en: 'Yes, I want a bottle of water and two apples.', ckb: 'بەلێ، ئەز شووشەکا ئاڤێ و دوو سیڤ دڤێم.' },
    { characterId: 'shirin', en: 'Of course. Here you are.', ckb: 'بێگومان. ئەڤە بۆ تە.' },
    { characterId: 'dara', en: 'How much is it?', ckb: 'ئەڤ ب چەندە؟' },
    { characterId: 'shirin', en: 'It is five dollars.', ckb: 'پێنج دۆلارە.' },
    { characterId: 'dara', en: 'Here you are. Thank you very much!', ckb: 'ئەڤە بۆ تە. زۆر سوپاس!' },
    { characterId: 'shirin', en: "You're welcome. Goodbye!", ckb: 'ب دەم و چاڤێ. ب خاتی تە!' },
  ],
};
