import type { Level } from '../../types/content';

export const level03: Level = {
  id: 3,
  titleEn: 'Numbers',
  titleCkb: 'ژمارە',
  icon: '🔢',
  objectiveEn: 'Count from one to twenty and ask "How many?".',
  objectiveCkb: 'ژ ئێکێ هەتا بیست بژمێری و بپرسی «چەند؟».',
  cefr: 'A1',
  vocab: [
    {
      id: 'l3-one',
      en: 'One',
      ckb: 'ئێک',
      pos: 'number',
      emoji: '1️⃣',
      phonetic: '/wʌn/',
      exampleEn: 'One apple.',
      exampleCkb: 'سیڤەک.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-two',
      en: 'Two',
      ckb: 'دوو',
      pos: 'number',
      emoji: '2️⃣',
      phonetic: '/tuː/',
      exampleEn: 'Two cars.',
      exampleCkb: 'دوو ترومبێل.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-three',
      en: 'Three',
      ckb: 'سێ',
      pos: 'number',
      emoji: '3️⃣',
      phonetic: '/θriː/',
      exampleEn: 'Three books.',
      exampleCkb: 'سێ پەرتووک.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-four',
      en: 'Four',
      ckb: 'چار',
      pos: 'number',
      emoji: '4️⃣',
      phonetic: '/fɔː/',
      exampleEn: 'Four pens.',
      exampleCkb: 'چار پێنووس.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-five',
      en: 'Five',
      ckb: 'پێنج',
      pos: 'number',
      emoji: '5️⃣',
      phonetic: '/faɪv/',
      exampleEn: 'Five boys.',
      exampleCkb: 'پێنج کور.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-six',
      en: 'Six',
      ckb: 'شەش',
      pos: 'number',
      emoji: '6️⃣',
      phonetic: '/sɪks/',
      exampleEn: 'Six girls.',
      exampleCkb: 'شەش کێچ.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-seven',
      en: 'Seven',
      ckb: 'حەڤت',
      pos: 'number',
      emoji: '7️⃣',
      phonetic: '/ˈsevən/',
      exampleEn: 'Seven days.',
      exampleCkb: 'حەڤت ڕۆژ.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-eight',
      en: 'Eight',
      ckb: 'هەشت',
      pos: 'number',
      emoji: '8️⃣',
      phonetic: '/eɪt/',
      exampleEn: 'Eight cups.',
      exampleCkb: 'هەشت فینجان.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-nine',
      en: 'Nine',
      ckb: 'نەه',
      pos: 'number',
      emoji: '9️⃣',
      phonetic: '/naɪn/',
      exampleEn: 'Nine eggs.',
      exampleCkb: 'نەه هێک.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-ten',
      en: 'Ten',
      ckb: 'دەه',
      pos: 'number',
      emoji: '🔟',
      phonetic: '/ten/',
      exampleEn: 'Ten apples.',
      exampleCkb: 'دەه سیڤ.',
      category: 'Numbers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-eleven',
      en: 'Eleven',
      ckb: 'یازدە',
      pos: 'number',
      emoji: '1️⃣1️⃣',
      phonetic: '/ɪˈlevən/',
      exampleEn: 'Eleven apples.',
      exampleCkb: 'یازدە سیڤ.',
      category: 'Numbers',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-twelve',
      en: 'Twelve',
      ckb: 'دوازدە',
      pos: 'number',
      emoji: '1️⃣2️⃣',
      phonetic: '/twelv/',
      exampleEn: 'Twelve months.',
      exampleCkb: 'دوازدە مەه.',
      category: 'Numbers',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-thirteen',
      en: 'Thirteen',
      ckb: 'سیازدە',
      pos: 'number',
      emoji: '1️⃣3️⃣',
      phonetic: '/ˌθɜːˈtiːn/',
      exampleEn: 'Thirteen books.',
      exampleCkb: 'سیازدە پەرتووک.',
      category: 'Numbers',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-fourteen',
      en: 'Fourteen',
      ckb: 'چاردە',
      pos: 'number',
      emoji: '1️⃣4️⃣',
      phonetic: '/ˌfɔːˈtiːn/',
      exampleEn: 'Fourteen pens.',
      exampleCkb: 'چاردە پێنووس.',
      category: 'Numbers',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-fifteen',
      en: 'Fifteen',
      ckb: 'پازدە',
      pos: 'number',
      emoji: '1️⃣5️⃣',
      phonetic: '/ˌfɪfˈtiːn/',
      exampleEn: 'Fifteen eggs.',
      exampleCkb: 'پازدە هێک.',
      category: 'Numbers',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-sixteen',
      en: 'Sixteen',
      ckb: 'شازدە',
      pos: 'number',
      emoji: '1️⃣6️⃣',
      phonetic: '/ˌsɪksˈtiːn/',
      exampleEn: 'Sixteen apples.',
      exampleCkb: 'شازدە سیڤ.',
      category: 'Numbers',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-seventeen',
      en: 'Seventeen',
      ckb: 'حەڤدە',
      pos: 'number',
      emoji: '1️⃣7️⃣',
      phonetic: '/ˌsevənˈtiːn/',
      exampleEn: 'Seventeen cars.',
      exampleCkb: 'حەڤدە ترومبێل.',
      category: 'Numbers',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-eighteen',
      en: 'Eighteen',
      ckb: 'هەژدە',
      pos: 'number',
      emoji: '1️⃣8️⃣',
      phonetic: '/ˌeɪˈtiːn/',
      exampleEn: 'Eighteen books.',
      exampleCkb: 'هەژدە پەرتووک.',
      category: 'Numbers',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-nineteen',
      en: 'Nineteen',
      ckb: 'نۆزدە',
      pos: 'number',
      emoji: '1️⃣9️⃣',
      phonetic: '/ˌnaɪnˈtiːn/',
      exampleEn: 'Nineteen cups.',
      exampleCkb: 'نۆزدە فینجان.',
      category: 'Numbers',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l3-twenty',
      en: 'Twenty',
      ckb: 'بیست',
      pos: 'number',
      emoji: '2️⃣0️⃣',
      phonetic: '/ˈtwenti/',
      exampleEn: 'Twenty boys.',
      exampleCkb: 'بیست کور.',
      category: 'Numbers',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'How many?', ckb: 'چەند؟ — بۆ پسیارکرنا ژمارا تشتان' },
    { en: 'One apple.', ckb: 'سیڤەک. — دگەل «one» ناڤ ب رێکا تاک دێت: one apple' },
    { en: 'Two cars.', ckb: 'دوو ترومبێل. — دگەل ژمارەیێن مەزنتر، ناڤ ب رێکا کۆم دێت: two carS' },
    { en: 'Three books.', ckb: 'سێ پەرتووک. — ژمارە بەر پێش ناڤی دێت' },
    { en: 'How many apples? Three.', ckb: 'چەند سیڤ؟ سێ. — بەرسڤا کورت تێڕۆیە' },
    { en: 'I am ten.', ckb: 'ئەز دەه سالی مە. — بۆ تەمەنی: I am + ژمارە' },
  ],
  conversation: [
    { characterId: 'rojin', en: 'Look! How many apples?', ckb: 'بینە! چەند سیڤ؟' },
    { characterId: 'dara', en: 'One, two, three. Three apples!', ckb: 'ئێک، دوو، سێ. سێ سیڤ!' },
    { characterId: 'rojin', en: 'Good! How many books?', ckb: 'باشە! چەند پەرتووک؟' },
    { characterId: 'dara', en: 'Five books.', ckb: 'پێنج پەرتووک.' },
    { characterId: 'rojin', en: 'And how many pens?', ckb: 'و چەند پێنووس؟' },
    { characterId: 'dara', en: 'Hmm... ten pens!', ckb: 'هەمم... دەه پێنووس!' },
    { characterId: 'rojin', en: 'No! Eleven pens.', ckb: 'نەخێر! یازدە پێنووس.' },
    { characterId: 'dara', en: 'Eleven? Yes, eleven!', ckb: 'یازدە؟ بەلێ، یازدە!' },
  ],
};
