import type { Level } from '../../types/content';

export const level28: Level = {
  id: 28,
  titleEn: 'The Past: Yesterday',
  titleCkb: 'رابووردوو: دوھێ',
  icon: '⏮️',
  objectiveEn: 'Talk about what you did yesterday.',
  objectiveCkb: 'بەحس ژ وان تشتان بکە کو تو دوھێ کرن.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l28-yesterday',
      en: 'yesterday',
      ckb: 'دوھێ',
      pos: 'other',
      emoji: '📅',
      phonetic: '/ˈjestərdeɪ/',
      exampleEn: 'I worked yesterday.',
      exampleCkb: 'من دوھێ کار کر.',
      category: 'time',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-last-night',
      en: 'last night',
      ckb: 'دوھێ شەڤ',
      pos: 'other',
      emoji: '🌙',
      phonetic: '/lɑːst naɪt/',
      exampleEn: 'I watched a movie last night.',
      exampleCkb: 'من دوھێ شەڤ فلمەک تەماشە کر.',
      category: 'time',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-last-week',
      en: 'last week',
      ckb: 'هەفتیا ڕابووری',
      pos: 'other',
      emoji: '🗓️',
      phonetic: '/lɑːst wiːk/',
      exampleEn: 'I visited my family last week.',
      exampleCkb: 'من هەفتیا رابووری سەرەدانا خیزانا خو کر.',
      category: 'time',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-went',
      en: 'went',
      ckb: 'چوو',
      pos: 'verb',
      emoji: '🚶',
      phonetic: '/went/',
      exampleEn: 'I went to the shop.',
      exampleCkb: 'ئەز چوومە دۆکانێ.',
      category: 'past',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-had',
      en: 'had',
      ckb: 'ھەبوون (من ھەبوو)',
      pos: 'verb',
      emoji: '🤲',
      phonetic: '/hæd/',
      exampleEn: 'I had a good day.',
      exampleCkb: 'ڕۆژەکا باش یا من هەبوو.',
      category: 'past',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-ate',
      en: 'ate',
      ckb: 'خوارن (من خوار)',
      pos: 'verb',
      emoji: '🍽️',
      phonetic: '/eɪt/',
      exampleEn: 'I ate chicken yesterday.',
      exampleCkb: 'من دوھێ مریشک خوار.',
      category: 'past',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-drank',
      en: 'drank',
      ckb: 'ڤەخوارن (من ڤەخوار)',
      pos: 'verb',
      emoji: '☕',
      phonetic: '/dræŋk/',
      exampleEn: 'I drank coffee at work.',
      exampleCkb: 'من ل کار قەهوێ ڤەخوار.',
      category: 'past',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-saw',
      en: 'saw',
      ckb: 'دیت',
      pos: 'verb',
      emoji: '👀',
      phonetic: '/sɔː/',
      exampleEn: 'I saw my friend in the shop.',
      exampleCkb: 'من هەڤالێ خو ل دۆکانێ دیت.',
      category: 'past',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-bought',
      en: 'bought',
      ckb: 'کرین (من کری)',
      pos: 'verb',
      emoji: '🛍️',
      phonetic: '/bɔːt/',
      exampleEn: 'I bought a shirt.',
      exampleCkb: 'من کراسەک کری.',
      category: 'past',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-worked',
      en: 'worked',
      ckb: 'کارکرن (من کار کر)',
      pos: 'verb',
      emoji: '💼',
      phonetic: '/wɜːkt/',
      exampleEn: 'Yesterday I worked at home.',
      exampleCkb: 'من دوھێ ل مال کار کر.',
      category: 'past',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-played',
      en: 'played',
      ckb: 'لێستن (من لێست)',
      pos: 'verb',
      emoji: '⚽',
      phonetic: '/pleɪd/',
      exampleEn: 'We played football yesterday.',
      exampleCkb: 'مە دوھێ فوتبۆل لێست.',
      category: 'past',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-watched',
      en: 'watched',
      ckb: 'تەماشەکرن (من تەماشە کر)',
      pos: 'verb',
      emoji: '📺',
      phonetic: '/wɒtʃt/',
      exampleEn: 'I watched a movie.',
      exampleCkb: 'من فلمەک تەماشە کر.',
      category: 'past',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l28-visited',
      en: 'visited',
      ckb: 'سەرەدانکرن (من سەرەدان کر)',
      pos: 'verb',
      emoji: '🏡',
      phonetic: '/ˈvɪzɪtɪd/',
      exampleEn: 'I visited my mother.',
      exampleCkb: 'من سەرەدانا دایکا خو کر.',
      category: 'past',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Yesterday I worked.', ckb: 'من دوھێ کار کر.' },
    { en: 'I went to the shop.', ckb: 'ئەز چوومە دۆکانێ.' },
    { en: 'I ate chicken.', ckb: 'من مریشک خوار.' },
    { en: 'I drank coffee.', ckb: 'من قەهوێ ڤەخوار.' },
    { en: 'I watched a movie.', ckb: 'من فلمەک تەماشە کر.' },
    { en: 'I bought a shirt.', ckb: 'من کراسەک کری.' },
    { en: 'I visited my family.', ckb: 'من سەرەدانا خیزانا خو کر.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Yesterday was a busy day.', ckb: 'دوھێ ڕۆژەکا مژوول بوو.' },
    { characterId: 'azad', en: 'Yes! I worked in the morning.', ckb: 'بەلێ! من سپێدە کار کر.' },
    { characterId: 'shirin', en: 'I went to the shop and bought a shirt.', ckb: 'ئەز چوومە دۆکانێ و من کراسەک کری.' },
    { characterId: 'azad', en: 'I ate chicken for lunch.', ckb: 'من بۆ نانێ نیڤڕۆ مریشک خوار.' },
    { characterId: 'shirin', en: 'Last night I watched a movie.', ckb: 'من دوھێ شەڤ فلمەک تەماشە کر.' },
    { characterId: 'azad', en: 'I played football with Dara.', ckb: 'مە دگەل دارا فوتبۆل لێست.' },
    { characterId: 'shirin', en: 'And then I went home at ten.', ckb: 'و پاشی ئەز دەمژمێر دەهی چوومە مال.' },
  ],
};
