import type { Level } from '../../types/content';

export const level09: Level = {
  id: 9,
  titleEn: 'Food & Drink',
  titleCkb: 'خواردن و ڤەخوارن',
  icon: '🍎',
  objectiveEn: 'Name common foods and drinks and say what you like.',
  objectiveCkb: 'پەیڤێن خواردن و ڤەخوارنێ فێر ببە و بڵێ ژ چ حەز دکەی و ژ چ حەز ناکەی.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l9-water',
      en: 'water',
      ckb: 'ئاڤ',
      pos: 'noun',
      emoji: '💧',
      phonetic: '/ˈwɔːtər/',
      exampleEn: 'I drink water.',
      exampleCkb: 'ئەز ئاڤێ دڤێخوم.',
      category: 'drink',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-milk',
      en: 'milk',
      ckb: 'شیر',
      pos: 'noun',
      emoji: '🥛',
      phonetic: '/mɪlk/',
      exampleEn: 'The milk is white.',
      exampleCkb: 'شیر سپی یە.',
      category: 'drink',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-tea',
      en: 'tea',
      ckb: 'چای',
      pos: 'noun',
      emoji: '🍵',
      phonetic: '/tiː/',
      exampleEn: 'I like tea.',
      exampleCkb: 'ئەز حەز ژ چایێ دکەم.',
      category: 'drink',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-coffee',
      en: 'coffee',
      ckb: 'قەهوە',
      pos: 'noun',
      emoji: '☕',
      phonetic: '/ˈkɔːfi/',
      exampleEn: 'I like coffee.',
      exampleCkb: 'ئەز حەز ژ قەهوەیێ دکەم.',
      category: 'drink',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-bread',
      en: 'bread',
      ckb: 'نان',
      pos: 'noun',
      emoji: '🍞',
      phonetic: '/brɛd/',
      exampleEn: 'The bread is hot.',
      exampleCkb: 'نان گەرمە.',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-rice',
      en: 'rice',
      ckb: 'برنج',
      pos: 'noun',
      emoji: '🍚',
      phonetic: '/raɪs/',
      exampleEn: 'I eat rice.',
      exampleCkb: 'ئەز برنجێ دخوم.',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-chicken',
      en: 'chicken',
      ckb: 'مریشک',
      pos: 'noun',
      emoji: '🍗',
      phonetic: '/ˈtʃɪkɪn/',
      exampleEn: 'I like chicken.',
      exampleCkb: 'ئەز حەز ژ مریشکێ دکەم.',
      category: 'food',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-meat',
      en: 'meat',
      ckb: 'گۆشت',
      pos: 'noun',
      emoji: '🥩',
      phonetic: '/miːt/',
      exampleEn: "I don't like meat.",
      exampleCkb: 'ئەز حەز ژ گۆشتی ناکەم.',
      category: 'food',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-fish',
      en: 'fish',
      ckb: 'ماسی',
      pos: 'noun',
      emoji: '🐟',
      phonetic: '/fɪʃ/',
      exampleEn: "I don't like fish.",
      exampleCkb: 'ئەز حەز ژ ماسیێ ناکەم.',
      category: 'food',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-apple',
      en: 'apple',
      ckb: 'سێڤ',
      pos: 'noun',
      emoji: '🍎',
      phonetic: '/ˈæpəl/',
      exampleEn: 'The apple is red.',
      exampleCkb: 'سێڤ سۆرە.',
      category: 'fruit',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-banana',
      en: 'banana',
      ckb: 'مۆز',
      pos: 'noun',
      emoji: '🍌',
      phonetic: '/bəˈnɑːnə/',
      exampleEn: 'The banana is yellow.',
      exampleCkb: 'موس زەردە.',
      category: 'fruit',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-orange',
      en: 'orange',
      ckb: 'پرتەقال',
      pos: 'noun',
      emoji: '🍊',
      phonetic: '/ˈɒrɪndʒ/',
      exampleEn: 'I eat an orange.',
      exampleCkb: 'ئەز پرتەقالەکێ دخوم.',
      category: 'fruit',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-egg',
      en: 'egg',
      ckb: 'هێک',
      pos: 'noun',
      emoji: '🥚',
      phonetic: '/ɛɡ/',
      exampleEn: 'I eat an egg.',
      exampleCkb: 'ئەز هێکەکێ دخوم.',
      category: 'food',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l9-cheese',
      en: 'cheese',
      ckb: 'پەنیر',
      pos: 'noun',
      emoji: '🧀',
      phonetic: '/tʃiːz/',
      exampleEn: 'I like cheese.',
      exampleCkb: 'ئەز حەز ژ پەنیری دکەم.',
      category: 'food',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I like tea.', ckb: 'ئەز حەز ژ چایێ دکەم.' },
    { en: 'I like apples.', ckb: 'ئەز حەز ژ سێڤان دکەم.' },
    { en: "I don't like fish.", ckb: 'ئەز حەز ژ ماسیێ ناکەم.' },
    { en: 'Do you like coffee?', ckb: 'تو ژ قەهوەیێ حەز دکەی؟' },
    { en: 'Yes, I like coffee.', ckb: 'بەلێ، ئەز ژ قەهوەیێ حەز دکەم.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Hello! Welcome.', ckb: 'سلاو! ب خێر هاتوی.' },
    { characterId: 'rojin', en: 'Hello. I want tea, please.', ckb: 'سلاو. ئەز چایەکێ دڤێم، هیڤیدارم.' },
    { characterId: 'shirin', en: 'Do you like chicken?', ckb: 'تو ژ مریشکێ حەز دکەی؟' },
    { characterId: 'rojin', en: 'Yes, I like chicken.', ckb: 'بەلێ، ئەز ژ مریشکێ حەز دکەم.' },
    { characterId: 'shirin', en: 'Do you want rice?', ckb: 'تو برنجی دڤێی؟' },
    { characterId: 'rojin', en: 'Yes, and water, please.', ckb: 'بەلێ، و ئاڤەکا ژی، هیڤیدارم.' },
    { characterId: 'shirin', en: 'Enjoy your meal!', ckb: 'نۆش تە بیت!' },
  ],
};
