import type { Level } from '../../types/content';

export const level17: Level = {
  id: 17,
  titleEn: 'Common Actions',
  titleCkb: 'کرارێن گشتی',
  icon: '🏃',
  objectiveEn: 'Use common action verbs and say what people are doing.',
  objectiveCkb: 'پەیڤێن کراران بکاربینە و بڵێ خەلک چ دکەن.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l17-run',
      en: 'run',
      ckb: 'بەزین',
      pos: 'verb',
      emoji: '🏃',
      phonetic: '/rʌn/',
      exampleEn: 'I am running.',
      exampleCkb: 'ئەز دڕیکم.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-walk',
      en: 'walk',
      ckb: 'پیاسەکرن',
      pos: 'verb',
      emoji: '🚶',
      phonetic: '/wɔːk/',
      exampleEn: 'She is walking to school.',
      exampleCkb: 'ئەو پیاسە دکە بۆ قوتابخانێ.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-eat',
      en: 'eat',
      ckb: 'خوارن',
      pos: 'verb',
      emoji: '🍽️',
      phonetic: '/iːt/',
      exampleEn: 'I eat bread.',
      exampleCkb: 'ئەز نانێ دخوم.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-drink',
      en: 'drink',
      ckb: 'ڤەخوارن',
      pos: 'verb',
      emoji: '🥤',
      phonetic: '/drɪŋk/',
      exampleEn: 'He is drinking water.',
      exampleCkb: 'ئەو ئاڤێ دڤەخۆ.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-sleep',
      en: 'sleep',
      ckb: 'نووستن',
      pos: 'verb',
      emoji: '😴',
      phonetic: '/sliːp/',
      exampleEn: 'I sleep at night.',
      exampleCkb: 'ئەز ب شەڤ دنووم.',
      category: 'actions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-read',
      en: 'read',
      ckb: 'خویندن',
      pos: 'verb',
      emoji: '📖',
      phonetic: '/riːd/',
      exampleEn: 'She is reading a book.',
      exampleCkb: 'ئەو پەرتووکەکی دخوینە.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-write',
      en: 'write',
      ckb: 'نڤیسین',
      pos: 'verb',
      emoji: '✍️',
      phonetic: '/raɪt/',
      exampleEn: 'He is writing.',
      exampleCkb: 'ئەو دنڤیسە.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-speak',
      en: 'speak',
      ckb: 'ئاخفتن',
      pos: 'verb',
      emoji: '🗣️',
      phonetic: '/spiːk/',
      exampleEn: 'I speak Kurdish.',
      exampleCkb: 'ئەز ب کوردی دئاخڤم.',
      category: 'actions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-listen',
      en: 'listen',
      ckb: 'گوهداریکرن',
      pos: 'verb',
      emoji: '👂',
      phonetic: '/ˈlɪsən/',
      exampleEn: 'I am listening to you.',
      exampleCkb: 'ئەز گوهداریێ تە دکەم.',
      category: 'actions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-open',
      en: 'open',
      ckb: 'ڤەکرن',
      pos: 'verb',
      emoji: '🔓',
      phonetic: '/ˈoʊpən/',
      exampleEn: 'I open the door.',
      exampleCkb: 'ئەز دەرگەهێ دڤەکم.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-close',
      en: 'close',
      ckb: 'گرتن',
      pos: 'verb',
      emoji: '🔒',
      phonetic: '/kloʊz/',
      exampleEn: 'Close the window, please.',
      exampleCkb: 'هیڤیدارین پەنجەرێ بگرە.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-sit',
      en: 'sit',
      ckb: 'رۆنیشتن',
      pos: 'verb',
      emoji: '🪑',
      phonetic: '/sɪt/',
      exampleEn: 'I sit on the chair.',
      exampleCkb: 'ئەز ل سەر کورسیێ دنیشم.',
      category: 'actions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-stand',
      en: 'stand',
      ckb: 'وەستان',
      pos: 'verb',
      emoji: '🧍',
      phonetic: '/stænd/',
      exampleEn: 'I am standing.',
      exampleCkb: 'ئەز ب سەرپێ مە.',
      category: 'actions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l17-look',
      en: 'look',
      ckb: 'سەحکرن',
      pos: 'verb',
      emoji: '👀',
      phonetic: '/lʊk/',
      exampleEn: 'Look at me.',
      exampleCkb: 'ب سەر من دا بسەحە.',
      category: 'actions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I am walking.', ckb: 'ئەز پیاسە دکەم.' },
    { en: 'He is running.', ckb: 'ئەو دڕیکی.' },
    { en: 'She is eating.', ckb: 'ئەو دخۆ.' },
    { en: 'I am drinking water.', ckb: 'ئەز ئاڤێ دڤەخوم.' },
    { en: 'She is reading a book.', ckb: 'ئەو پەرتووکەکی دخوینە.' },
    { en: 'He is sleeping.', ckb: 'ئەو دنووە.' },
  ],
  conversation: [
    { characterId: 'dara', en: 'What are you doing, Rojin?', ckb: 'تو چ دکەی، ڕۆژین؟' },
    { characterId: 'rojin', en: 'I am reading a book.', ckb: 'ئەز پەرتووکەکی دخوینم.' },
    { characterId: 'dara', en: 'Look! Azad is running.', ckb: 'بسەحە! ئازاد دڕیکی.' },
    { characterId: 'rojin', en: 'He is fast!', ckb: 'ئەو ب خێرایە!' },
    { characterId: 'rojin', en: 'Where is Shirin?', ckb: 'شیرین ل کویە؟' },
    { characterId: 'dara', en: 'She is sleeping.', ckb: 'ئەو دنووە.' },
    { characterId: 'rojin', en: 'And I am drinking tea.', ckb: 'و ئەز چایێ دڤەخوم.' },
    { characterId: 'dara', en: 'And I am listening to you!', ckb: 'و ئەز گوهداریێ تە دکەم!' },
  ],
};
