import type { Level } from '../../types/content';

export const level02: Level = {
  id: 2,
  titleEn: 'My name is...',
  titleCkb: 'ناڤێ من...',
  icon: '🙂',
  objectiveEn: 'Introduce yourself and ask someone their name.',
  objectiveCkb: 'خو بناسینە و ناڤێ کەسان ژی بپرسی.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l2-i',
      en: 'I',
      ckb: 'ئەز',
      pos: 'other',
      emoji: '🙋',
      phonetic: '/aɪ/',
      exampleEn: 'I am Dara.',
      exampleCkb: 'ئەز دارا مە.',
      category: 'People',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-you',
      en: 'You',
      ckb: 'تو',
      pos: 'other',
      emoji: '🫵',
      phonetic: '/juː/',
      exampleEn: 'You are my friend.',
      exampleCkb: 'تو هەڤاڵێ من یی.',
      category: 'People',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-my',
      en: 'My',
      ckb: 'یێ من / یا من',
      pos: 'other',
      emoji: '🤲',
      phonetic: '/maɪ/',
      exampleEn: 'My name is Dara.',
      exampleCkb: 'ناڤێ من دارا یە.',
      category: 'People',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-your',
      en: 'Your',
      ckb: 'یێ تە / یا تە',
      pos: 'other',
      emoji: '🫴',
      phonetic: '/jɔː/',
      exampleEn: 'What is your name?',
      exampleCkb: 'ناڤێ تە چیە؟',
      category: 'People',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-name',
      en: 'Name',
      ckb: 'ناڤ',
      pos: 'noun',
      emoji: '📛',
      phonetic: '/neɪm/',
      exampleEn: 'My name is Rojin.',
      exampleCkb: 'ناڤێ من ڕۆژینە.',
      category: 'People',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-friend',
      en: 'Friend',
      ckb: 'هەڤاڵ',
      pos: 'noun',
      emoji: '🤝',
      phonetic: '/frend/',
      exampleEn: 'He is my friend.',
      exampleCkb: 'ئەو هەڤاڵێ منە.',
      category: 'People',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-boy',
      en: 'Boy',
      ckb: 'کور',
      pos: 'noun',
      emoji: '👦',
      phonetic: '/bɔɪ/',
      exampleEn: 'He is a boy.',
      exampleCkb: 'ئەو کورەکە.',
      category: 'People',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-girl',
      en: 'Girl',
      ckb: 'کێچ',
      pos: 'noun',
      emoji: '👧',
      phonetic: '/ɡɜːl/',
      exampleEn: 'She is a girl.',
      exampleCkb: 'ئەو کێچەکە.',
      category: 'People',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-man',
      en: 'Man',
      ckb: 'زەلام',
      pos: 'noun',
      emoji: '👨',
      phonetic: '/mæn/',
      exampleEn: 'He is a man.',
      exampleCkb: 'ئەو زەلامەکە.',
      category: 'People',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l2-woman',
      en: 'Woman',
      ckb: 'ژن',
      pos: 'noun',
      emoji: '👩',
      phonetic: '/ˈwʊmən/',
      exampleEn: 'She is a woman.',
      exampleCkb: 'ئەو ژنەکە.',
      category: 'People',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I am Dara.', ckb: 'ئەز دارا مە. — «I am» = ئەز ... مە' },
    { en: 'My name is Dara.', ckb: 'ناڤێ من دارا یە. — «My name is» = ناڤێ من ... یە' },
    { en: 'You are my friend.', ckb: 'تو هەڤاڵێ من یی. — «You are» = تو ... یی' },
    { en: 'What is your name?', ckb: 'ناڤێ تە چیە؟ — بۆ پسیارکرنا ناڤێ کەسەکی' },
    { en: 'Nice to meet you.', ckb: 'خۆشحال مە ب ناسکرنا تە. — دەمێ تو کەسەکی بۆ جارا ئێکێ دبینی' },
    { en: 'This is my friend.', ckb: 'ئەڤە هەڤاڵێ منە. — «This is» = ئەڤە ... ـە' },
  ],
  conversation: [
    { characterId: 'azad', en: 'Hello! What is your name?', ckb: 'سلاڤ! ناڤێ تە چیە؟' },
    { characterId: 'shirin', en: 'My name is Shirin.', ckb: 'ناڤێ من شیرینە.' },
    { characterId: 'azad', en: 'I am Azad. Nice to meet you.', ckb: 'ئەز ئازاد مە. خۆشحال مە ب ناسکرنا تە.' },
    { characterId: 'shirin', en: 'Nice to meet you too.', ckb: 'ئەز ژی خۆشحال مە ب ناسکرنا تە.' },
    { characterId: 'azad', en: 'You are my friend.', ckb: 'تو هەڤاڵێ من یی.' },
    { characterId: 'shirin', en: 'Yes! Goodbye, Azad.', ckb: 'بەلێ! ب خاترێ تە، ئازاد.' },
  ],
};
