import type { Level } from '../../types/content';

export const level29: Level = {
  id: 29,
  titleEn: 'Questions in the Past',
  titleCkb: 'پسیار ل سەر رابووردووی',
  icon: '❓',
  objectiveEn: 'Ask and answer questions about yesterday.',
  objectiveCkb: 'پسیاران ل سەر دوھێ بکە و بەرسڤان بدە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l29-did-you',
      en: 'did you...?',
      ckb: 'تو ... کری؟',
      pos: 'question',
      emoji: '❓',
      phonetic: '/dɪd juː/',
      exampleEn: 'Did you work yesterday?',
      exampleCkb: 'تو دوھێ کار کری؟',
      category: 'questions',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-what-did-you-do',
      en: 'what did you do?',
      ckb: 'تو چ کر؟',
      pos: 'question',
      emoji: '🤔',
      phonetic: '/wɒt dɪd juː duː/',
      exampleEn: 'What did you do yesterday?',
      exampleCkb: 'تو دوھێ چ کر؟',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-where-did-you-go',
      en: 'where did you go?',
      ckb: 'تو کو چوو؟',
      pos: 'question',
      emoji: '🗺️',
      phonetic: '/weər dɪd juː ɡəʊ/',
      exampleEn: 'Where did you go?',
      exampleCkb: 'تو کو چوو؟',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-when-did-you-come',
      en: 'when did you come?',
      ckb: 'تو کیچان هات؟',
      pos: 'question',
      emoji: '⏰',
      phonetic: '/wen dɪd juː kʌm/',
      exampleEn: 'When did you come home?',
      exampleCkb: 'تو کیشان هاتە مال؟',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-who-did-you-see',
      en: 'who did you see?',
      ckb: 'تو کێ دیت؟',
      pos: 'question',
      emoji: '👀',
      phonetic: '/huː dɪd juː siː/',
      exampleEn: 'Who did you see at the shop?',
      exampleCkb: 'تو ل دۆکانێ کێ دیت؟',
      category: 'questions',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-yes-i-did',
      en: 'Yes, I did.',
      ckb: 'بەلێ، من کر.',
      pos: 'phrase',
      emoji: '✅',
      phonetic: '/jes aɪ dɪd/',
      exampleEn: 'Did you eat breakfast? Yes, I did.',
      exampleCkb: 'تو ژار خوار؟ بەلێ، من خوار.',
      category: 'answers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-no-i-didnt',
      en: "No, I didn't.",
      ckb: 'نەخێر، من نەکر.',
      pos: 'phrase',
      emoji: '❌',
      phonetic: '/nəʊ aɪ ˈdɪdənt/',
      exampleEn: "Did you go to work? No, I didn't.",
      exampleCkb: 'تو چوویە کار؟ نەخێر، ئەز نەچووم.',
      category: 'answers',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-how-was-it',
      en: 'how was it?',
      ckb: 'چەوا بوو؟',
      pos: 'question',
      emoji: '🎬',
      phonetic: '/haʊ wɒz ɪt/',
      exampleEn: 'How was the movie?',
      exampleCkb: 'فلم چەوا بوو؟',
      category: 'questions',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-busy',
      en: 'busy',
      ckb: 'مژوول',
      pos: 'adjective',
      emoji: '🏃',
      phonetic: '/ˈbɪzi/',
      exampleEn: 'I was busy yesterday.',
      exampleCkb: 'ئەز دوھێ مژوول بووم.',
      category: 'feelings',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-tired',
      en: 'tired',
      ckb: 'ماندوو',
      pos: 'adjective',
      emoji: '😪',
      phonetic: '/ˈtaɪəd/',
      exampleEn: 'I am tired today.',
      exampleCkb: 'ئەز ئەڤڕۆ وەسقی مە.',
      category: 'feelings',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l29-fun',
      en: 'fun',
      ckb: 'خۆش',
      pos: 'adjective',
      emoji: '🎉',
      phonetic: '/fʌn/',
      exampleEn: 'The movie was fun.',
      exampleCkb: 'فلم ب خۆش بوو.',
      category: 'feelings',
      difficulty: 3,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Did you work yesterday?', ckb: 'تو دوھێ کار کری؟' },
    { en: 'Yes, I did.', ckb: 'بەلێ، من کر.' },
    { en: "No, I didn't.", ckb: 'نەخێر، من نەکر.' },
    { en: 'Did you go to the shop?', ckb: 'تو چوویە دۆکانێ؟' },
    { en: 'Where did you go?', ckb: 'تو کو چوو؟' },
    { en: 'I went home.', ckb: 'ئەز چوومە مال.' },
    { en: 'What did you do?', ckb: 'تو چ کر؟' },
    { en: 'When did you come home?', ckb: 'تو کیشان هاتە مال؟' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Did you work yesterday, Dara?', ckb: 'تو دوھێ کار کر، دارا؟' },
    { characterId: 'dara', en: 'Yes, I did. I worked in the morning.', ckb: 'بەلێ، من کر. من سپێدە کار کر.' },
    { characterId: 'shirin', en: 'Did you go to the shop?', ckb: 'تو چوویە دۆکانێ؟' },
    { characterId: 'dara', en: "No, I didn't.", ckb: 'نەخێر، ئەز نەچووم.' },
    { characterId: 'shirin', en: 'Where did you go after work?', ckb: 'تو پاش کارێ کو چوو؟' },
    { characterId: 'dara', en: 'I went home. I watched a movie.', ckb: 'ئەز چوومە مال. من فلمەک تەماشە کر.' },
    { characterId: 'shirin', en: 'Did you see Rojin yesterday?', ckb: 'تو دوھێ ڕۆژین دیت؟' },
    { characterId: 'dara', en: 'Yes, I did. We drank coffee together.', ckb: 'بەلێ، من دیت. مە پێکڤە قەهوێ ڤەخوار.' },
  ],
};
