import type { Level } from '../../types/content';

export const level08: Level = {
  id: 8,
  titleEn: 'Everyday Objects',
  titleCkb: 'تشتێن ڕۆژانە',
  icon: '📱',
  objectiveEn: 'Name everyday objects and ask yes/no questions about them.',
  objectiveCkb: 'ناڤێن تشتێن ڕۆژانە فێر ببە و پرسیارێن بەلێ/نەخێر بکە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l8-phone',
      en: 'Phone',
      ckb: 'موبایل',
      pos: 'noun',
      emoji: '📱',
      phonetic: '/foʊn/',
      exampleEn: 'This is my phone.',
      exampleCkb: 'ئەڤە موبایلێ منە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-computer',
      en: 'Computer',
      ckb: 'کۆمپیوتەر',
      pos: 'noun',
      emoji: '💻',
      phonetic: '/kəmˈpjuːtər/',
      exampleEn: 'This is a computer.',
      exampleCkb: 'ئەڤە کۆمپیوتەرەکە.',
      category: 'objects',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-book',
      en: 'Book',
      ckb: 'پەرتووك',
      pos: 'noun',
      emoji: '📖',
      phonetic: '/bʊk/',
      exampleEn: 'The book is red.',
      exampleCkb: 'پەرتووك سورە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-pen',
      en: 'Pen',
      ckb: 'پێنووس',
      pos: 'noun',
      emoji: '🖊️',
      phonetic: '/pen/',
      exampleEn: 'The pen is blue.',
      exampleCkb: 'پێنووس شینە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-bag',
      en: 'Bag',
      ckb: 'چەنتە',
      pos: 'noun',
      emoji: '🎒',
      phonetic: '/bæɡ/',
      exampleEn: 'My bag is black.',
      exampleCkb: 'چەنتەیا من رەشە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-key',
      en: 'Key',
      ckb: 'کلیل',
      pos: 'noun',
      emoji: '🔑',
      phonetic: '/kiː/',
      exampleEn: 'This is my key.',
      exampleCkb: 'ئەڤە کلیلا منە.',
      category: 'objects',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-cup',
      en: 'Cup',
      ckb: 'کوپ',
      pos: 'noun',
      emoji: '☕',
      phonetic: '/kʌp/',
      exampleEn: 'The cup is white.',
      exampleCkb: 'کوپ سپییە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-bottle',
      en: 'Bottle',
      ckb: 'شیشە',
      pos: 'noun',
      emoji: '🍶',
      phonetic: '/ˈbɑːtəl/',
      exampleEn: 'This is a bottle.',
      exampleCkb: 'ئەڤە شیشەیەکە.',
      category: 'objects',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-water',
      en: 'Water',
      ckb: 'ئاڤ',
      pos: 'noun',
      emoji: '💧',
      phonetic: '/ˈwɔːtər/',
      exampleEn: 'Water is good.',
      exampleCkb: 'ئاڤ باشە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-chair',
      en: 'Chair',
      ckb: 'کورسی',
      pos: 'noun',
      emoji: '🪑',
      phonetic: '/tʃer/',
      exampleEn: 'The chair is small.',
      exampleCkb: 'کورسی بچووکە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-table',
      en: 'Table',
      ckb: 'مێز',
      pos: 'noun',
      emoji: '🍽️',
      phonetic: '/ˈteɪbəl/',
      exampleEn: 'The table is brown.',
      exampleCkb: 'مێز قاوەییە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l8-car',
      en: 'Car',
      ckb: 'ترۆمبێل',
      pos: 'noun',
      emoji: '🚗',
      phonetic: '/kɑːr/',
      exampleEn: 'The car is fast.',
      exampleCkb: 'ترۆمبێل خێرایە.',
      category: 'objects',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'This is a phone.', ckb: 'ئەڤە موبایلەکە.' },
    { en: 'It is a book.', ckb: 'ئەو پەرتووکەکە.' },
    { en: 'Is this a pen?', ckb: 'ئەڤە پێنووسەکە؟' },
    { en: 'Yes, it is.', ckb: 'بەڵێ، هەر وهایە.' },
    { en: 'No, it isn\'t.', ckb: 'نەخێر، ئەو نینە.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'What is this?', ckb: 'ئەڤە چیە؟' },
    { characterId: 'azad', en: 'It is a book.', ckb: 'ئەو پەرتووکەکە.' },
    { characterId: 'shirin', en: 'Is this a pen?', ckb: 'ئەڤە پێنووسەکە؟' },
    {
      characterId: 'azad',
      en: "No, it isn't. It is a key.",
      ckb: 'نەخێر، ئەو نینە. ئەو کلیلەکە.',
    },
    { characterId: 'shirin', en: 'Is this a phone?', ckb: 'ئەڤە موبایلەکە؟' },
    {
      characterId: 'azad',
      en: 'Yes, it is. It is my phone.',
      ckb: 'بەڵێ، هەر وهایە. ئەو موبایلێ منە.',
    },
    {
      characterId: 'shirin',
      en: 'And this? Is this a cup?',
      ckb: 'و ئەڤە؟ ئەڤە کوپەکە؟',
    },
    { characterId: 'azad', en: 'Yes, it is!', ckb: 'بەڵێ، هەر وهایە!' },
  ],
};
