import type { Level } from '../../types/content';

export const level36: Level = {
  id: 36,
  titleEn: 'Work & Jobs',
  titleCkb: 'کار و ئیش',
  icon: '💼',
  objectiveEn: 'Talk about your job, your workplace and your work schedule.',
  objectiveCkb: 'ل سەر کارا خو، جهێ کارێ و دەمێ کارێ ئاخڤە.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l36-work',
      en: 'work',
      ckb: 'کارکرن',
      pos: 'verb',
      emoji: '🛠️',
      phonetic: '/wɜːrk/',
      exampleEn: 'I work at an airport.',
      exampleCkb: 'ئەز ل فرۆکەخانێ کار دکەم.',
      category: 'work',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-job',
      en: 'job',
      ckb: 'کار',
      pos: 'noun',
      emoji: '💼',
      phonetic: '/dʒɑːb/',
      exampleEn: 'I have a new job.',
      exampleCkb: 'کارەکا نویا من هەیە.',
      category: 'work',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-manager',
      en: 'manager',
      ckb: 'ڕێڤەبەر',
      pos: 'noun',
      emoji: '👔',
      phonetic: '/ˈmænɪdʒər/',
      exampleEn: 'The manager is in a meeting.',
      exampleCkb: 'ڕێڤەبەر ل کۆمبوونێ دایە.',
      category: 'work',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-employee',
      en: 'employee',
      ckb: 'کارمەند',
      pos: 'noun',
      emoji: '🧑‍💼',
      phonetic: '/ɪmˈplɔɪiː/',
      exampleEn: 'She is a new employee.',
      exampleCkb: 'ئەو کارمەندەکا نووی یە.',
      category: 'work',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-customer',
      en: 'customer',
      ckb: 'کڕیار',
      pos: 'noun',
      emoji: '🛒',
      phonetic: '/ˈkʌstəmər/',
      exampleEn: 'The customer wants coffee.',
      exampleCkb: 'کڕیار قەهوەیێ دڤێت.',
      category: 'work',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-office',
      en: 'office',
      ckb: 'ئۆفیس',
      pos: 'noun',
      emoji: '🏢',
      phonetic: '/ˈɑːfɪs/',
      exampleEn: 'My office is near the airport.',
      exampleCkb: 'ئۆفیسا من ل نێزیکی فرۆکەخانێ یە.',
      category: 'work',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-meeting',
      en: 'meeting',
      ckb: 'کۆمبوون',
      pos: 'noun',
      emoji: '🗣️',
      phonetic: '/ˈmiːtɪŋ/',
      exampleEn: 'The meeting starts at nine.',
      exampleCkb: 'کۆمبوون ل دەمژمێر نێه دەست پێ دکەت.',
      category: 'work',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-break',
      en: 'break',
      ckb: 'بێهنڤەدان',
      pos: 'noun',
      emoji: '☕',
      phonetic: '/breɪk/',
      exampleEn: 'I drink coffee on my break.',
      exampleCkb: 'ئەز ل دەمێ بێهنڤەدانیێ قەهوەیێ دڤێم.',
      category: 'work',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-computer',
      en: 'computer',
      ckb: 'کۆمپیوتەر',
      pos: 'noun',
      emoji: '💻',
      phonetic: '/kəmˈpjuːtər/',
      exampleEn: 'I use a computer at work.',
      exampleCkb: 'ئەز ل کارێ کۆمپیوتەری بکار دئینم.',
      category: 'work',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-email',
      en: 'email',
      ckb: 'ئیمەیڵ',
      pos: 'noun',
      emoji: '📧',
      phonetic: '/ˈiːmeɪl/',
      exampleEn: 'I write emails at work.',
      exampleCkb: 'ئەز ل کارێ ئیمەیڵان دینیڤیسم.',
      category: 'work',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-busy',
      en: 'busy',
      ckb: 'مەشغوول',
      pos: 'adjective',
      emoji: '🏃',
      phonetic: '/ˈbɪzi/',
      exampleEn: 'I am very busy today.',
      exampleCkb: 'ئەڤڕۆ ئەز زۆر مەشغوول مە.',
      category: 'work',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-start',
      en: 'start',
      ckb: 'دەستپێکرن',
      pos: 'verb',
      emoji: '▶️',
      phonetic: '/stɑːrt/',
      exampleEn: 'I start work at eight.',
      exampleCkb: 'ئەز ل دەمژمێر هەشتێ دەست ب کارێ دکەم.',
      category: 'work',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l36-finish',
      en: 'finish',
      ckb: 'تمامکرن',
      pos: 'verb',
      emoji: '🏁',
      phonetic: '/ˈfɪnɪʃ/',
      exampleEn: 'I finish work at four.',
      exampleCkb: 'ئەز ل دەمژمێر چارێ کار تمام دکەم.',
      category: 'work',
      difficulty: 2,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'I work at a restaurant.', ckb: 'ئەز ل چێشتخانەیێ کار دکەم.' },
    { en: 'I work in an office.', ckb: 'ئەز ل ئۆفیسەکێ کار دکەم.' },
    { en: 'I start work at eight.', ckb: 'ئەز ل دەمژمێر هەشتێ دەست ب کارێ دکەم.' },
    { en: 'I finish at four.', ckb: 'ئەز ل دەمژمێر چارێ تمام دکەم.' },
    { en: 'I am busy now.', ckb: 'ئەز نوکە مەشغوول مە.' },
    { en: 'I have a meeting at ten.', ckb: 'کۆمبوونەکا من ل دەمژمێر دەهێ هەیە.' },
    { en: 'The customer needs help.', ckb: 'پێدڤیا کڕیاری ب هاریکاریێ هەیە.' },
  ],
  conversation: [
    { characterId: 'shirin', en: 'Good morning! Are you the new employee?', ckb: 'بەیانی تە باش! تو یی کارمەندا نوو؟' },
    { characterId: 'dara', en: 'Yes, I am. My name is Dara. Nice to meet you.', ckb: 'بەلێ، ئەزە. ناڤێ من دارا یە. دلخۆش مە ب دیتنا تە.' },
    { characterId: 'shirin', en: 'Nice to meet you too. I am Shirin, the manager.', ckb: 'ئەز ژی دلخۆش مە ب دیتنا تە. من شیرینە، ڕێڤەبەر.' },
    { characterId: 'dara', en: 'Where is my desk?', ckb: 'مێزا من ل کویە؟' },
    { characterId: 'shirin', en: 'It is next to the window. Your computer is on the desk.', ckb: 'ل نێزیکی پەنجەرەیێ یە. کۆمپیوتەرا تە ل سەر مێزێ یە.' },
    { characterId: 'dara', en: 'What time do I start and finish?', ckb: 'ل چ دەمژمێرەکێ دەست پێ دکەم و ل چ دەمژمێرەکێ تمام دکەم؟' },
    { characterId: 'shirin', en: 'You start at eight and finish at four.', ckb: 'ل دەمژمێر هەشتێ دەست پێ دکەی و ل دەمژمێر چارێ تمام دکەی.' },
    { characterId: 'dara', en: 'Great. When is my break?', ckb: 'باش. بێهنڤەدانا من ل کەیا؟' },
    { characterId: 'shirin', en: 'Your break is at twelve. You can have coffee in the kitchen.', ckb: 'بێهنڤەدانا تە ل دەمژمێر دوانزدەی یە. تو دشێی ل مەتبەخێ قەهوەیێ ڤەخوای.' },
    { characterId: 'dara', en: 'Thank you very much. See you in the meeting!', ckb: 'زۆر سوپاس. دبینمە تە ل کۆمبوونێ!' },
  ],
};
