import type { Level } from '../../types/content';

export const level40: Level = {
  id: 40,
  titleEn: 'English Adventure',
  titleCkb: 'سەرکێشیا ئینگلیزی',
  icon: '🏆',
  objectiveEn: 'Final challenge: travel to another city — airport, taxi, hotel and restaurant.',
  objectiveCkb: 'تاقیکرنا دوماهیێ: گەشت بۆ باژێرەکێ دی — فرۆکەخانە، تاکسی، ئۆتێل و چێشتخانە.',
  cefr: 'A2',
  vocab: [
    {
      id: 'l40-passport',
      en: 'passport',
      ckb: 'پاسپۆرت',
      pos: 'noun',
      emoji: '🛂',
      phonetic: '/ˈpæspɔːrt/',
      exampleEn: 'Here is my passport.',
      exampleCkb: 'ئەڤە پاسپۆرتا من.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-gate',
      en: 'gate',
      ckb: 'دەرگەهە',
      pos: 'noun',
      emoji: '🚪',
      phonetic: '/ɡeɪt/',
      exampleEn: 'Where is Gate 5?',
      exampleCkb: 'دەرگەهێ پێنجێ ل کویە؟',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-flight',
      en: 'flight',
      ckb: 'فرین',
      pos: 'noun',
      emoji: '✈️',
      phonetic: '/flaɪt/',
      exampleEn: 'What time is the flight?',
      exampleCkb: 'فرین ل چ دەمژمێرەکێ یە؟',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-taxi',
      en: 'taxi',
      ckb: 'تاکسی',
      pos: 'noun',
      emoji: '🚕',
      phonetic: '/ˈtæksi/',
      exampleEn: 'I need a taxi to the hotel.',
      exampleCkb: 'پێدڤیا من ب تاکسیەکێ هەیە بۆ ئۆتێلێ.',
      category: 'review',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-reservation',
      en: 'reservation',
      ckb: 'حەجز',
      pos: 'noun',
      emoji: '📋',
      phonetic: '/ˌrezərˈveɪʃn/',
      exampleEn: 'I have a reservation.',
      exampleCkb: 'حەجزەکا من هەیە.',
      category: 'review',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-room',
      en: 'room',
      ckb: 'ژوور',
      pos: 'noun',
      emoji: '🛏️',
      phonetic: '/ruːm/',
      exampleEn: 'My room is on the second floor.',
      exampleCkb: 'ژوورا من ل نهۆما دووێ یە.',
      category: 'review',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-menu',
      en: 'menu',
      ckb: 'لیستا خوارنێ',
      pos: 'noun',
      emoji: '📜',
      phonetic: '/ˈmenjuː/',
      exampleEn: 'Can I have the menu, please?',
      exampleCkb: 'ئەز دشێم لیستا خوارنێ وەربگرم، هیڤیدارین؟',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-bill',
      en: 'bill',
      ckb: 'حیساب',
      pos: 'noun',
      emoji: '🧾',
      phonetic: '/bɪl/',
      exampleEn: "I'd like the bill, please.",
      exampleCkb: 'ئەز حیسابی دڤێم، هیڤیدارین.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-turn-left',
      en: 'turn left',
      ckb: 'بزڤرێ چەپێ',
      pos: 'phrase',
      emoji: '⬅️',
      phonetic: '/tɜːrn left/',
      exampleEn: 'Turn left at the corner.',
      exampleCkb: 'ل گۆشەیێ بزڤرێ چەپێ.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-go-straight',
      en: 'go straight',
      ckb: 'ڕاست بچە',
      pos: 'phrase',
      emoji: '⬆️',
      phonetic: '/ɡoʊ streɪt/',
      exampleEn: 'Go straight, then turn right.',
      exampleCkb: 'ڕاست بچە، پاشی بزڤرێ راستێ.',
      category: 'review',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-manager',
      en: 'manager',
      ckb: 'ڕێڤەبەر',
      pos: 'noun',
      emoji: '👔',
      phonetic: '/ˈmænɪdʒər/',
      exampleEn: 'The manager is busy now.',
      exampleCkb: 'ڕێڤەبەر نوکە مەشغوولە.',
      category: 'review',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-sick',
      en: 'sick',
      ckb: 'نەخۆش',
      pos: 'adjective',
      emoji: '🤒',
      phonetic: '/sɪk/',
      exampleEn: "I don't feel well. I need a doctor.",
      exampleCkb: 'ئەز خوود باش حەس ناکەم. پێدڤیا من ب دکتورەکی هەیە.',
      category: 'review',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-cheaper',
      en: 'cheaper',
      ckb: 'هەرزانتر',
      pos: 'adjective',
      emoji: '💰',
      phonetic: '/ˈtʃiːpər/',
      exampleEn: 'This one is cheaper than that one.',
      exampleCkb: 'ئەڤە ژ وان هەرزانترە.',
      category: 'review',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l40-tomorrow',
      en: 'tomorrow',
      ckb: 'سبەی',
      pos: 'other',
      emoji: '🌅',
      phonetic: '/təˈmɑːroʊ/',
      exampleEn: "I'm going to travel tomorrow.",
      exampleCkb: 'ئەز دێ سبەی گەشتێ بکەم.',
      category: 'review',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'Where is the gate?', ckb: 'دەرگەهە ل کویە؟' },
    { en: 'I have a reservation.', ckb: 'حەجزەکا من هەیە.' },
    { en: "I'd like the bill, please.", ckb: 'ئەز حیسابی دڤێم، هیڤیدارین.' },
    { en: 'Turn left and go straight.', ckb: 'بزڤرێ چەپێ و ڕاست بچە.' },
    { en: 'I work at an airport.', ckb: 'ئەز ل فرۆکەخانێ کار دکەم.' },
    { en: 'My head hurts.', ckb: 'سەرێ من دئێشێت.' },
    { en: 'The blue car is faster.', ckb: 'ترۆمبێلا شین خێراترە.' },
    { en: "I'm going to visit my family tomorrow.", ckb: 'ئەز دێ سبەی سەرەدانا خیزانا خو بکەم.' },
  ],
  conversation: [
    { characterId: 'dara', en: 'Excuse me, where is Gate 5?', ckb: 'ببورە، دەرگەهێ پێنجێ ل کویە؟' },
    { characterId: 'shirin', en: 'Go straight and turn left. Have a good flight!', ckb: 'ڕاست بچە و بزڤرێ چەپێ. گەشتەکا خۆش!' },
    { characterId: 'azad', en: 'Hello! Where do you want to go?', ckb: 'سلاو! تو دڤێی بچی کو؟' },
    { characterId: 'dara', en: 'To the Grand Hotel, please.', ckb: 'بۆ ئۆتێلا گراند، هیڤیدارین.' },
    { characterId: 'azad', en: 'It is twenty minutes. The price is ten dollars.', ckb: 'بیست خولەکە. بها یا وی دەه دۆلارە.' },
    { characterId: 'rojin', en: 'Welcome to the Grand Hotel. Can I help you?', ckb: 'ب خێر هاتوی بۆ ئۆتێلا گراند. ئەز دشێم هاریکاریا تە بکەم؟' },
    { characterId: 'dara', en: 'Yes, I have a reservation. My name is Dara.', ckb: 'بەلێ، حەجزەکا من هەیە. ناڤێ من دارا یە.' },
    { characterId: 'rojin', en: 'Your room is on the second floor. Breakfast is at eight.', ckb: 'ژوورا تە ل نهۆما دووێ یە. تەشتە ل دەمژمێر هەشتێ یە.' },
    { characterId: 'dara', en: 'Thank you! Later I am going to the restaurant next to the hotel.', ckb: 'سوپاس! پاشی ئەز دێ بچمە چێشتخانا نێزیکی ئۆتێلێ.' },
    { characterId: 'dara', en: "I'd like chicken and rice, and the bill, please. What an adventure!", ckb: 'ئەز مرشک و برنج دڤێم، و حیساب ژی، هیڤیدارین. سەرکێشیەکا گەلەک خۆش!' },
  ],
};
