import type { Level } from '../../types/content';

export const level10: Level = {
  id: 10,
  titleEn: 'Numbers, Money & Shopping',
  titleCkb: 'ژمارە، پارە و کڕین',
  icon: '💰',
  objectiveEn: 'Learn money and shopping words and ask about prices.',
  objectiveCkb: 'پەیڤێن پارە و کڕینێ فێر ببە و بپرسە بها چەندە.',
  cefr: 'A1',
  vocab: [
    {
      id: 'l10-price',
      en: 'price',
      ckb: 'بها',
      pos: 'noun',
      emoji: '🏷️',
      phonetic: '/praɪs/',
      exampleEn: 'The price is good.',
      exampleCkb: 'بها باشە.',
      category: 'shopping',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-money',
      en: 'money',
      ckb: 'پارە',
      pos: 'noun',
      emoji: '💰',
      phonetic: '/ˈmʌni/',
      exampleEn: 'I have money.',
      exampleCkb: 'پارە مە هەیە.',
      category: 'money',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-cheap',
      en: 'cheap',
      ckb: 'هەرزان',
      pos: 'adjective',
      emoji: '💲',
      phonetic: '/tʃiːp/',
      exampleEn: 'This is cheap.',
      exampleCkb: 'ئەڤە هەرزانە.',
      category: 'shopping',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-expensive',
      en: 'expensive',
      ckb: 'گران',
      pos: 'adjective',
      emoji: '💎',
      phonetic: '/ɪkˈspɛnsɪv/',
      exampleEn: 'This is expensive.',
      exampleCkb: 'ئەڤە گرانە.',
      category: 'shopping',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-buy',
      en: 'buy',
      ckb: 'کڕین (ئەز دکڕم)',
      pos: 'verb',
      emoji: '🛒',
      phonetic: '/baɪ/',
      exampleEn: 'I buy bread.',
      exampleCkb: 'ئەز نانێ دکڕم.',
      category: 'shopping',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-want',
      en: 'want',
      ckb: 'ڤێستن (ئەز دڤێم)',
      pos: 'verb',
      emoji: '🙋',
      phonetic: '/wɒnt/',
      exampleEn: 'I want water.',
      exampleCkb: 'ئەز ئاڤێ دڤێم.',
      category: 'shopping',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-have',
      en: 'have',
      ckb: 'هەبوون (مە هەیە)',
      pos: 'verb',
      emoji: '🤲',
      phonetic: '/hæv/',
      exampleEn: 'I have two apples.',
      exampleCkb: 'دوو سێڤ مە هەنە.',
      category: 'shopping',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-dollar',
      en: 'dollar',
      ckb: 'دۆلار',
      pos: 'noun',
      emoji: '💵',
      phonetic: '/ˈdɒlər/',
      exampleEn: 'It is ten dollars.',
      exampleCkb: 'بها وی دەھ دۆلارە.',
      category: 'money',
      difficulty: 1,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-how-much',
      en: 'how much',
      ckb: 'ب چەند؟',
      pos: 'question',
      emoji: '❓',
      phonetic: '/haʊ mʌtʃ/',
      exampleEn: 'How much is it?',
      exampleCkb: 'بها وی چەندە؟',
      category: 'shopping',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-twenty',
      en: 'twenty',
      ckb: 'بیست',
      pos: 'number',
      emoji: '2️⃣0️⃣',
      phonetic: '/ˈtwɛnti/',
      exampleEn: 'It is twenty dollars.',
      exampleCkb: 'بها وی بیست دۆلارە.',
      category: 'numbers',
      difficulty: 2,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-fifty',
      en: 'fifty',
      ckb: 'پێنجی',
      pos: 'number',
      emoji: '5️⃣0️⃣',
      phonetic: '/ˈfɪfti/',
      exampleEn: 'It is fifty dollars.',
      exampleCkb: 'بها وی پێنجی دۆلارە.',
      category: 'numbers',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-hundred',
      en: 'hundred',
      ckb: 'سەد',
      pos: 'number',
      emoji: '💯',
      phonetic: '/ˈhʌndrəd/',
      exampleEn: 'It is one hundred dollars.',
      exampleCkb: 'بها وی سەد دۆلارە.',
      category: 'numbers',
      difficulty: 3,
      bahdiniReviewed: false,
    },
    {
      id: 'l10-shop',
      en: 'shop',
      ckb: 'دکان',
      pos: 'noun',
      emoji: '🏪',
      phonetic: '/ʃɒp/',
      exampleEn: 'The shop is big.',
      exampleCkb: 'دکان مەزنە.',
      category: 'shopping',
      difficulty: 1,
      bahdiniReviewed: false,
    },
  ],
  grammarPatterns: [
    { en: 'How much is it?', ckb: 'بها وی چەندە؟' },
    { en: 'It is five dollars.', ckb: 'بها وی پێنج دۆلارە.' },
    { en: 'I want this.', ckb: 'ئەز ڤێ دڤێم.' },
    { en: 'I want two.', ckb: 'ئەز دوو دڤێم.' },
    { en: 'Do you have money?', ckb: 'پارە تە هەیە؟' },
  ],
  conversation: [
    { characterId: 'dara', en: 'Hello. How much is this?', ckb: 'سلاو. بها ڤێ چەندە؟' },
    { characterId: 'azad', en: 'It is ten dollars.', ckb: 'بها وی دەھ دۆلارە.' },
    { characterId: 'dara', en: 'That is expensive!', ckb: 'ئەوە گرانە!' },
    { characterId: 'azad', en: 'No, it is cheap. Look, this is five dollars.', ckb: 'نەخێر، هەرزانە. تەماشە بکە، بها ڤێ پێنج دۆلارە.' },
    { characterId: 'dara', en: 'OK. I want two.', ckb: 'باشە. ئەز دوو دڤێم.' },
    { characterId: 'azad', en: 'That is ten dollars.', ckb: 'دبیت دەھ دۆلار.' },
    { characterId: 'dara', en: 'Here you are. Thank you!', ckb: 'بگرە. زۆر سپاس!' },
  ],
};
