// Downloads the Google Fonts woff2 files referenced by a css2 response and
// rewrites the CSS to local /fonts/ paths so the app is fully self-contained.
// Run: node scripts/fetch-fonts.mjs <css-url>
import { writeFileSync, mkdirSync } from 'node:fs';

const cssUrl = process.argv[2];
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text();

// Only keep the arabic + latin subsets (others are unused by the app).
const blocks = css.split('/*').slice(1);
const kept = blocks.filter((b) => b.startsWith(' arabic */') || b.startsWith(' latin */'));

const urlMap = new Map();
for (const block of kept) {
  const m = block.match(/url\((https:[^)]+\.woff2)\)/);
  if (!m) continue;
  const url = m[1];
  if (!urlMap.has(url)) {
    const family = block.match(/font-family: '([^']+)'/)[1].replace(/\s+/g, '');
    const weight = block.match(/font-weight: (\d+)/)[1];
    const subset = block.startsWith(' arabic */') ? 'arabic' : 'latin';
    urlMap.set(url, `${family}-${weight}-${subset}.woff2`);
  }
}

mkdirSync(new URL('../public/fonts/', import.meta.url), { recursive: true });
for (const [url, name] of urlMap) {
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  writeFileSync(new URL(`../public/fonts/${name}`, import.meta.url), buf);
  console.log(`${name} ${buf.length}b`);
}

const localCss =
  '/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs */\n' +
  kept
    .map((b) => {
      const body = b.slice(b.indexOf('*/') + 2).trim();
      const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
      return url ? body.replace(url, `/fonts/${urlMap.get(url)}`) : body;
    })
    .join('\n');
writeFileSync(new URL('../src/fonts.css', import.meta.url), localCss + '\n');
console.log('src/fonts.css written');
